// Code generated by cmd/isagen. DO NOT EDIT.
// clang-format off

// MicroC seen as C: the device pins, the four operand enums, the machine
// constants and the intrinsics. Include it with -std=c23 -ffreestanding, which
// is what the generated compile_flags.txt naming it does.
//
// C is the looser language of the two. Every program MicroC accepts compiles
// here; the reverse does not hold, and each place it does not is noted below.
// Nothing here enforces a MicroC rule, so a clean C parse is not an analysis.
//
// Extracted from Stationeers depot manifest 2546537964923579038, game version 0.2.6403.27689.

#ifndef IC10_PRELUDE_H
#define IC10_PRELUDE_H

// The pins a housing exposes, and db for the housing itself.
//
// An enum is what makes `const dev sensor = d0;` legal at file scope: C needs a
// constant expression there and an enumeration constant is the only one that
// names a device. C converts an enumeration to int freely, so d0 + 1 and
// d0 < d1 compile here where MicroC rejects them.
//
// Higher pins are absent because no housing has one.
typedef enum ic10_dev { db = -1, d0 = 0, d1, d2, d3, d4, d5 } dev;

// Device properties: the logic type argument of the direct and batch forms.
typedef enum ic10_logic_e {
    None [[deprecated("the game marks this logic type retired")]] = 0,
    Power = 1,
    Open = 2,
    Mode = 3,
    Error = 4,
    Pressure = 5,
    Temperature = 6,
    PressureExternal = 7,
    PressureInternal = 8,
    Activate = 9,
    Lock = 10,
    Charge = 11,
    Setting = 12,
    Reagents = 13,
    RatioOxygen = 14,
    RatioCarbonDioxide = 15,
    RatioNitrogen = 16,
    RatioPollutant = 17,
    RatioMethane = 18,
    RatioWater = 19,
    Horizontal = 20,
    Vertical = 21,
    SolarAngle = 22,
    Maximum = 23,
    Ratio = 24,
    PowerPotential = 25,
    PowerActual = 26,
    Quantity = 27,
    On = 28,
    ImportQuantity [[deprecated("the game marks this logic type retired")]] = 29,
    ImportSlotOccupant [[deprecated("the game marks this logic type retired")]] = 30,
    ExportQuantity [[deprecated("the game marks this logic type retired")]] = 31,
    ExportSlotOccupant [[deprecated("the game marks this logic type retired")]] = 32,
    RequiredPower = 33,
    HorizontalRatio = 34,
    VerticalRatio = 35,
    PowerRequired = 36,
    Idle = 37,
    Color = 38,
    ElevatorSpeed = 39,
    ElevatorLevel = 40,
    RecipeHash = 41,
    ExportSlotHash [[deprecated("the game marks this logic type retired")]] = 42,
    ImportSlotHash [[deprecated("the game marks this logic type retired")]] = 43,
    PlantHealth1 [[deprecated("the game marks this logic type retired")]] = 44,
    PlantHealth2 [[deprecated("the game marks this logic type retired")]] = 45,
    PlantHealth3 [[deprecated("the game marks this logic type retired")]] = 46,
    PlantHealth4 [[deprecated("the game marks this logic type retired")]] = 47,
    PlantGrowth1 [[deprecated("the game marks this logic type retired")]] = 48,
    PlantGrowth2 [[deprecated("the game marks this logic type retired")]] = 49,
    PlantGrowth3 [[deprecated("the game marks this logic type retired")]] = 50,
    PlantGrowth4 [[deprecated("the game marks this logic type retired")]] = 51,
    PlantEfficiency1 [[deprecated("the game marks this logic type retired")]] = 52,
    PlantEfficiency2 [[deprecated("the game marks this logic type retired")]] = 53,
    PlantEfficiency3 [[deprecated("the game marks this logic type retired")]] = 54,
    PlantEfficiency4 [[deprecated("the game marks this logic type retired")]] = 55,
    PlantHash1 [[deprecated("the game marks this logic type retired")]] = 56,
    PlantHash2 [[deprecated("the game marks this logic type retired")]] = 57,
    PlantHash3 [[deprecated("the game marks this logic type retired")]] = 58,
    PlantHash4 [[deprecated("the game marks this logic type retired")]] = 59,
    RequestHash = 60,
    CompletionRatio = 61,
    ClearMemory = 62,
    ExportCount = 63,
    ImportCount = 64,
    PowerGeneration = 65,
    TotalMoles = 66,
    Volume = 67,
    Plant = 68,
    Harvest = 69,
    Output = 70,
    PressureSetting = 71,
    TemperatureSetting = 72,
    TemperatureExternal = 73,
    Filtration = 74,
    AirRelease = 75,
    PositionX = 76,
    PositionY = 77,
    PositionZ = 78,
    VelocityMagnitude = 79,
    VelocityRelativeX = 80,
    VelocityRelativeY = 81,
    VelocityRelativeZ = 82,
    RatioNitrousOxide = 83,
    PrefabHash = 84,
    ForceWrite = 85,
    SignalStrength = 86,
    SignalID = 87,
    TargetX = 88,
    TargetY = 89,
    TargetZ = 90,
    SettingInput = 91,
    SettingOutput = 92,
    CurrentResearchPodType = 93,
    ManualResearchRequiredPod = 94,
    MineablesInVicinity = 95,
    MineablesInQueue = 96,
    NextWeatherEventTime = 97,
    Combustion = 98,
    Fuel = 99,
    ReturnFuelCost = 100,
    CollectableGoods = 101,
    Time = 102,
    Bpm = 103,
    EnvironmentEfficiency = 104,
    WorkingGasEfficiency = 105,
    PressureInput = 106,
    TemperatureInput = 107,
    RatioOxygenInput = 108,
    RatioCarbonDioxideInput = 109,
    RatioNitrogenInput = 110,
    RatioPollutantInput = 111,
    RatioMethaneInput = 112,
    RatioWaterInput = 113,
    RatioNitrousOxideInput = 114,
    TotalMolesInput = 115,
    PressureInput2 = 116,
    TemperatureInput2 = 117,
    RatioOxygenInput2 = 118,
    RatioCarbonDioxideInput2 = 119,
    RatioNitrogenInput2 = 120,
    RatioPollutantInput2 = 121,
    RatioMethaneInput2 = 122,
    RatioWaterInput2 = 123,
    RatioNitrousOxideInput2 = 124,
    TotalMolesInput2 = 125,
    PressureOutput = 126,
    TemperatureOutput = 127,
    RatioOxygenOutput = 128,
    RatioCarbonDioxideOutput = 129,
    RatioNitrogenOutput = 130,
    RatioPollutantOutput = 131,
    RatioMethaneOutput = 132,
    RatioWaterOutput = 133,
    RatioNitrousOxideOutput = 134,
    TotalMolesOutput = 135,
    PressureOutput2 = 136,
    TemperatureOutput2 = 137,
    RatioOxygenOutput2 = 138,
    RatioCarbonDioxideOutput2 = 139,
    RatioNitrogenOutput2 = 140,
    RatioPollutantOutput2 = 141,
    RatioMethaneOutput2 = 142,
    RatioWaterOutput2 = 143,
    RatioNitrousOxideOutput2 = 144,
    TotalMolesOutput2 = 145,
    CombustionInput = 146,
    CombustionInput2 = 147,
    CombustionOutput = 148,
    CombustionOutput2 = 149,
    OperationalTemperatureEfficiency = 150,
    TemperatureDifferentialEfficiency = 151,
    PressureEfficiency = 152,
    CombustionLimiter = 153,
    Throttle = 154,
    Rpm = 155,
    Stress = 156,
    InterrogationProgress = 157,
    TargetPadIndex = 158,
    SizeX = 160,
    SizeY = 161,
    SizeZ = 162,
    MinimumWattsToContact = 163,
    WattsReachingContact = 164,
    Channel0 = 165,
    Channel1 = 166,
    Channel2 = 167,
    Channel3 = 168,
    Channel4 = 169,
    Channel5 = 170,
    Channel6 = 171,
    Channel7 = 172,
    LineNumber = 173,
    Flush = 174,
    SoundAlert = 175,
    SolarIrradiance = 176,
    RatioLiquidNitrogen = 177,
    RatioLiquidNitrogenInput = 178,
    RatioLiquidNitrogenInput2 = 179,
    RatioLiquidNitrogenOutput = 180,
    RatioLiquidNitrogenOutput2 = 181,
    VolumeOfLiquid = 182,
    RatioLiquidOxygen = 183,
    RatioLiquidOxygenInput = 184,
    RatioLiquidOxygenInput2 = 185,
    RatioLiquidOxygenOutput = 186,
    RatioLiquidOxygenOutput2 = 187,
    RatioLiquidMethane = 188,
    RatioLiquidMethaneInput = 189,
    RatioLiquidMethaneInput2 = 190,
    RatioLiquidMethaneOutput = 191,
    RatioLiquidMethaneOutput2 = 192,
    RatioSteam = 193,
    RatioSteamInput = 194,
    RatioSteamInput2 = 195,
    RatioSteamOutput = 196,
    RatioSteamOutput2 = 197,
    ContactTypeId = 198,
    RatioLiquidCarbonDioxide = 199,
    RatioLiquidCarbonDioxideInput = 200,
    RatioLiquidCarbonDioxideInput2 = 201,
    RatioLiquidCarbonDioxideOutput = 202,
    RatioLiquidCarbonDioxideOutput2 = 203,
    RatioLiquidPollutant = 204,
    RatioLiquidPollutantInput = 205,
    RatioLiquidPollutantInput2 = 206,
    RatioLiquidPollutantOutput = 207,
    RatioLiquidPollutantOutput2 = 208,
    RatioLiquidNitrousOxide = 209,
    RatioLiquidNitrousOxideInput = 210,
    RatioLiquidNitrousOxideInput2 = 211,
    RatioLiquidNitrousOxideOutput = 212,
    RatioLiquidNitrousOxideOutput2 = 213,
    Progress = 214,
    DestinationCode = 215,
    Acceleration = 216,
    ReferenceId = 217,
    AutoShutOff = 218,
    Mass = 219,
    DryMass = 220,
    Thrust = 221,
    Weight = 222,
    ThrustToWeight = 223,
    TimeToDestination = 224,
    BurnTimeRemaining = 225,
    AutoLand = 226,
    ForwardX = 227,
    ForwardY = 228,
    ForwardZ = 229,
    Orientation = 230,
    VelocityX = 231,
    VelocityY = 232,
    VelocityZ = 233,
    PassedMoles = 234,
    ExhaustVelocity = 235,
    FlightControlRule = 236,
    ReEntryAltitude = 237,
    Apex = 238,
    EntityState = 239,
    DrillCondition = 240,
    Index = 241,
    CelestialHash = 242,
    AlignmentError = 243,
    DistanceAu = 244,
    OrbitPeriod = 245,
    Inclination = 246,
    Eccentricity = 247,
    SemiMajorAxis = 248,
    DistanceKm = 249,
    CelestialParentHash = 250,
    TrueAnomaly = 251,
    RatioHydrogen = 252,
    RatioLiquidHydrogen = 253,
    RatioPollutedWater = 254,
    Discover = 255,
    Chart = 256,
    Survey = 257,
    NavPoints = 258,
    ChartedNavPoints = 259,
    Sites = 260,
    CurrentCode = 261,
    Density = 262,
    Richness = 263,
    Size = 264,
    TotalQuantity = 265,
    MinedQuantity = 266,
    BestContactFilter = 267,
    NameHash = 268,
    Altitude = 269,
    TargetSlotIndex = 270,
    TargetPrefabHash = 271,
    Extended = 272,
    NetworkFault = 273,
    ProportionalGain = 274,
    IntegralGain = 275,
    DerivativeGain = 276,
    Minimum = 277,
    Setpoint = 278,
    Reset = 279,
    StackSize = 280,
    NextWeatherHash = 281,
    ContactSlotIndex = 282,
    RatioHydrazine = 283,
    RatioLiquidHydrazine = 284,
    RatioLiquidAlcohol = 285,
    RatioHelium = 286,
    RatioLiquidSodiumChloride = 287,
    RatioSilanol = 288,
    RatioLiquidSilanol = 289,
    RatioHydrochloricAcid = 290,
    RatioLiquidHydrochloricAcid = 291,
    RatioOzone = 292,
    RatioLiquidOzone = 293,
    RatioHydrogenInput = 294,
    RatioHydrogenInput2 = 295,
    RatioHydrogenOutput = 296,
    RatioHydrogenOutput2 = 297,
    RatioLiquidHydrogenInput = 298,
    RatioLiquidHydrogenInput2 = 299,
    RatioLiquidHydrogenOutput = 300,
    RatioLiquidHydrogenOutput2 = 301,
    RatioPollutedWaterInput = 302,
    RatioPollutedWaterInput2 = 303,
    RatioPollutedWaterOutput = 304,
    RatioPollutedWaterOutput2 = 305,
    RatioHydrazineInput = 306,
    RatioHydrazineInput2 = 307,
    RatioHydrazineOutput = 308,
    RatioHydrazineOutput2 = 309,
    RatioLiquidHydrazineInput = 310,
    RatioLiquidHydrazineInput2 = 311,
    RatioLiquidHydrazineOutput = 312,
    RatioLiquidHydrazineOutput2 = 313,
    RatioLiquidAlcoholInput = 314,
    RatioLiquidAlcoholInput2 = 315,
    RatioLiquidAlcoholOutput = 316,
    RatioLiquidAlcoholOutput2 = 317,
    RatioHeliumInput = 318,
    RatioHeliumInput2 = 319,
    RatioHeliumOutput = 320,
    RatioHeliumOutput2 = 321,
    RatioLiquidSodiumChlorideInput = 322,
    RatioLiquidSodiumChlorideInput2 = 323,
    RatioLiquidSodiumChlorideOutput = 324,
    RatioLiquidSodiumChlorideOutput2 = 325,
    RatioSilanolInput = 326,
    RatioSilanolInput2 = 327,
    RatioSilanolOutput = 328,
    RatioSilanolOutput2 = 329,
    RatioLiquidSilanolInput = 330,
    RatioLiquidSilanolInput2 = 331,
    RatioLiquidSilanolOutput = 332,
    RatioLiquidSilanolOutput2 = 333,
    RatioHydrochloricAcidInput = 334,
    RatioHydrochloricAcidInput2 = 335,
    RatioHydrochloricAcidOutput = 336,
    RatioHydrochloricAcidOutput2 = 337,
    RatioLiquidHydrochloricAcidInput = 338,
    RatioLiquidHydrochloricAcidInput2 = 339,
    RatioLiquidHydrochloricAcidOutput = 340,
    RatioLiquidHydrochloricAcidOutput2 = 341,
    RatioOzoneInput = 342,
    RatioOzoneInput2 = 343,
    RatioOzoneOutput = 344,
    RatioOzoneOutput2 = 345,
    RatioLiquidOzoneInput = 346,
    RatioLiquidOzoneInput2 = 347,
    RatioLiquidOzoneOutput = 348,
    RatioLiquidOzoneOutput2 = 349,
    HealthDamage = 350,
    StunDamage = 351,
    CurrentNodeType = 352,
    TargetNodeType = 353,
    EnergyConvected = 354,
    EnergyRadiated = 355,
    Dispense = 356,
    DispenseSlot = 357,
    Gravity = 358,
} ic10_logic;

// Slot properties: the slot type argument of the slot forms.
//
// A name an earlier family already declared is omitted here, because C admits
// one enumerator per name in a scope and the families give the shared names
// different values. Spelling one where another family's type is expected still
// compiles, since C converts between enumeration types.
typedef enum ic10_slot_e {
    // None = 0 omitted; ic10_logic declares it as 0.
    Occupied = 1,
    OccupantHash = 2,
    // Quantity = 3 omitted; ic10_logic declares it as 27.
    Damage = 4,
    Efficiency = 5,
    Health = 6,
    Growth = 7,
    // Pressure = 8 omitted; ic10_logic declares it as 5.
    // Temperature = 9 omitted; ic10_logic declares it as 6.
    // Charge = 10 omitted; ic10_logic declares it as 11.
    ChargeRatio = 11,
    Class = 12,
    PressureWaste = 13,
    PressureAir = 14,
    MaxQuantity = 15,
    Mature = 16,
    // PrefabHash = 17 omitted; ic10_logic declares it as 84.
    Seeding = 18,
    // LineNumber = 19 omitted; ic10_logic declares it as 173.
    // Volume = 20 omitted; ic10_logic declares it as 67.
    // Open = 21 omitted; ic10_logic declares it as 2.
    // On = 22 omitted; ic10_logic declares it as 28.
    // Lock = 23 omitted; ic10_logic declares it as 10.
    SortingClass = 24,
    FilterType = 25,
    // ReferenceId = 26 omitted; ic10_logic declares it as 217.
    HarvestedHash = 27,
    // Mode = 28 omitted; ic10_logic declares it as 3.
    MaturityRatio = 29,
    SeedingRatio = 30,
    FreeSlots = 31,
    TotalSlots = 32,
} ic10_slot;

// Aggregation modes: the last argument of the batch load forms.
typedef enum ic10_batch_e {
    Average = 0,
    Sum = 1,
    // Minimum = 2 omitted; ic10_logic declares it as 277.
    // Maximum = 3 omitted; ic10_logic declares it as 23.
    Count = 4,
} ic10_batch;

// Reagent views: the mode argument of __ic_load_reagent.
typedef enum ic10_reagent_e {
    Contents = 0,
    Required = 1,
    Recipe = 2,
    TotalContents = 3,
} ic10_reagent;

// The chip's own constants, which a program cannot write for itself: deg2rad
// and rad2deg are float literals widened to double, so folding pi/180 at double
// precision produces a different number from the chip.
constexpr double pi = 3.141592653589793;
constexpr double tau = 6.283185307179586;
constexpr double deg2rad = 0.01745329238474369;
constexpr double rad2deg = 57.295780181884766;
constexpr double epsilon = 5e-324;
constexpr double rgas = 8.31446261815324;

// The intrinsics. Three of their rules no prototype can carry, each of them C
// admitting more than MicroC does:
//
//   - a slot index must be a constant expression, where C takes any int;
//   - __ic_hash takes a string literal, where C takes any const char *;
//   - a device argument must be a pin, a dev object or a dev parameter, and is
//     never computed.
double    __ic_load(dev d, ic10_logic t);
void      __ic_store(dev d, ic10_logic t, double v);
double    __ic_load_slot(dev d, long long slot, ic10_slot t);
void      __ic_store_slot(dev d, long long slot, ic10_slot t, double v);
double    __ic_load_batch(long long hash, ic10_logic t, ic10_batch m);
void      __ic_store_batch(long long hash, ic10_logic t, double v);
double    __ic_load_batch_named(long long hash, long long name, ic10_logic t, ic10_batch m);
void      __ic_store_batch_named(long long hash, long long name, ic10_logic t, double v);
double    __ic_load_batch_slot(long long hash, long long slot, ic10_slot t, ic10_batch m);
void      __ic_store_batch_slot(long long hash, long long slot, ic10_slot t, double v);
double    __ic_load_batch_named_slot(long long hash, long long name, long long slot, ic10_slot t, ic10_batch m);
double    __ic_load_reagent(dev d, ic10_reagent m, long long hash);
bool      __ic_device_present(dev d);
long long __ic_hash(const char *s);
void      __ic_yield(void);
void      __ic_sleep(double seconds);
bool      __ic_isnan(double v);
double    __ic_rand(void);
double    __ic_sqrt(double v);
double    __ic_abs(double v);
double    __ic_sgn(double v);
double    __ic_round(double v);
double    __ic_trunc(double v);
double    __ic_ceil(double v);
double    __ic_floor(double v);
double    __ic_log(double v);
double    __ic_exp(double v);
double    __ic_sin(double v);
double    __ic_cos(double v);
double    __ic_tan(double v);
double    __ic_asin(double v);
double    __ic_acos(double v);
double    __ic_atan(double v);
double    __ic_min(double a, double b);
double    __ic_max(double a, double b);
double    __ic_pow(double a, double b);
double    __ic_atan2(double a, double b);
double    __ic_clamp(double a, double b, double c);
double    __ic_lerp(double a, double b, double c);

#endif // IC10_PRELUDE_H
