// Code generated by cmd/isagen. DO NOT EDIT.

package ic10

import "math"

// ManifestID is the Steam depot manifest these tables were extracted from.
// It names the assembly's exact bytes, so a re-extraction that reaches it
// lands on this table again.
const ManifestID = "2546537964923579038"

// GameVersion is the assembly file version these tables were extracted from.
const GameVersion = "0.2.6403.27689"

// Opcodes in game enum order. The numeric value is the ScriptCommand
// ordinal and is also the index into Instructions.
const (
	OpL      Opcode = 0
	OpS      Opcode = 1
	OpLs     Opcode = 2
	OpLr     Opcode = 3
	OpSb     Opcode = 4
	OpLb     Opcode = 5
	OpAlias  Opcode = 6
	OpMove   Opcode = 7
	OpAdd    Opcode = 8
	OpSub    Opcode = 9
	OpSdse   Opcode = 10
	OpSdns   Opcode = 11
	OpSlt    Opcode = 12
	OpSgt    Opcode = 13
	OpSle    Opcode = 14
	OpSge    Opcode = 15
	OpSeq    Opcode = 16
	OpSne    Opcode = 17
	OpSap    Opcode = 18
	OpSna    Opcode = 19
	OpAnd    Opcode = 20
	OpOr     Opcode = 21
	OpXor    Opcode = 22
	OpNor    Opcode = 23
	OpMul    Opcode = 24
	OpDiv    Opcode = 25
	OpMod    Opcode = 26
	OpJ      Opcode = 27
	OpBltz   Opcode = 28
	OpBgez   Opcode = 29
	OpBlez   Opcode = 30
	OpBgtz   Opcode = 31
	OpBdse   Opcode = 32
	OpBdns   Opcode = 33
	OpBeq    Opcode = 34
	OpBne    Opcode = 35
	OpBap    Opcode = 36
	OpBna    Opcode = 37
	OpJal    Opcode = 38
	OpBrdse  Opcode = 39
	OpBrdns  Opcode = 40
	OpBltzal Opcode = 41
	OpBgezal Opcode = 42
	OpBlezal Opcode = 43
	OpBgtzal Opcode = 44
	OpBeqal  Opcode = 45
	OpBneal  Opcode = 46
	OpJr     Opcode = 47
	OpBdseal Opcode = 48
	OpBdnsal Opcode = 49
	OpBrltz  Opcode = 50
	OpBrgez  Opcode = 51
	OpBrlez  Opcode = 52
	OpBrgtz  Opcode = 53
	OpBreq   Opcode = 54
	OpBrne   Opcode = 55
	OpBrap   Opcode = 56
	OpBrna   Opcode = 57
	OpSqrt   Opcode = 58
	OpRound  Opcode = 59
	OpTrunc  Opcode = 60
	OpCeil   Opcode = 61
	OpFloor  Opcode = 62
	OpMax    Opcode = 63
	OpMin    Opcode = 64
	OpAbs    Opcode = 65
	OpLog    Opcode = 66
	OpExp    Opcode = 67
	OpRand   Opcode = 68
	OpYield  Opcode = 69
	OpLabel  Opcode = 70
	OpPeek   Opcode = 71
	OpPush   Opcode = 72
	OpPop    Opcode = 73
	OpHcf    Opcode = 74
	OpSelect Opcode = 75
	OpBlt    Opcode = 76
	OpBgt    Opcode = 77
	OpBle    Opcode = 78
	OpBge    Opcode = 79
	OpBrlt   Opcode = 80
	OpBrgt   Opcode = 81
	OpBrle   Opcode = 82
	OpBrge   Opcode = 83
	OpBltal  Opcode = 84
	OpBgtal  Opcode = 85
	OpBleal  Opcode = 86
	OpBgeal  Opcode = 87
	OpBapal  Opcode = 88
	OpBnaal  Opcode = 89
	OpBeqz   Opcode = 90
	OpBnez   Opcode = 91
	OpBapz   Opcode = 92
	OpBnaz   Opcode = 93
	OpBreqz  Opcode = 94
	OpBrnez  Opcode = 95
	OpBrapz  Opcode = 96
	OpBrnaz  Opcode = 97
	OpBeqzal Opcode = 98
	OpBnezal Opcode = 99
	OpBapzal Opcode = 100
	OpBnazal Opcode = 101
	OpSltz   Opcode = 102
	OpSgtz   Opcode = 103
	OpSlez   Opcode = 104
	OpSgez   Opcode = 105
	OpSeqz   Opcode = 106
	OpSnez   Opcode = 107
	OpSapz   Opcode = 108
	OpSnaz   Opcode = 109
	OpDefine Opcode = 110
	OpSleep  Opcode = 111
	OpSin    Opcode = 112
	OpAsin   Opcode = 113
	OpTan    Opcode = 114
	OpAtan   Opcode = 115
	OpCos    Opcode = 116
	OpAcos   Opcode = 117
	OpAtan2  Opcode = 118
	OpBrnan  Opcode = 119
	OpBnan   Opcode = 120
	OpSnan   Opcode = 121
	OpSnanz  Opcode = 122
	OpLbs    Opcode = 123
	OpLbn    Opcode = 124
	OpSbn    Opcode = 125
	OpLbns   Opcode = 126
	OpSs     Opcode = 127
	OpSbs    Opcode = 128
	OpSrl    Opcode = 129
	OpSra    Opcode = 130
	OpSll    Opcode = 131
	OpSla    Opcode = 132
	OpNot    Opcode = 133
	OpLd     Opcode = 134
	OpSd     Opcode = 135
	OpPoke   Opcode = 136
	OpGetd   Opcode = 137
	OpPutd   Opcode = 138
	OpGet    Opcode = 139
	OpPut    Opcode = 140
	OpClr    Opcode = 141
	OpClrd   Opcode = 142
	OpRmap   Opcode = 143
	OpBdnvl  Opcode = 144
	OpBdnvs  Opcode = 145
	OpPow    Opcode = 146
	OpExt    Opcode = 147
	OpIns    Opcode = 148
	OpLerp   Opcode = 149
	OpSgn    Opcode = 150
	OpClamp  Opcode = 151
	OpRol    Opcode = 152
	OpRor    Opcode = 153
)

// Instructions holds every mnemonic the chip's assembler accepts, indexed by
// Opcode. Deprecated entries still assemble and run.
var Instructions = []Instruction{
	{Mnemonic: "l", Opcode: OpL, Example: "l r? device(d?|r?|id) logicType", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}}},
	{Mnemonic: "s", Opcode: OpS, Example: "s device(d?|r?|id) logicType r?", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead}}},
	{Mnemonic: "ls", Opcode: OpLs, Example: "ls r? device(d?|r?|id) slotIndex logicSlotType", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead}}},
	{Mnemonic: "lr", Opcode: OpLr, Example: "lr r? device(d?|r?|id) reagentMode int", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandReagentMode}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandInteger}, Direction: DirectionRead}}},
	{Mnemonic: "sb", Opcode: OpSb, Example: "sb deviceHash logicType r?", Operands: []Operand{{Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead}}},
	{Mnemonic: "lb", Opcode: OpLb, Example: "lb r? deviceHash logicType batchMode", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandBatchMode}, Direction: DirectionRead}}},
	{Mnemonic: "alias", Opcode: OpAlias, Example: "alias str r?|d?", Operands: []Operand{{Kinds: []OperandKind{OperandString}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandRegister, OperandDevice}, Direction: DirectionRead}}},
	{Mnemonic: "move", Opcode: OpMove, Example: "move r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "add", Opcode: OpAdd, Example: "add r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sub", Opcode: OpSub, Example: "sub r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sdse", Opcode: OpSdse, Example: "sdse r? device(d?|r?|id)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}}},
	{Mnemonic: "sdns", Opcode: OpSdns, Example: "sdns r? device(d?|r?|id)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}}},
	{Mnemonic: "slt", Opcode: OpSlt, Example: "slt r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sgt", Opcode: OpSgt, Example: "sgt r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sle", Opcode: OpSle, Example: "sle r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sge", Opcode: OpSge, Example: "sge r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "seq", Opcode: OpSeq, Example: "seq r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sne", Opcode: OpSne, Example: "sne r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sap", Opcode: OpSap, Example: "sap r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sna", Opcode: OpSna, Example: "sna r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "and", Opcode: OpAnd, Example: "and r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "or", Opcode: OpOr, Example: "or r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "xor", Opcode: OpXor, Example: "xor r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "nor", Opcode: OpNor, Example: "nor r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "mul", Opcode: OpMul, Example: "mul r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "div", Opcode: OpDiv, Example: "div r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "mod", Opcode: OpMod, Example: "mod r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "j", Opcode: OpJ, Example: "j int", Operands: []Operand{{Kinds: []OperandKind{OperandInteger}, Direction: DirectionRead}}},
	{Mnemonic: "bltz", Opcode: OpBltz, Example: "bltz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bgez", Opcode: OpBgez, Example: "bgez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "blez", Opcode: OpBlez, Example: "blez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bgtz", Opcode: OpBgtz, Example: "bgtz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bdse", Opcode: OpBdse, Example: "bdse device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bdns", Opcode: OpBdns, Example: "bdns device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "beq", Opcode: OpBeq, Example: "beq a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bne", Opcode: OpBne, Example: "bne a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bap", Opcode: OpBap, Example: "bap a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bna", Opcode: OpBna, Example: "bna a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "jal", Opcode: OpJal, Example: "jal int", Operands: []Operand{{Kinds: []OperandKind{OperandInteger}, Direction: DirectionRead}}},
	{Mnemonic: "brdse", Opcode: OpBrdse, Example: "brdse device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brdns", Opcode: OpBrdns, Example: "brdns device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bltzal", Opcode: OpBltzal, Example: "bltzal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bgezal", Opcode: OpBgezal, Example: "bgezal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "blezal", Opcode: OpBlezal, Example: "blezal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bgtzal", Opcode: OpBgtzal, Example: "bgtzal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "beqal", Opcode: OpBeqal, Example: "beqal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bneal", Opcode: OpBneal, Example: "bneal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "jr", Opcode: OpJr, Example: "jr int", Operands: []Operand{{Kinds: []OperandKind{OperandInteger}, Direction: DirectionRead}}},
	{Mnemonic: "bdseal", Opcode: OpBdseal, Example: "bdseal device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bdnsal", Opcode: OpBdnsal, Example: "bdnsal device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brltz", Opcode: OpBrltz, Example: "brltz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brgez", Opcode: OpBrgez, Example: "brgez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brlez", Opcode: OpBrlez, Example: "brlez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brgtz", Opcode: OpBrgtz, Example: "brgtz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "breq", Opcode: OpBreq, Example: "breq a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brne", Opcode: OpBrne, Example: "brne a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brap", Opcode: OpBrap, Example: "brap a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brna", Opcode: OpBrna, Example: "brna a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sqrt", Opcode: OpSqrt, Example: "sqrt r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "round", Opcode: OpRound, Example: "round r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "trunc", Opcode: OpTrunc, Example: "trunc r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "ceil", Opcode: OpCeil, Example: "ceil r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "floor", Opcode: OpFloor, Example: "floor r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "max", Opcode: OpMax, Example: "max r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "min", Opcode: OpMin, Example: "min r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "abs", Opcode: OpAbs, Example: "abs r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "log", Opcode: OpLog, Example: "log r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "exp", Opcode: OpExp, Example: "exp r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "rand", Opcode: OpRand, Example: "rand r?", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}}},
	{Mnemonic: "yield", Opcode: OpYield, Example: "yield", Operands: nil},
	{Mnemonic: "label", Opcode: OpLabel, Deprecated: true, Example: "label d? str", Operands: []Operand{{Kinds: []OperandKind{OperandDevice}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandString}, Direction: DirectionRead}}},
	{Mnemonic: "peek", Opcode: OpPeek, Example: "peek r?", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}}},
	{Mnemonic: "push", Opcode: OpPush, Example: "push a(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "pop", Opcode: OpPop, Example: "pop r?", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}}},
	{Mnemonic: "hcf", Opcode: OpHcf, Example: "hcf", Operands: nil},
	{Mnemonic: "select", Opcode: OpSelect, Example: "select r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "blt", Opcode: OpBlt, Example: "blt a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bgt", Opcode: OpBgt, Example: "bgt a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "ble", Opcode: OpBle, Example: "ble a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bge", Opcode: OpBge, Example: "bge a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brlt", Opcode: OpBrlt, Example: "brlt a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brgt", Opcode: OpBrgt, Example: "brgt a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brle", Opcode: OpBrle, Example: "brle a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brge", Opcode: OpBrge, Example: "brge a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bltal", Opcode: OpBltal, Example: "bltal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bgtal", Opcode: OpBgtal, Example: "bgtal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bleal", Opcode: OpBleal, Example: "bleal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bgeal", Opcode: OpBgeal, Example: "bgeal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bapal", Opcode: OpBapal, Example: "bapal a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bnaal", Opcode: OpBnaal, Example: "bnaal a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "beqz", Opcode: OpBeqz, Example: "beqz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bnez", Opcode: OpBnez, Example: "bnez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bapz", Opcode: OpBapz, Example: "bapz a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bnaz", Opcode: OpBnaz, Example: "bnaz a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "breqz", Opcode: OpBreqz, Example: "breqz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brnez", Opcode: OpBrnez, Example: "brnez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brapz", Opcode: OpBrapz, Example: "brapz a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brnaz", Opcode: OpBrnaz, Example: "brnaz a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "beqzal", Opcode: OpBeqzal, Example: "beqzal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bnezal", Opcode: OpBnezal, Example: "bnezal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bapzal", Opcode: OpBapzal, Example: "bapzal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bnazal", Opcode: OpBnazal, Example: "bnazal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sltz", Opcode: OpSltz, Example: "sltz r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sgtz", Opcode: OpSgtz, Example: "sgtz r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "slez", Opcode: OpSlez, Example: "slez r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sgez", Opcode: OpSgez, Example: "sgez r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "seqz", Opcode: OpSeqz, Example: "seqz r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "snez", Opcode: OpSnez, Example: "snez r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sapz", Opcode: OpSapz, Example: "sapz r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "snaz", Opcode: OpSnaz, Example: "snaz r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "define", Opcode: OpDefine, Example: "define str num", Operands: []Operand{{Kinds: []OperandKind{OperandString}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sleep", Opcode: OpSleep, Example: "sleep a(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sin", Opcode: OpSin, Example: "sin r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "asin", Opcode: OpAsin, Example: "asin r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "tan", Opcode: OpTan, Example: "tan r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "atan", Opcode: OpAtan, Example: "atan r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "cos", Opcode: OpCos, Example: "cos r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "acos", Opcode: OpAcos, Example: "acos r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "atan2", Opcode: OpAtan2, Example: "atan2 r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "brnan", Opcode: OpBrnan, Example: "brnan a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bnan", Opcode: OpBnan, Example: "bnan a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "snan", Opcode: OpSnan, Example: "snan r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "snanz", Opcode: OpSnanz, Example: "snanz r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "lbs", Opcode: OpLbs, Example: "lbs r? deviceHash slotIndex logicSlotType batchMode", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandBatchMode}, Direction: DirectionRead}}},
	{Mnemonic: "lbn", Opcode: OpLbn, Example: "lbn r? deviceHash nameHash logicType batchMode", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandNameHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandBatchMode}, Direction: DirectionRead}}},
	{Mnemonic: "sbn", Opcode: OpSbn, Example: "sbn deviceHash nameHash logicType r?", Operands: []Operand{{Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandNameHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead}}},
	{Mnemonic: "lbns", Opcode: OpLbns, Example: "lbns r? deviceHash nameHash slotIndex logicSlotType batchMode", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandNameHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandBatchMode}, Direction: DirectionRead}}},
	{Mnemonic: "ss", Opcode: OpSs, Example: "ss device(d?|r?|id) slotIndex logicSlotType r?", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead}}},
	{Mnemonic: "sbs", Opcode: OpSbs, Example: "sbs deviceHash slotIndex logicSlotType r?", Operands: []Operand{{Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead}}},
	{Mnemonic: "srl", Opcode: OpSrl, Example: "srl r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sra", Opcode: OpSra, Example: "sra r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sll", Opcode: OpSll, Example: "sll r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sla", Opcode: OpSla, Example: "sla r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "not", Opcode: OpNot, Example: "not r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "ld", Opcode: OpLd, Deprecated: true, Example: "ld r? id(r?|id) logicType", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "id", Kinds: []OperandKind{OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}}},
	{Mnemonic: "sd", Opcode: OpSd, Deprecated: true, Example: "sd id(r?|id) logicType r?", Operands: []Operand{{Name: "id", Kinds: []OperandKind{OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead}}},
	{Mnemonic: "poke", Opcode: OpPoke, Example: "poke address(r?|num) value(r?|num)", Operands: []Operand{{Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "value", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "getd", Opcode: OpGetd, Deprecated: true, Example: "getd r? id(r?|id) address(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "id", Kinds: []OperandKind{OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "putd", Opcode: OpPutd, Deprecated: true, Example: "putd id(r?|id) address(r?|num) value(r?|num)", Operands: []Operand{{Name: "id", Kinds: []OperandKind{OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "value", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "get", Opcode: OpGet, Example: "get r? device(d?|r?|id) address(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "put", Opcode: OpPut, Example: "put device(d?|r?|id) address(r?|num) value(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "value", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "clr", Opcode: OpClr, Example: "clr d?", Operands: []Operand{{Kinds: []OperandKind{OperandDevice}, Direction: DirectionRead}}},
	{Mnemonic: "clrd", Opcode: OpClrd, Example: "clrd id(r?|num)", Operands: []Operand{{Name: "id", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "rmap", Opcode: OpRmap, Example: "rmap r? d? reagentHash(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Kinds: []OperandKind{OperandDevice}, Direction: DirectionRead}, {Name: "reagentHash", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bdnvl", Opcode: OpBdnvl, Example: "bdnvl device(d?|r?|id) logicType a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "bdnvs", Opcode: OpBdnvs, Example: "bdnvs device(d?|r?|id) logicType a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "pow", Opcode: OpPow, Example: "pow r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "ext", Opcode: OpExt, Example: "ext r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "ins", Opcode: OpIns, Example: "ins r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionReadWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "lerp", Opcode: OpLerp, Example: "lerp r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "sgn", Opcode: OpSgn, Example: "sgn r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "clamp", Opcode: OpClamp, Example: "clamp r? a(r?|num) min(r?|num) max(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "min", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "max", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "rol", Opcode: OpRol, Example: "rol r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
	{Mnemonic: "ror", Opcode: OpRor, Example: "ror r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead}}},
}

// LogicTypes holds the device properties addressable by l, s, and the batch
// forms. Generated code emits Value rather than Name; they resolve alike.
var LogicTypes = []LogicTypeInfo{
	{Name: "None", Value: 0, Deprecated: true},
	{Name: "Power", Value: 1},
	{Name: "Open", Value: 2},
	{Name: "Mode", Value: 3},
	{Name: "Error", Value: 4},
	{Name: "Pressure", Value: 5},
	{Name: "Temperature", Value: 6},
	{Name: "PressureExternal", Value: 7},
	{Name: "PressureInternal", Value: 8},
	{Name: "Activate", Value: 9},
	{Name: "Lock", Value: 10},
	{Name: "Charge", Value: 11},
	{Name: "Setting", Value: 12},
	{Name: "Reagents", Value: 13},
	{Name: "RatioOxygen", Value: 14},
	{Name: "RatioCarbonDioxide", Value: 15},
	{Name: "RatioNitrogen", Value: 16},
	{Name: "RatioPollutant", Value: 17},
	{Name: "RatioMethane", Value: 18},
	{Name: "RatioWater", Value: 19},
	{Name: "Horizontal", Value: 20},
	{Name: "Vertical", Value: 21},
	{Name: "SolarAngle", Value: 22},
	{Name: "Maximum", Value: 23},
	{Name: "Ratio", Value: 24},
	{Name: "PowerPotential", Value: 25},
	{Name: "PowerActual", Value: 26},
	{Name: "Quantity", Value: 27},
	{Name: "On", Value: 28},
	{Name: "ImportQuantity", Value: 29, Deprecated: true},
	{Name: "ImportSlotOccupant", Value: 30, Deprecated: true},
	{Name: "ExportQuantity", Value: 31, Deprecated: true},
	{Name: "ExportSlotOccupant", Value: 32, Deprecated: true},
	{Name: "RequiredPower", Value: 33},
	{Name: "HorizontalRatio", Value: 34},
	{Name: "VerticalRatio", Value: 35},
	{Name: "PowerRequired", Value: 36},
	{Name: "Idle", Value: 37},
	{Name: "Color", Value: 38},
	{Name: "ElevatorSpeed", Value: 39},
	{Name: "ElevatorLevel", Value: 40},
	{Name: "RecipeHash", Value: 41},
	{Name: "ExportSlotHash", Value: 42, Deprecated: true},
	{Name: "ImportSlotHash", Value: 43, Deprecated: true},
	{Name: "PlantHealth1", Value: 44, Deprecated: true},
	{Name: "PlantHealth2", Value: 45, Deprecated: true},
	{Name: "PlantHealth3", Value: 46, Deprecated: true},
	{Name: "PlantHealth4", Value: 47, Deprecated: true},
	{Name: "PlantGrowth1", Value: 48, Deprecated: true},
	{Name: "PlantGrowth2", Value: 49, Deprecated: true},
	{Name: "PlantGrowth3", Value: 50, Deprecated: true},
	{Name: "PlantGrowth4", Value: 51, Deprecated: true},
	{Name: "PlantEfficiency1", Value: 52, Deprecated: true},
	{Name: "PlantEfficiency2", Value: 53, Deprecated: true},
	{Name: "PlantEfficiency3", Value: 54, Deprecated: true},
	{Name: "PlantEfficiency4", Value: 55, Deprecated: true},
	{Name: "PlantHash1", Value: 56, Deprecated: true},
	{Name: "PlantHash2", Value: 57, Deprecated: true},
	{Name: "PlantHash3", Value: 58, Deprecated: true},
	{Name: "PlantHash4", Value: 59, Deprecated: true},
	{Name: "RequestHash", Value: 60},
	{Name: "CompletionRatio", Value: 61},
	{Name: "ClearMemory", Value: 62},
	{Name: "ExportCount", Value: 63},
	{Name: "ImportCount", Value: 64},
	{Name: "PowerGeneration", Value: 65},
	{Name: "TotalMoles", Value: 66},
	{Name: "Volume", Value: 67},
	{Name: "Plant", Value: 68},
	{Name: "Harvest", Value: 69},
	{Name: "Output", Value: 70},
	{Name: "PressureSetting", Value: 71},
	{Name: "TemperatureSetting", Value: 72},
	{Name: "TemperatureExternal", Value: 73},
	{Name: "Filtration", Value: 74},
	{Name: "AirRelease", Value: 75},
	{Name: "PositionX", Value: 76},
	{Name: "PositionY", Value: 77},
	{Name: "PositionZ", Value: 78},
	{Name: "VelocityMagnitude", Value: 79},
	{Name: "VelocityRelativeX", Value: 80},
	{Name: "VelocityRelativeY", Value: 81},
	{Name: "VelocityRelativeZ", Value: 82},
	{Name: "RatioNitrousOxide", Value: 83},
	{Name: "PrefabHash", Value: 84},
	{Name: "ForceWrite", Value: 85},
	{Name: "SignalStrength", Value: 86},
	{Name: "SignalID", Value: 87},
	{Name: "TargetX", Value: 88},
	{Name: "TargetY", Value: 89},
	{Name: "TargetZ", Value: 90},
	{Name: "SettingInput", Value: 91},
	{Name: "SettingOutput", Value: 92},
	{Name: "CurrentResearchPodType", Value: 93},
	{Name: "ManualResearchRequiredPod", Value: 94},
	{Name: "MineablesInVicinity", Value: 95},
	{Name: "MineablesInQueue", Value: 96},
	{Name: "NextWeatherEventTime", Value: 97},
	{Name: "Combustion", Value: 98},
	{Name: "Fuel", Value: 99},
	{Name: "ReturnFuelCost", Value: 100},
	{Name: "CollectableGoods", Value: 101},
	{Name: "Time", Value: 102},
	{Name: "Bpm", Value: 103},
	{Name: "EnvironmentEfficiency", Value: 104},
	{Name: "WorkingGasEfficiency", Value: 105},
	{Name: "PressureInput", Value: 106},
	{Name: "TemperatureInput", Value: 107},
	{Name: "RatioOxygenInput", Value: 108},
	{Name: "RatioCarbonDioxideInput", Value: 109},
	{Name: "RatioNitrogenInput", Value: 110},
	{Name: "RatioPollutantInput", Value: 111},
	{Name: "RatioMethaneInput", Value: 112},
	{Name: "RatioWaterInput", Value: 113},
	{Name: "RatioNitrousOxideInput", Value: 114},
	{Name: "TotalMolesInput", Value: 115},
	{Name: "PressureInput2", Value: 116},
	{Name: "TemperatureInput2", Value: 117},
	{Name: "RatioOxygenInput2", Value: 118},
	{Name: "RatioCarbonDioxideInput2", Value: 119},
	{Name: "RatioNitrogenInput2", Value: 120},
	{Name: "RatioPollutantInput2", Value: 121},
	{Name: "RatioMethaneInput2", Value: 122},
	{Name: "RatioWaterInput2", Value: 123},
	{Name: "RatioNitrousOxideInput2", Value: 124},
	{Name: "TotalMolesInput2", Value: 125},
	{Name: "PressureOutput", Value: 126},
	{Name: "TemperatureOutput", Value: 127},
	{Name: "RatioOxygenOutput", Value: 128},
	{Name: "RatioCarbonDioxideOutput", Value: 129},
	{Name: "RatioNitrogenOutput", Value: 130},
	{Name: "RatioPollutantOutput", Value: 131},
	{Name: "RatioMethaneOutput", Value: 132},
	{Name: "RatioWaterOutput", Value: 133},
	{Name: "RatioNitrousOxideOutput", Value: 134},
	{Name: "TotalMolesOutput", Value: 135},
	{Name: "PressureOutput2", Value: 136},
	{Name: "TemperatureOutput2", Value: 137},
	{Name: "RatioOxygenOutput2", Value: 138},
	{Name: "RatioCarbonDioxideOutput2", Value: 139},
	{Name: "RatioNitrogenOutput2", Value: 140},
	{Name: "RatioPollutantOutput2", Value: 141},
	{Name: "RatioMethaneOutput2", Value: 142},
	{Name: "RatioWaterOutput2", Value: 143},
	{Name: "RatioNitrousOxideOutput2", Value: 144},
	{Name: "TotalMolesOutput2", Value: 145},
	{Name: "CombustionInput", Value: 146},
	{Name: "CombustionInput2", Value: 147},
	{Name: "CombustionOutput", Value: 148},
	{Name: "CombustionOutput2", Value: 149},
	{Name: "OperationalTemperatureEfficiency", Value: 150},
	{Name: "TemperatureDifferentialEfficiency", Value: 151},
	{Name: "PressureEfficiency", Value: 152},
	{Name: "CombustionLimiter", Value: 153},
	{Name: "Throttle", Value: 154},
	{Name: "Rpm", Value: 155},
	{Name: "Stress", Value: 156},
	{Name: "InterrogationProgress", Value: 157},
	{Name: "TargetPadIndex", Value: 158},
	{Name: "SizeX", Value: 160},
	{Name: "SizeY", Value: 161},
	{Name: "SizeZ", Value: 162},
	{Name: "MinimumWattsToContact", Value: 163},
	{Name: "WattsReachingContact", Value: 164},
	{Name: "Channel0", Value: 165},
	{Name: "Channel1", Value: 166},
	{Name: "Channel2", Value: 167},
	{Name: "Channel3", Value: 168},
	{Name: "Channel4", Value: 169},
	{Name: "Channel5", Value: 170},
	{Name: "Channel6", Value: 171},
	{Name: "Channel7", Value: 172},
	{Name: "LineNumber", Value: 173},
	{Name: "Flush", Value: 174},
	{Name: "SoundAlert", Value: 175},
	{Name: "SolarIrradiance", Value: 176},
	{Name: "RatioLiquidNitrogen", Value: 177},
	{Name: "RatioLiquidNitrogenInput", Value: 178},
	{Name: "RatioLiquidNitrogenInput2", Value: 179},
	{Name: "RatioLiquidNitrogenOutput", Value: 180},
	{Name: "RatioLiquidNitrogenOutput2", Value: 181},
	{Name: "VolumeOfLiquid", Value: 182},
	{Name: "RatioLiquidOxygen", Value: 183},
	{Name: "RatioLiquidOxygenInput", Value: 184},
	{Name: "RatioLiquidOxygenInput2", Value: 185},
	{Name: "RatioLiquidOxygenOutput", Value: 186},
	{Name: "RatioLiquidOxygenOutput2", Value: 187},
	{Name: "RatioLiquidMethane", Value: 188},
	{Name: "RatioLiquidMethaneInput", Value: 189},
	{Name: "RatioLiquidMethaneInput2", Value: 190},
	{Name: "RatioLiquidMethaneOutput", Value: 191},
	{Name: "RatioLiquidMethaneOutput2", Value: 192},
	{Name: "RatioSteam", Value: 193},
	{Name: "RatioSteamInput", Value: 194},
	{Name: "RatioSteamInput2", Value: 195},
	{Name: "RatioSteamOutput", Value: 196},
	{Name: "RatioSteamOutput2", Value: 197},
	{Name: "ContactTypeId", Value: 198},
	{Name: "RatioLiquidCarbonDioxide", Value: 199},
	{Name: "RatioLiquidCarbonDioxideInput", Value: 200},
	{Name: "RatioLiquidCarbonDioxideInput2", Value: 201},
	{Name: "RatioLiquidCarbonDioxideOutput", Value: 202},
	{Name: "RatioLiquidCarbonDioxideOutput2", Value: 203},
	{Name: "RatioLiquidPollutant", Value: 204},
	{Name: "RatioLiquidPollutantInput", Value: 205},
	{Name: "RatioLiquidPollutantInput2", Value: 206},
	{Name: "RatioLiquidPollutantOutput", Value: 207},
	{Name: "RatioLiquidPollutantOutput2", Value: 208},
	{Name: "RatioLiquidNitrousOxide", Value: 209},
	{Name: "RatioLiquidNitrousOxideInput", Value: 210},
	{Name: "RatioLiquidNitrousOxideInput2", Value: 211},
	{Name: "RatioLiquidNitrousOxideOutput", Value: 212},
	{Name: "RatioLiquidNitrousOxideOutput2", Value: 213},
	{Name: "Progress", Value: 214},
	{Name: "DestinationCode", Value: 215},
	{Name: "Acceleration", Value: 216},
	{Name: "ReferenceId", Value: 217},
	{Name: "AutoShutOff", Value: 218},
	{Name: "Mass", Value: 219},
	{Name: "DryMass", Value: 220},
	{Name: "Thrust", Value: 221},
	{Name: "Weight", Value: 222},
	{Name: "ThrustToWeight", Value: 223},
	{Name: "TimeToDestination", Value: 224},
	{Name: "BurnTimeRemaining", Value: 225},
	{Name: "AutoLand", Value: 226},
	{Name: "ForwardX", Value: 227},
	{Name: "ForwardY", Value: 228},
	{Name: "ForwardZ", Value: 229},
	{Name: "Orientation", Value: 230},
	{Name: "VelocityX", Value: 231},
	{Name: "VelocityY", Value: 232},
	{Name: "VelocityZ", Value: 233},
	{Name: "PassedMoles", Value: 234},
	{Name: "ExhaustVelocity", Value: 235},
	{Name: "FlightControlRule", Value: 236},
	{Name: "ReEntryAltitude", Value: 237},
	{Name: "Apex", Value: 238},
	{Name: "EntityState", Value: 239},
	{Name: "DrillCondition", Value: 240},
	{Name: "Index", Value: 241},
	{Name: "CelestialHash", Value: 242},
	{Name: "AlignmentError", Value: 243},
	{Name: "DistanceAu", Value: 244},
	{Name: "OrbitPeriod", Value: 245},
	{Name: "Inclination", Value: 246},
	{Name: "Eccentricity", Value: 247},
	{Name: "SemiMajorAxis", Value: 248},
	{Name: "DistanceKm", Value: 249},
	{Name: "CelestialParentHash", Value: 250},
	{Name: "TrueAnomaly", Value: 251},
	{Name: "RatioHydrogen", Value: 252},
	{Name: "RatioLiquidHydrogen", Value: 253},
	{Name: "RatioPollutedWater", Value: 254},
	{Name: "Discover", Value: 255},
	{Name: "Chart", Value: 256},
	{Name: "Survey", Value: 257},
	{Name: "NavPoints", Value: 258},
	{Name: "ChartedNavPoints", Value: 259},
	{Name: "Sites", Value: 260},
	{Name: "CurrentCode", Value: 261},
	{Name: "Density", Value: 262},
	{Name: "Richness", Value: 263},
	{Name: "Size", Value: 264},
	{Name: "TotalQuantity", Value: 265},
	{Name: "MinedQuantity", Value: 266},
	{Name: "BestContactFilter", Value: 267},
	{Name: "NameHash", Value: 268},
	{Name: "Altitude", Value: 269},
	{Name: "TargetSlotIndex", Value: 270},
	{Name: "TargetPrefabHash", Value: 271},
	{Name: "Extended", Value: 272},
	{Name: "NetworkFault", Value: 273},
	{Name: "ProportionalGain", Value: 274},
	{Name: "IntegralGain", Value: 275},
	{Name: "DerivativeGain", Value: 276},
	{Name: "Minimum", Value: 277},
	{Name: "Setpoint", Value: 278},
	{Name: "Reset", Value: 279},
	{Name: "StackSize", Value: 280},
	{Name: "NextWeatherHash", Value: 281},
	{Name: "ContactSlotIndex", Value: 282},
	{Name: "RatioHydrazine", Value: 283},
	{Name: "RatioLiquidHydrazine", Value: 284},
	{Name: "RatioLiquidAlcohol", Value: 285},
	{Name: "RatioHelium", Value: 286},
	{Name: "RatioLiquidSodiumChloride", Value: 287},
	{Name: "RatioSilanol", Value: 288},
	{Name: "RatioLiquidSilanol", Value: 289},
	{Name: "RatioHydrochloricAcid", Value: 290},
	{Name: "RatioLiquidHydrochloricAcid", Value: 291},
	{Name: "RatioOzone", Value: 292},
	{Name: "RatioLiquidOzone", Value: 293},
	{Name: "RatioHydrogenInput", Value: 294},
	{Name: "RatioHydrogenInput2", Value: 295},
	{Name: "RatioHydrogenOutput", Value: 296},
	{Name: "RatioHydrogenOutput2", Value: 297},
	{Name: "RatioLiquidHydrogenInput", Value: 298},
	{Name: "RatioLiquidHydrogenInput2", Value: 299},
	{Name: "RatioLiquidHydrogenOutput", Value: 300},
	{Name: "RatioLiquidHydrogenOutput2", Value: 301},
	{Name: "RatioPollutedWaterInput", Value: 302},
	{Name: "RatioPollutedWaterInput2", Value: 303},
	{Name: "RatioPollutedWaterOutput", Value: 304},
	{Name: "RatioPollutedWaterOutput2", Value: 305},
	{Name: "RatioHydrazineInput", Value: 306},
	{Name: "RatioHydrazineInput2", Value: 307},
	{Name: "RatioHydrazineOutput", Value: 308},
	{Name: "RatioHydrazineOutput2", Value: 309},
	{Name: "RatioLiquidHydrazineInput", Value: 310},
	{Name: "RatioLiquidHydrazineInput2", Value: 311},
	{Name: "RatioLiquidHydrazineOutput", Value: 312},
	{Name: "RatioLiquidHydrazineOutput2", Value: 313},
	{Name: "RatioLiquidAlcoholInput", Value: 314},
	{Name: "RatioLiquidAlcoholInput2", Value: 315},
	{Name: "RatioLiquidAlcoholOutput", Value: 316},
	{Name: "RatioLiquidAlcoholOutput2", Value: 317},
	{Name: "RatioHeliumInput", Value: 318},
	{Name: "RatioHeliumInput2", Value: 319},
	{Name: "RatioHeliumOutput", Value: 320},
	{Name: "RatioHeliumOutput2", Value: 321},
	{Name: "RatioLiquidSodiumChlorideInput", Value: 322},
	{Name: "RatioLiquidSodiumChlorideInput2", Value: 323},
	{Name: "RatioLiquidSodiumChlorideOutput", Value: 324},
	{Name: "RatioLiquidSodiumChlorideOutput2", Value: 325},
	{Name: "RatioSilanolInput", Value: 326},
	{Name: "RatioSilanolInput2", Value: 327},
	{Name: "RatioSilanolOutput", Value: 328},
	{Name: "RatioSilanolOutput2", Value: 329},
	{Name: "RatioLiquidSilanolInput", Value: 330},
	{Name: "RatioLiquidSilanolInput2", Value: 331},
	{Name: "RatioLiquidSilanolOutput", Value: 332},
	{Name: "RatioLiquidSilanolOutput2", Value: 333},
	{Name: "RatioHydrochloricAcidInput", Value: 334},
	{Name: "RatioHydrochloricAcidInput2", Value: 335},
	{Name: "RatioHydrochloricAcidOutput", Value: 336},
	{Name: "RatioHydrochloricAcidOutput2", Value: 337},
	{Name: "RatioLiquidHydrochloricAcidInput", Value: 338},
	{Name: "RatioLiquidHydrochloricAcidInput2", Value: 339},
	{Name: "RatioLiquidHydrochloricAcidOutput", Value: 340},
	{Name: "RatioLiquidHydrochloricAcidOutput2", Value: 341},
	{Name: "RatioOzoneInput", Value: 342},
	{Name: "RatioOzoneInput2", Value: 343},
	{Name: "RatioOzoneOutput", Value: 344},
	{Name: "RatioOzoneOutput2", Value: 345},
	{Name: "RatioLiquidOzoneInput", Value: 346},
	{Name: "RatioLiquidOzoneInput2", Value: 347},
	{Name: "RatioLiquidOzoneOutput", Value: 348},
	{Name: "RatioLiquidOzoneOutput2", Value: 349},
	{Name: "HealthDamage", Value: 350},
	{Name: "StunDamage", Value: 351},
	{Name: "CurrentNodeType", Value: 352},
	{Name: "TargetNodeType", Value: 353},
	{Name: "EnergyConvected", Value: 354},
	{Name: "EnergyRadiated", Value: 355},
	{Name: "Dispense", Value: 356},
	{Name: "DispenseSlot", Value: 357},
	{Name: "Gravity", Value: 358},
}

// LogicSlotTypes holds the slot properties addressable by ls, ss, and the
// batch slot forms.
var LogicSlotTypes = []LogicSlotTypeInfo{
	{Name: "None", Value: 0},
	{Name: "Occupied", Value: 1},
	{Name: "OccupantHash", Value: 2},
	{Name: "Quantity", Value: 3},
	{Name: "Damage", Value: 4},
	{Name: "Efficiency", Value: 5},
	{Name: "Health", Value: 6},
	{Name: "Growth", Value: 7},
	{Name: "Pressure", Value: 8},
	{Name: "Temperature", Value: 9},
	{Name: "Charge", Value: 10},
	{Name: "ChargeRatio", Value: 11},
	{Name: "Class", Value: 12},
	{Name: "PressureWaste", Value: 13},
	{Name: "PressureAir", Value: 14},
	{Name: "MaxQuantity", Value: 15},
	{Name: "Mature", Value: 16},
	{Name: "PrefabHash", Value: 17},
	{Name: "Seeding", Value: 18},
	{Name: "LineNumber", Value: 19},
	{Name: "Volume", Value: 20},
	{Name: "Open", Value: 21},
	{Name: "On", Value: 22},
	{Name: "Lock", Value: 23},
	{Name: "SortingClass", Value: 24},
	{Name: "FilterType", Value: 25},
	{Name: "ReferenceId", Value: 26},
	{Name: "HarvestedHash", Value: 27},
	{Name: "Mode", Value: 28},
	{Name: "MaturityRatio", Value: 29},
	{Name: "SeedingRatio", Value: 30},
	{Name: "FreeSlots", Value: 31},
	{Name: "TotalSlots", Value: 32},
}

// BatchModes holds the aggregation modes accepted by the batch load forms.
var BatchModes = []BatchModeInfo{
	{Name: "Average", Value: 0},
	{Name: "Sum", Value: 1},
	{Name: "Minimum", Value: 2},
	{Name: "Maximum", Value: 3},
	{Name: "Count", Value: 4},
}

// ReagentModes holds the reagent views accepted by lr.
var ReagentModes = []ReagentModeInfo{
	{Name: "Contents", Value: 0},
	{Name: "Required", Value: 1},
	{Name: "Recipe", Value: 2},
	{Name: "TotalContents", Value: 3},
}

// Constants holds the numeric literals the chip's assembler accepts wherever a
// number is accepted, in game declaration order.
var Constants = []Constant{
	{Name: "nan", Value: math.Float64frombits(0xfff8000000000000)},
	{Name: "pinf", Value: math.Inf(1)},
	{Name: "ninf", Value: math.Inf(-1)},
	{Name: "pi", Value: 3.141592653589793},
	{Name: "tau", Value: 6.283185307179586},
	{Name: "deg2rad", Value: 0.01745329238474369},
	{Name: "rad2deg", Value: 57.295780181884766},
	{Name: "epsilon", Value: 5e-324},
	{Name: "rgas", Value: 8.31446261815324},
}
