package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// generatedHeader marks the output as machine written. The exact wording is
// what golangci-lint and other tools match on to exclude the file.
const generatedHeader = "// Code generated by cmd/isagen. DO NOT EDIT."

// outputs names the files generate writes. All five are checked in, and
// check:codegen fails on any that drifted from the ISA JSON.
type outputs struct {
	// tables is the Go the compiler reads the machine through.
	tables string
	// prelude and flags are the C editor's view of the same tables: a header
	// declaring what a MicroC program may name, and the argument file that
	// includes it.
	prelude string
	flags   string
	// fixtureFlags configures an editor opening one of the MicroC programs the
	// test corpus holds. It is the same argument file as flags, naming the same
	// header by a path that reaches it from there, so the corpus needs no copy
	// of the header and has nothing of its own to drift.
	fixtureFlags string
	// basicEnums is the interpreter's view of the game enums an operand may
	// name that the machine tables do not otherwise carry.
	basicEnums string
}

// generate reads the canonical ISA JSON and writes the tables, the C prelude,
// its flags file, and the interpreter's enum tables. It touches nothing else,
// so it runs on any machine without the game.
func generate(inPath string, out outputs) error {
	data, err := os.ReadFile(inPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", inPath, err)
	}
	var isa ISA
	if err := decodeISA(data, &isa); err != nil {
		return fmt.Errorf("%s: %w", inPath, err)
	}

	tables, err := renderTables(&isa)
	if err != nil {
		return fmt.Errorf("render tables from %s: %w", inPath, err)
	}
	prelude, err := renderPrelude(&isa)
	if err != nil {
		return fmt.Errorf("render prelude from %s: %w", inPath, err)
	}
	basicEnums, err := renderBasicEnums(&isa)
	if err != nil {
		return fmt.Errorf("render enum tables from %s: %w", inPath, err)
	}
	flags, err := renderFlagsFor(out.flags, out.prelude)
	if err != nil {
		return err
	}
	fixtureFlags, err := renderFlagsFor(out.fixtureFlags, out.prelude)
	if err != nil {
		return err
	}

	for _, file := range []struct {
		path string
		data []byte
	}{
		{out.tables, tables},
		{out.prelude, prelude},
		{out.flags, flags},
		{out.fixtureFlags, fixtureFlags},
		{out.basicEnums, basicEnums},
	} {
		if err := writeGenerated(file.path, file.data); err != nil {
			return err
		}
	}
	return nil
}

func writeGenerated(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// decodeISA reads the canonical JSON. Unknown fields are rejected so a table
// written by a newer isagen is reported rather than silently truncated.
func decodeISA(data []byte, isa *ISA) error {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(isa); err != nil {
		return fmt.Errorf("decode ISA: %w", err)
	}
	return nil
}

// renderTables produces the gofmt-formatted contents of tables.gen.go.
func renderTables(isa *ISA) ([]byte, error) {
	if len(isa.Instructions) == 0 {
		return nil, fmt.Errorf("instruction table is empty")
	}
	for i, instruction := range isa.Instructions {
		if instruction.Opcode != i {
			return nil, fmt.Errorf("instruction %s has opcode %d at index %d: opcodes must be dense and ordered so Instructions can be indexed by Opcode",
				instruction.Mnemonic, instruction.Opcode, i)
		}
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\npackage ic10\n\n")
	if needsMath(isa.Constants) {
		b.WriteString("import \"math\"\n\n")
	}

	fmt.Fprintf(&b, "// ManifestID is the Steam depot manifest these tables were extracted from.\n// It names the assembly's exact bytes, so a re-extraction that reaches it\n// lands on this table again.\nconst ManifestID = %q\n\n", isa.Manifest)
	fmt.Fprintf(&b, "// GameVersion is the assembly file version these tables were extracted from.\nconst GameVersion = %q\n\n", isa.Version)

	b.WriteString("// Opcodes in game enum order. The numeric value is the ScriptCommand\n// ordinal and is also the index into Instructions.\nconst (\n")
	for _, instruction := range isa.Instructions {
		fmt.Fprintf(&b, "\t%s Opcode = %d\n", opcodeConst(instruction.Mnemonic), instruction.Opcode)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Instructions holds every mnemonic the chip's assembler accepts, indexed by\n// Opcode. Deprecated entries still assemble and run.\nvar Instructions = []Instruction{\n")
	for _, instruction := range isa.Instructions {
		operands, err := renderOperands(instruction)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\t{Mnemonic: %q, Opcode: %s, ", instruction.Mnemonic, opcodeConst(instruction.Mnemonic))
		if instruction.Deprecated {
			b.WriteString("Deprecated: true, ")
		}
		fmt.Fprintf(&b, "Example: %q, Operands: %s},\n", instruction.Example, operands)
	}
	b.WriteString("}\n\n")

	renderEnum(&b, "LogicTypes", "LogicTypeInfo",
		"// LogicTypes holds the device properties addressable by l, s, and the batch\n// forms. Generated code emits Value rather than Name; they resolve alike.",
		isa.LogicTypes)
	renderEnum(&b, "LogicSlotTypes", "LogicSlotTypeInfo",
		"// LogicSlotTypes holds the slot properties addressable by ls, ss, and the\n// batch slot forms.",
		isa.SlotTypes)
	renderEnum(&b, "BatchModes", "BatchModeInfo",
		"// BatchModes holds the aggregation modes accepted by the batch load forms.",
		isa.BatchModes)
	renderEnum(&b, "ReagentModes", "ReagentModeInfo",
		"// ReagentModes holds the reagent views accepted by lr.",
		isa.ReagentModes)

	b.WriteString("// Constants holds the numeric literals the chip's assembler accepts wherever a\n// number is accepted, in game declaration order.\nvar Constants = []Constant{\n")
	for _, constant := range isa.Constants {
		value, err := constant.Float()
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\t{Name: %q, Value: %s},\n", constant.Name, goFloat(value))
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}

// basicEnumsDoc heads the interpreter's enum tables. It carries what the
// literal below cannot: why one entry has no name, and that the order the
// entries appear in is the order the game resolves them in.
const basicEnumsDoc = `// basicEnumMembers holds the member tables of the BasicEnum entries in
// ProgrammableChip.InternalEnums whose members the machine tables in
// internal/ic10 do not already carry, in game declaration order. That order
// decides which table wins when two of them share a member name, because the
// first match stops the search.
//
// The entry with an empty name is the one the game registers without a type
// prefix, so its members resolve as bare words in any value position; every
// other entry needs a ` + "`Type.Member`" + ` spelling. Each entry is commented with
// the C# enum its members were read from.`

// renderBasicEnums produces the gofmt-formatted contents of the interpreter's
// enum tables.
func renderBasicEnums(isa *ISA) ([]byte, error) {
	if len(isa.BasicEnums) == 0 {
		return nil, errors.New("basic enum table is empty")
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\npackage vm\n\n")
	b.WriteString(basicEnumsDoc)
	b.WriteString("\nvar basicEnumMembers = []struct {\n\tname    string\n\tmembers map[string]int\n}{\n")
	for _, enum := range isa.BasicEnums {
		if len(enum.Members) == 0 {
			return nil, fmt.Errorf("basic enum %q has no members", enum.Prefix)
		}
		fmt.Fprintf(&b, "\t// %s\n\t{name: %q, members: map[string]int{\n", enum.Type, enum.Prefix)
		for _, member := range enum.Members {
			fmt.Fprintf(&b, "\t\t%q: %d,\n", member.Name, member.Value)
		}
		b.WriteString("\t}},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}

// renderEnum writes one operand enum table. The value is always emitted, since
// it is the identity generated code refers to.
func renderEnum(b *strings.Builder, sliceName, infoType, doc string, members []EnumMember) {
	b.WriteString(doc)
	fmt.Fprintf(b, "\nvar %s = []%s{\n", sliceName, infoType)
	for _, member := range members {
		fmt.Fprintf(b, "\t{Name: %q, Value: %d", member.Name, member.Value)
		if member.Deprecated {
			b.WriteString(", Deprecated: true")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
}

// renderOperands writes an instruction's operand list as a Go composite
// literal, or the nil literal for the operandless forms.
func renderOperands(instruction Instruction) (string, error) {
	if len(instruction.Operands) == 0 {
		return "nil", nil
	}
	var b strings.Builder
	b.WriteString("[]Operand{")
	for i, operand := range instruction.Operands {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteByte('{')
		if operand.Name != "" {
			fmt.Fprintf(&b, "Name: %q, ", operand.Name)
		}
		if len(operand.Kinds) == 0 {
			return "", fmt.Errorf("instruction %s operand %d has no kinds", instruction.Mnemonic, i)
		}
		b.WriteString("Kinds: []OperandKind{")
		for j, kind := range operand.Kinds {
			name, ok := goOperandKinds[kind]
			if !ok {
				return "", fmt.Errorf("instruction %s operand %d: unknown kind %q", instruction.Mnemonic, i, kind)
			}
			if j > 0 {
				b.WriteString(", ")
			}
			b.WriteString(name)
		}
		b.WriteString("}}")
	}
	b.WriteByte('}')
	return b.String(), nil
}

// needsMath reports whether any constant must be written as a math package
// call because Go has no literal for it.
func needsMath(constants []Constant) bool {
	for _, c := range constants {
		v, err := c.Float()
		if err != nil {
			continue
		}
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return true
		}
	}
	return false
}

// goFloat renders v as a Go expression that evaluates to exactly v.
//
// A NaN is written as its bit pattern rather than as math.NaN, whose payload is
// Go's and not the game's.
func goFloat(v float64) string {
	switch {
	case math.IsNaN(v):
		return fmt.Sprintf("math.Float64frombits(%#x)", math.Float64bits(v))
	case math.IsInf(v, 1):
		return "math.Inf(1)"
	case math.IsInf(v, -1):
		return "math.Inf(-1)"
	default:
		return strconv.FormatFloat(v, 'g', -1, 64)
	}
}

// opcodeConst is the exported Go name for a mnemonic's opcode constant.
func opcodeConst(mnemonic string) string {
	return "Op" + strings.ToUpper(mnemonic[:1]) + mnemonic[1:]
}
