package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// generatedHeader marks the output as machine written. The exact wording is
// what golangci-lint and other tools match on to exclude the file.
const generatedHeader = "// Code generated by cmd/isagen. DO NOT EDIT."

// outputs names the files generate writes. All six are checked in, and
// check:codegen fails on any that drifted from the JSON it was rendered from.
type outputs struct {
	// tables is the Go the compiler reads the machine through.
	tables string
	// devices is the Go view of the game things a program names by hash, which
	// the instruction set describes no part of.
	devices string
	// prelude and flags are the C editor's view of the same tables: a header
	// declaring what a MicroC program may name, and the argument file that
	// includes it.
	prelude string
	flags   string
	// fixtureFlags configures an editor opening one of the MicroC programs the
	// test corpus holds. It is the same argument file as flags, naming the same
	// header by a path that reaches it from there, so the corpus needs no copy
	// of the header and has nothing of its own to drift.
	fixtureFlags string
	// basicEnums is the interpreter's view of the game enums an operand may
	// name that the machine tables do not otherwise carry.
	basicEnums string
}

// generate reads the canonical ISA and device JSON and writes the tables, the
// C prelude, its flags file, and the interpreter's enum tables. It touches
// nothing else, so it runs on any machine without the game.
//
// The two inputs are held to one game build and to the same shape extraction
// holds them to before anything is rendered, which makes every path that
// regenerates the tables -- including check:codegen -- an enforcement point for
// both. Nothing writes these files but extraction, so a JSON that fails here
// was hand-edited or was written by another build, and rendering it would put
// that into the compiler's own tables.
func generate(inPath, devicesPath string, out outputs) error {
	isa, err := readJSON[ISA](inPath)
	if err != nil {
		return err
	}
	extracted, err := readJSON[Devices](devicesPath)
	if err != nil {
		return err
	}
	if err := checkSameBuild(extracted, isa); err != nil {
		return err
	}
	if err := validate(isa); err != nil {
		return err
	}
	if err := validateDevices(extracted, isa); err != nil {
		return err
	}

	tables, err := renderTables(isa)
	if err != nil {
		return fmt.Errorf("render tables from %s: %w", inPath, err)
	}
	deviceTables, err := renderDevices(extracted, isa)
	if err != nil {
		return fmt.Errorf("render device tables from %s: %w", devicesPath, err)
	}
	prelude, err := renderPrelude(isa)
	if err != nil {
		return fmt.Errorf("render prelude from %s: %w", inPath, err)
	}
	basicEnums, err := renderBasicEnums(isa)
	if err != nil {
		return fmt.Errorf("render enum tables from %s: %w", inPath, err)
	}
	flags, err := renderFlagsFor(out.flags, out.prelude)
	if err != nil {
		return err
	}
	fixtureFlags, err := renderFlagsFor(out.fixtureFlags, out.prelude)
	if err != nil {
		return err
	}

	for _, file := range []struct {
		path string
		data []byte
	}{
		{out.tables, tables},
		{out.devices, deviceTables},
		{out.prelude, prelude},
		{out.flags, flags},
		{out.fixtureFlags, fixtureFlags},
		{out.basicEnums, basicEnums},
	} {
		if err := writeGenerated(file.path, file.data); err != nil {
			return err
		}
	}
	return nil
}

func writeGenerated(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// readJSON reads one of the canonical tables. Unknown fields are rejected so a
// table written by a newer isagen is reported rather than silently truncated.
func readJSON[T ISA | Devices | assetPrefabs](path string) (*T, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var table T
	if err := dec.Decode(&table); err != nil {
		return nil, fmt.Errorf("%s: decode: %w", path, err)
	}
	return &table, nil
}

// renderTables produces the gofmt-formatted contents of tables.gen.go.
func renderTables(isa *ISA) ([]byte, error) {
	if len(isa.Instructions) == 0 {
		return nil, fmt.Errorf("instruction table is empty")
	}
	for i, instruction := range isa.Instructions {
		if instruction.Opcode != i {
			return nil, fmt.Errorf("instruction %s has opcode %d at index %d: opcodes must be dense and ordered so Instructions can be indexed by Opcode",
				instruction.Mnemonic, instruction.Opcode, i)
		}
	}

	// The constants are resolved ahead of the file because whether the file
	// imports math is a property of their values.
	values := make([]float64, len(isa.Constants))
	for i, constant := range isa.Constants {
		value, err := constant.Float()
		if err != nil {
			return nil, err
		}
		values[i] = value
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\npackage ic10\n\n")
	if needsMath(values) {
		b.WriteString("import \"math\"\n\n")
	}

	fmt.Fprintf(&b, "// ManifestID is the Steam depot manifest these tables were extracted from.\n// It names the assembly's exact bytes, so a re-extraction that reaches it\n// lands on this table again.\nconst ManifestID = %q\n\n", isa.Manifest)
	fmt.Fprintf(&b, "// GameVersion is the assembly file version these tables were extracted from.\nconst GameVersion = %q\n\n", isa.Version)

	b.WriteString("// Opcodes in game enum order. The numeric value is the ScriptCommand\n// ordinal and is also the index into Instructions.\nconst (\n")
	for _, instruction := range isa.Instructions {
		fmt.Fprintf(&b, "\t%s Opcode = %d\n", opcodeConst(instruction.Mnemonic), instruction.Opcode)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Instructions holds every mnemonic the chip's assembler accepts, indexed by\n// Opcode. Deprecated entries still assemble and run.\nvar Instructions = []Instruction{\n")
	for _, instruction := range isa.Instructions {
		operands, err := renderOperands(instruction)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\t{Mnemonic: %q, Opcode: %s, ", instruction.Mnemonic, opcodeConst(instruction.Mnemonic))
		if instruction.Deprecated {
			b.WriteString("Deprecated: true, ")
		}
		fmt.Fprintf(&b, "Example: %q, Operands: %s},\n", instruction.Example, operands)
	}
	b.WriteString("}\n\n")

	renderEnum(&b, "LogicTypes", "LogicTypeInfo",
		"// LogicTypes holds the device properties addressable by l, s, and the batch\n// forms. Generated code emits Value rather than Name; they resolve alike.",
		isa.LogicTypes)
	renderEnum(&b, "LogicSlotTypes", "LogicSlotTypeInfo",
		"// LogicSlotTypes holds the slot properties addressable by ls, ss, and the\n// batch slot forms.",
		isa.SlotTypes)
	renderEnum(&b, "BatchModes", "BatchModeInfo",
		"// BatchModes holds the aggregation modes accepted by the batch load forms.",
		isa.BatchModes)
	renderEnum(&b, "ReagentModes", "ReagentModeInfo",
		"// ReagentModes holds the reagent views accepted by lr.",
		isa.ReagentModes)

	b.WriteString("// Constants holds the numeric literals the chip's assembler accepts wherever a\n// number is accepted, in game declaration order.\nvar Constants = []Constant{\n")
	for i, constant := range isa.Constants {
		fmt.Fprintf(&b, "\t{Name: %q, Value: %s},\n", constant.Name, goFloat(values[i]))
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}

// prefabsDoc heads the prefab table. It carries what the literal below cannot:
// what state the surfaces describe, and what an undecided entry obliges a
// caller to do.
const prefabsDoc = `// Prefabs holds every thing the game ships, in the order its own prefab roster
// declares them, together with what a chip can reach on each.
//
// Hash is what a batch instruction operand carries, and is the whole reason
// the things with no logic surface at all -- the kits, the ores, the tools --
// are listed: a hash naming none of these names nothing in this build.
//
// The surfaces describe a completed device. The game refuses every property of
// a structure still under construction, so a table stating that would say no to
// everything.
//
// An accessUnknown entry is a property the game decides from live state.
// Nothing may read it as a denial; see [PrefabInfo.RefusesRead], which with its
// three siblings is the whole of what the surfaces answer outside this
// package.`

// prefabAccessDoc explains the one shorthand the table uses. A table this size
// is unreadable with every field named.
const prefabAccessDoc = `// The logicAccess and slotAccess entries are written positionally: the
// property first, then the directions allowed.`

// renderDevices produces the gofmt-formatted contents of devices.gen.go.
//
// The reagent table the device JSON carries is not rendered. It earns its place
// in the JSON as an extraction check -- validateDevices holds it to the game's
// two declarations of the same list and to its own hashes -- but a chip names a
// reagent by hash alone, so there is no name for the compiler to resolve and
// nothing to answer from a rendered table.
func renderDevices(devices *Devices, isa *ISA) ([]byte, error) {
	if len(devices.Prefabs) == 0 {
		return nil, errors.New("prefab table is empty")
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\npackage ic10\n\n")
	b.WriteString(prefabsDoc)
	b.WriteString("\n//\n")
	b.WriteString(prefabAccessDoc)
	b.WriteString("\nvar Prefabs = []PrefabInfo{\n")
	logicTypes := enumValues(isa.LogicTypes)
	slotTypes := enumValues(isa.SlotTypes)
	for _, prefab := range devices.Prefabs {
		if err := renderPrefab(&b, prefab, logicTypes, slotTypes); err != nil {
			return nil, err
		}
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}

func renderPrefab(b *strings.Builder, prefab Prefab, logicTypes, slotTypes map[string]int64) error {
	if prefab.Name == "" {
		return errors.New("prefab table holds an unnamed entry")
	}
	fmt.Fprintf(b, "\t{Name: %q, Hash: %d", prefab.Name, prefab.Hash)
	if prefab.Title != "" {
		fmt.Fprintf(b, ", Title: %q", prefab.Title)
	}
	if prefab.CircuitHolder {
		b.WriteString(", CircuitHolder: true")
	}
	if prefab.CircuitHolderUnknown {
		b.WriteString(", CircuitHolderUnknown: true")
	}
	if prefab.ModesUnknown {
		b.WriteString(", ModesUnknown: true")
	}
	if len(prefab.Modes) > 0 {
		b.WriteString(",\n\t\tModes: []string{")
		for i, mode := range prefab.Modes {
			if mode.Value != i {
				return fmt.Errorf("prefab %s: mode %d is listed at position %d, and the generated table indexes modes by position",
					prefab.Name, mode.Value, i)
			}
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", mode.Name)
		}
		b.WriteString("}")
	}
	if len(prefab.Logic) > 0 {
		b.WriteString(",\n\t\tlogic: []logicAccess{")
		if err := renderAccessList(b, prefab.Name, prefab.Logic, logicTypes); err != nil {
			return err
		}
		b.WriteString("}")
	}
	if len(prefab.Slots) > 0 {
		b.WriteString(",\n\t\tSlots: []SlotInfo{")
		for i, slot := range prefab.Slots {
			if slot.Index != i {
				return fmt.Errorf("prefab %s: slot %d is listed at position %d, and the generated table indexes slots by position",
					prefab.Name, slot.Index, i)
			}
			fmt.Fprintf(b, "\n\t\t\t{Class: %q, types: []slotAccess{", slot.Class)
			if err := renderAccessList(b, prefab.Name, slot.Types, slotTypes); err != nil {
				return err
			}
			b.WriteString("}},")
		}
		b.WriteString("\n\t\t}")
	}
	b.WriteString("},\n")
	return nil
}

func renderAccessList(b *strings.Builder, prefab string, entries []LogicAccess, values map[string]int64) error {
	for i, entry := range entries {
		value, ok := values[entry.Name]
		if !ok {
			return fmt.Errorf("prefab %s: %s is not a member of the ISA enumeration it is listed under", prefab, entry.Name)
		}
		name, ok := goAccessConstants[entry.Access]
		if !ok {
			return fmt.Errorf("prefab %s: property %s has access %q", prefab, entry.Name, entry.Access)
		}
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "{%d, %s}", value, name)
	}
	return nil
}

// goAccessConstants maps each access to its internal/ic10 constant name.
var goAccessConstants = map[access]string{
	accessRead:      "accessRead",
	accessWrite:     "accessWrite",
	accessReadWrite: "accessReadWrite",
	accessUnknown:   "accessUnknown",
}

// basicEnumsDoc heads the interpreter's enum tables. It carries what the
// literal below cannot: why one entry has no name, and that the order the
// entries appear in is the order the game resolves them in.
const basicEnumsDoc = `// basicEnumMembers holds the member tables of the BasicEnum entries in
// ProgrammableChip.InternalEnums whose members the machine tables in
// internal/ic10 do not already carry, in game declaration order. That order
// decides which table wins when two of them share a member name, because the
// first match stops the search.
//
// The entry with an empty name is the one the game registers without a type
// prefix, so its members resolve as bare words in any value position; every
// other entry needs a ` + "`Type.Member`" + ` spelling. Each entry is commented with
// the C# enum its members were read from.`

// renderBasicEnums produces the gofmt-formatted contents of the interpreter's
// enum tables.
func renderBasicEnums(isa *ISA) ([]byte, error) {
	if len(isa.BasicEnums) == 0 {
		return nil, errors.New("basic enum table is empty")
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\npackage vm\n\n")
	b.WriteString(basicEnumsDoc)
	b.WriteString("\nvar basicEnumMembers = []struct {\n\tname    string\n\tmembers map[string]int\n}{\n")
	for _, enum := range isa.BasicEnums {
		if len(enum.Members) == 0 {
			return nil, fmt.Errorf("basic enum %q has no members", enum.Prefix)
		}
		fmt.Fprintf(&b, "\t// %s\n\t{name: %q, members: map[string]int{\n", enum.Type, enum.Prefix)
		for _, member := range enum.Members {
			fmt.Fprintf(&b, "\t\t%q: %d,\n", member.Name, member.Value)
		}
		b.WriteString("\t}},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}

// renderEnum writes one operand enum table. The value is always emitted, since
// it is the identity generated code refers to.
func renderEnum(b *strings.Builder, sliceName, infoType, doc string, members []EnumMember) {
	b.WriteString(doc)
	fmt.Fprintf(b, "\nvar %s = []%s{\n", sliceName, infoType)
	for _, member := range members {
		fmt.Fprintf(b, "\t{Name: %q, Value: %d", member.Name, member.Value)
		if member.Deprecated {
			b.WriteString(", Deprecated: true")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
}

// renderOperands writes an instruction's operand list as a Go composite
// literal, or the nil literal for the operandless forms.
func renderOperands(instruction Instruction) (string, error) {
	if len(instruction.Operands) == 0 {
		return "nil", nil
	}
	var b strings.Builder
	b.WriteString("[]Operand{")
	for i, operand := range instruction.Operands {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteByte('{')
		if operand.Name != "" {
			fmt.Fprintf(&b, "Name: %q, ", operand.Name)
		}
		if len(operand.Kinds) == 0 {
			return "", fmt.Errorf("instruction %s operand %d has no kinds", instruction.Mnemonic, i)
		}
		b.WriteString("Kinds: []OperandKind{")
		for j, kind := range operand.Kinds {
			name, ok := goOperandKinds[kind]
			if !ok {
				return "", fmt.Errorf("instruction %s operand %d: unknown kind %q", instruction.Mnemonic, i, kind)
			}
			if j > 0 {
				b.WriteString(", ")
			}
			b.WriteString(name)
		}
		direction, ok := goDirections[operand.Direction]
		if !ok {
			return "", fmt.Errorf("instruction %s operand %d: unknown direction %q", instruction.Mnemonic, i, operand.Direction)
		}
		fmt.Fprintf(&b, "}, Direction: %s}", direction)
	}
	b.WriteByte('}')
	return b.String(), nil
}

// needsMath reports whether any constant must be written as a math package
// call because Go has no literal for it.
func needsMath(values []float64) bool {
	for _, v := range values {
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return true
		}
	}
	return false
}

// goFloat renders v as a Go expression that evaluates to exactly v.
//
// A NaN is written as its bit pattern rather than as math.NaN, whose payload is
// Go's and not the game's.
func goFloat(v float64) string {
	switch {
	case math.IsNaN(v):
		return fmt.Sprintf("math.Float64frombits(%#x)", math.Float64bits(v))
	case math.IsInf(v, 1):
		return "math.Inf(1)"
	case math.IsInf(v, -1):
		return "math.Inf(-1)"
	default:
		return strconv.FormatFloat(v, 'g', -1, 64)
	}
}

// opcodeConst is the exported Go name for a mnemonic's opcode constant.
func opcodeConst(mnemonic string) string {
	return "Op" + strings.ToUpper(mnemonic[:1]) + mnemonic[1:]
}
