package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
)

// generatedHeader marks the output as machine written. The exact wording is
// what golangci-lint and other tools match on to exclude the file.
const generatedHeader = "// Code generated by tools/nodegen. DO NOT EDIT."

// packageDoc introduces the rendered package, up to and including its package
// clause. It is written here rather than in a file of its own beside the output
// because a hand-written file in that package is the thing it tells a reader
// not to add.
const packageDoc = `// Package tsnode is the tree-sitter C grammar's own description of itself,
// rendered into Go. Nothing hand-written belongs here; a name the grammar does
// not give belongs in the package that reads these tables.
package tsnode

`

// nodeType is one entry of a tree-sitter grammar's node types. Root is
// declared but never rendered: decoding rejects an unmodeled key, so a new
// way of describing a grammar fails here rather than silently rendering a
// short table, and Root is simply the one key rendering has no use for.
type nodeType struct {
	Type     string              `json:"type"`
	Named    bool                `json:"named"`
	Root     bool                `json:"root,omitempty"`
	Extra    bool                `json:"extra,omitempty"`
	Fields   map[string]childSet `json:"fields,omitempty"`
	Children *childSet           `json:"children,omitempty"`
	Subtypes []typeRef           `json:"subtypes,omitempty"`
}

// childSet is the set of node kinds one slot of a node admits.
type childSet struct {
	Multiple bool      `json:"multiple"`
	Required bool      `json:"required"`
	Types    []typeRef `json:"types"`
}

// typeRef names one node kind a slot admits.
type typeRef struct {
	Type  string `json:"type"`
	Named bool   `json:"named"`
}

// sync copies the grammar's description of itself out of the module that ships
// it: the node types into nodeTypes, and the rules into rules.
func sync(nodeTypes, rules string) error {
	dir, err := moduleDir(grammarModule)
	if err != nil {
		return err
	}
	// Each file is parsed before it is written, so a grammar this generator
	// cannot read is reported here rather than as a decode failure on a file
	// already checked in.
	copies := []struct {
		src, out string
		read     func([]byte) error
	}{
		{
			src: filepath.Join(dir, grammarNodeTypes), out: nodeTypes,
			read: func(data []byte) error { _, err := decodeNodeTypes(data); return err },
		},
		{
			src: filepath.Join(dir, grammarRules), out: rules,
			read: func(data []byte) error { _, err := decodeSpellings(data); return err },
		},
	}
	for _, c := range copies {
		data, err := os.ReadFile(c.src)
		if err != nil {
			return fmt.Errorf("read %s: %w", c.src, err)
		}
		if err := c.read(data); err != nil {
			return fmt.Errorf("%s: %w", c.src, err)
		}
		if err := writeFile(c.out, data); err != nil {
			return err
		}
	}
	return nil
}

// moduleDir answers where the go command has unpacked a module. The grammar's
// node types sit beside the parser it describes rather than in this module, and
// an embed directive cannot reach across that boundary.
func moduleDir(module string) (string, error) {
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", module)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("locate module %s: %w: %s", module, err, strings.TrimSpace(stderr.String()))
	}
	dir := strings.TrimSpace(string(out))
	if dir == "" {
		return "", fmt.Errorf("locate module %s: the go command named no directory", module)
	}
	return dir, nil
}

// generate renders the node kind tables from the checked-in grammar. It reads
// nothing else, so it runs without the grammar module present.
func generate(nodeTypes, rules, out string) error {
	typesData, err := os.ReadFile(nodeTypes)
	if err != nil {
		return fmt.Errorf("read %s: %w", nodeTypes, err)
	}
	types, err := decodeNodeTypes(typesData)
	if err != nil {
		return fmt.Errorf("%s: %w", nodeTypes, err)
	}
	rulesData, err := os.ReadFile(rules)
	if err != nil {
		return fmt.Errorf("read %s: %w", rules, err)
	}
	spellings, err := decodeSpellings(rulesData)
	if err != nil {
		return fmt.Errorf("%s: %w", rules, err)
	}
	rendered, err := render(types, spellings)
	if err != nil {
		return fmt.Errorf("render node kinds from %s: %w", nodeTypes, err)
	}
	return writeFile(out, rendered)
}

// decodeNodeTypes reads a grammar's node types. Unknown fields are rejected, so
// a grammar describing its nodes in a way this generator does not model is
// reported rather than silently rendered short.
func decodeNodeTypes(data []byte) ([]nodeType, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var types []nodeType
	if err := dec.Decode(&types); err != nil {
		return nil, fmt.Errorf("decode: %w", err)
	}
	if len(types) == 0 {
		return nil, fmt.Errorf("the grammar describes no node kinds")
	}
	return types, nil
}

// decodeSpellings gives every literal a grammar's rules are written with,
// ascending. Rules are walked as decoded JSON rather than modelled the way
// node types are, since a grammar nests rule forms arbitrarily and only one
// leaf is wanted out of them. A rule holding no literal is an error, not an empty set.
func decodeSpellings(data []byte) ([]string, error) {
	var rules any
	if err := json.Unmarshal(data, &rules); err != nil {
		return nil, fmt.Errorf("decode: %w", err)
	}
	found := map[string]bool{}
	collectSpellings(rules, found)
	if len(found) == 0 {
		return nil, fmt.Errorf("the rules are written with no literal")
	}
	return slices.Sorted(maps.Keys(found)), nil
}

// collectSpellings gathers the literals under one decoded rule. A grammar spells
// one as a node of its own, so the walk is over every value rather than over the
// keys a rule form declares.
func collectSpellings(rule any, into map[string]bool) {
	switch r := rule.(type) {
	case map[string]any:
		if spelling, spelled := r["value"].(string); spelled && r["type"] == "STRING" {
			into[spelling] = true
		}
		for _, member := range r {
			collectSpellings(member, into)
		}
	case []any:
		for _, member := range r {
			collectSpellings(member, into)
		}
	}
}

func writeFile(path string, data []byte) error {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create output directory for %s: %w", path, err)
		}
	}
	// The grammar ships out of the module cache, which is read only, so a copy
	// of one made with its mode carried over cannot be written a second time.
	// Removing first is what makes the generator runnable however the file it
	// last wrote came to be there.
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("replace %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func render(types []nodeType, spellings []string) ([]byte, error) {
	types = slices.Clone(types)
	slices.SortFunc(types, func(a, b nodeType) int { return strings.Compare(a.Type, b.Type) })

	kindNames, err := kindIdents(types)
	if err != nil {
		return nil, err
	}
	fieldNames, err := fieldIdents(types)
	if err != nil {
		return nil, err
	}

	r := &renderer{types: types, kinds: kindNames, fields: fieldNames}
	r.preamble()
	r.constants()
	r.allKinds()
	r.extras()
	r.tokens()
	r.spellings(spellings)
	r.subtypes()
	r.fieldTypes()
	r.childTypes()

	formatted, err := format.Source([]byte(r.b.String()))
	if err != nil {
		return nil, fmt.Errorf("format rendered source: %w", err)
	}
	return formatted, nil
}

// renderer accumulates the rendered package. Its methods run in the order the
// output reads, and each writes one declaration together with the doc comment
// that introduces it, so the two cannot drift apart.
type renderer struct {
	b     strings.Builder
	types []nodeType
	// kinds and fields give the Go identifier each grammar name is rendered
	// under, keyed by that name.
	kinds  map[string]string
	fields map[string]string
}

func (r *renderer) preamble() {
	r.b.WriteString(generatedHeader)
	r.b.WriteString("\n\n")
	r.b.WriteString(packageDoc)
	r.b.WriteString(`// Kind is a node kind as tree_sitter.Node.Kind reports it: the grammar rule
// behind a named node, the spelling itself for an anonymous one. Kinds are
// matched rather than kind ids, which the grammar gives several of per name.
type Kind string

// Field names one slot of a node, as tree_sitter.Node.ChildByFieldName takes it.
type Field string

`)
}

func (r *renderer) constants() {
	r.b.WriteString("// Node kinds the grammar can produce.\nconst (\n")
	for _, t := range r.types {
		fmt.Fprintf(&r.b, "\t%s Kind = %q\n", r.kinds[t.Type], t.Type)
	}
	r.b.WriteString(")\n\n")

	r.b.WriteString("// Field names the grammar gives to node slots.\nconst (\n")
	for _, name := range slices.Sorted(maps.Keys(r.fields)) {
		fmt.Fprintf(&r.b, "\t%s Field = %q\n", r.fields[name], name)
	}
	r.b.WriteString(")\n\n")
}

func (r *renderer) allKinds() {
	r.kindList("// AllKinds is every kind the grammar can produce, in name order.\nvar AllKinds = []Kind{\n",
		func(nodeType) bool { return true })
}

func (r *renderer) extras() {
	r.kindList(`// Extras are the kinds the grammar admits between any two tokens, so a walk
// reading children positionally has to step over them anywhere.
var Extras = []Kind{
`, func(t nodeType) bool { return t.Extra })
}

func (r *renderer) tokens() {
	r.kindList(`// Tokens are the kinds the grammar spells rather than names; the kind is the spelling.
var Tokens = []Kind{
`, func(t nodeType) bool { return !t.Named })
}

func (r *renderer) spellings(spellings []string) {
	r.b.WriteString(`// Spellings is every literal the grammar's rules are written with, in name
// order. It reaches where [Tokens] cannot: a grammar naming a single node for a
// whole token (C's true, false, primitive types) leaves the spelling only here.
var Spellings = []string{
`)
	for _, spelling := range spellings {
		fmt.Fprintf(&r.b, "\t%q,\n", spelling)
	}
	r.b.WriteString("}\n\n")
}

func (r *renderer) subtypes() {
	r.kindMap(`// Subtypes expands each supertype into the kinds that stand for it. A supertype
// is never itself a node, so this is the set of forms a slot declared as the
// supertype has to account for.
var Subtypes = map[Kind][]Kind{
`, func(t nodeType) bool { return len(t.Subtypes) > 0 },
		func(t nodeType) { r.refs("\t\t", t.Subtypes) })
}

func (r *renderer) fieldTypes() {
	r.kindMap(`// FieldTypes gives the kinds the grammar admits in each field of each kind, so a
// table keyed on a field's alternatives can be held to the ones that exist.
var FieldTypes = map[Kind]map[Field][]Kind{
`, func(t nodeType) bool { return len(t.Fields) > 0 }, func(t nodeType) {
		for _, field := range slices.Sorted(maps.Keys(t.Fields)) {
			fmt.Fprintf(&r.b, "\t\t%s: {\n", r.fields[field])
			r.refs("\t\t\t", t.Fields[field].Types)
			r.b.WriteString("\t\t},\n")
		}
	})
}

func (r *renderer) childTypes() {
	r.kindMap(`// ChildTypes gives the kinds the grammar admits inside each kind outside every
// named slot. A walk navigating by field alone reads none of them, so a kind here
// that such a walk neither reads nor refuses is one it drops in silence.
var ChildTypes = map[Kind][]Kind{
`, func(t nodeType) bool { return t.Children != nil && len(t.Children.Types) > 0 },
		func(t nodeType) { r.refs("\t\t", t.Children.Types) })
}

// kindList writes opening, which carries the doc comment and the opening brace,
// then every kind include admits, then the closing brace.
func (r *renderer) kindList(opening string, include func(nodeType) bool) {
	r.b.WriteString(opening)
	for _, t := range r.types {
		if include(t) {
			fmt.Fprintf(&r.b, "\t%s,\n", r.kinds[t.Type])
		}
	}
	r.b.WriteString("}\n\n")
}

// kindMap writes opening, then one entry per type has admits, then the closing
// brace. value writes the entry's body, which is already inside its braces.
func (r *renderer) kindMap(opening string, has func(nodeType) bool, value func(nodeType)) {
	r.b.WriteString(opening)
	for _, t := range r.types {
		if !has(t) {
			continue
		}
		fmt.Fprintf(&r.b, "\t%s: {\n", r.kinds[t.Type])
		value(t)
		r.b.WriteString("\t},\n")
	}
	r.b.WriteString("}\n\n")
}

// refs writes a slot's alternatives as kind constants, one to a line at the
// given indent.
func (r *renderer) refs(indent string, alternatives []typeRef) {
	for _, ref := range sortedRefs(alternatives) {
		fmt.Fprintf(&r.b, "%s%s,\n", indent, r.kinds[ref])
	}
}

// sortedRefs orders a slot's alternatives by kind so the rendering is stable
// under a grammar that reorders them.
func sortedRefs(refs []typeRef) []string {
	names := make([]string, len(refs))
	for i, ref := range refs {
		names[i] = ref.Type
	}
	slices.Sort(names)
	return slices.Compact(names)
}

// kindIdents names every kind an exported Go constant. It fails on a kind whose
// name it cannot derive or whose name another kind already took, so a grammar
// that introduces either stops the build here rather than rendering a table
// with two entries for one name.
func kindIdents(types []nodeType) (map[string]string, error) {
	idents := make(map[string]string, len(types))
	taken := make(map[string]string, len(types))
	for _, t := range types {
		ident, err := kindIdent(t)
		if err != nil {
			return nil, err
		}
		if other, clash := taken[ident]; clash {
			return nil, fmt.Errorf("node kinds %q and %q both name the constant %s; give one of them an entry in kindIdentOverrides", other, t.Type, ident)
		}
		taken[ident] = t.Type
		idents[t.Type] = ident
	}
	return idents, nil
}

func kindIdent(t nodeType) (string, error) {
	if override, ok := kindIdentOverrides[t.Type]; ok {
		return "Kind" + override, nil
	}
	// A named kind is the grammar's own rule name, written in snake case, and a
	// leading underscore marks a hidden rule -- which is how a supertype is
	// spelled, and not part of the name a reader knows it by. An anonymous kind
	// is a spelling rather than a name, so every byte of it has to survive.
	if t.Named {
		name, err := camel(strings.TrimPrefix(t.Type, "_"))
		if err != nil {
			return "", fmt.Errorf("node kind %q: %w", t.Type, err)
		}
		return "Kind" + name, nil
	}
	name, err := spellOut(t.Type)
	if err != nil {
		return "", fmt.Errorf("node kind %q: %w", t.Type, err)
	}
	return "Kind" + name, nil
}

// kindIdentOverrides names the kinds whose derived name would collide with
// another's. Every one of them is a spelling that differs from another only in
// the case of a letter, which the derivation folds away.
var kindIdentOverrides = map[string]string{
	"_alignof": "UnderAlignofLower",

	`L"`:  "WideStringPrefix",
	`L'`:  "WideCharPrefix",
	`U"`:  "Utf32StringPrefix",
	`U'`:  "Utf32CharPrefix",
	`u"`:  "Utf16StringPrefix",
	`u'`:  "Utf16CharPrefix",
	`u8"`: "Utf8StringPrefix",
	`u8'`: "Utf8CharPrefix",
}

func fieldIdents(types []nodeType) (map[string]string, error) {
	idents := map[string]string{}
	taken := map[string]string{}
	for _, t := range types {
		for field := range t.Fields {
			if _, done := idents[field]; done {
				continue
			}
			name, err := camel(field)
			if err != nil {
				return nil, fmt.Errorf("field %q: %w", field, err)
			}
			name = "Field" + name
			if other, clash := taken[name]; clash {
				return nil, fmt.Errorf("fields %q and %q both name the constant %s", other, field, name)
			}
			taken[name] = field
			idents[field] = name
		}
	}
	return idents, nil
}

// punctIdents names each byte a kind can be spelled with that cannot appear in
// a Go identifier. Deriving a name rather than listing one per kind is what
// makes the derivation total: a spelling with no name here fails the build
// instead of arriving unnamed.
var punctIdents = map[byte]string{
	'\n': "Newline",
	'!':  "Bang",
	'"':  "Quote",
	'#':  "Hash",
	'%':  "Percent",
	'&':  "Amp",
	'\'': "Tick",
	'(':  "Lparen",
	')':  "Rparen",
	'*':  "Star",
	'+':  "Plus",
	',':  "Comma",
	'-':  "Minus",
	'.':  "Dot",
	'/':  "Slash",
	':':  "Colon",
	';':  "Semi",
	'<':  "Lt",
	'=':  "Eq",
	'>':  "Gt",
	'?':  "Question",
	'[':  "Lbrack",
	']':  "Rbrack",
	'^':  "Caret",
	'_':  "Under",
	'{':  "Lbrace",
	'|':  "Pipe",
	'}':  "Rbrace",
	'~':  "Tilde",
}

// camel derives a Go identifier from a snake case grammar name, which is how
// every rule and every field is written.
func camel(text string) (string, error) {
	if text == "" {
		return "", fmt.Errorf("the empty name names nothing")
	}
	var b strings.Builder
	for word := range strings.SplitSeq(text, "_") {
		if word == "" {
			continue
		}
		if !isAlnum(word[0]) {
			return "", fmt.Errorf("%q is not a snake case name", text)
		}
		b.WriteString(strings.ToUpper(word[:1]))
		b.WriteString(word[1:])
	}
	if b.Len() == 0 {
		return "", fmt.Errorf("%q names nothing once its underscores are dropped", text)
	}
	return b.String(), nil
}

// spellOut derives a Go identifier from a spelling rather than a name. Runs of
// letters and digits are capitalized and every other byte is named, so the
// result carries the whole input and two spellings collide only where they
// differ in the case of a letter alone.
func spellOut(text string) (string, error) {
	if text == "" {
		return "", fmt.Errorf("the empty spelling names nothing")
	}
	var b strings.Builder
	for i := 0; i < len(text); {
		if !isAlnum(text[i]) {
			name, ok := punctIdents[text[i]]
			if !ok {
				return "", fmt.Errorf("no name for the byte %q", text[i:i+1])
			}
			b.WriteString(name)
			i++
			continue
		}
		j := i
		for j < len(text) && isAlnum(text[j]) {
			j++
		}
		b.WriteString(strings.ToUpper(text[i : i+1]))
		b.WriteString(text[i+1 : j])
		i = j
	}
	return b.String(), nil
}

func isAlnum(c byte) bool {
	return c >= '0' && c <= '9' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z'
}
