package main

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/greg2010/ic11c/internal/ic10"
	"github.com/spf13/cobra"
)

// preludeCmd writes the two files a C editor needs to read a MicroC program.
// A subcommand rather than a flag, since it compiles no source and a flag
// would have to suspend the root command's one-source-file rule. The one
// thing it takes away is compiling a file named exactly "prelude".
func preludeCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "prelude [directory]",
		Short: "Write " + ic10.PreludeFileName + " and " + ic10.CompileFlagsFileName + " for a C editor",
		Long: `prelude writes ` + ic10.CompileFlagsFileName + ` into a directory and
` + ic10.PreludeFileName + ` into ` + ic10.PreludeDirName + `/ beneath it, replacing whatever is
there. Together they let a C editor parse, complete and check a MicroC source
file, since MicroC is a subset of C23.

The header goes under ` + ic10.PreludeDirName + `/ because it is generated and stamped with the
game version it came from, and it is not something to read or edit beside the
sources. The flags file stays put: clangd finds it by walking up from the source
it opens, so one at the top of a source tree configures every directory under
it. Its -include argument names the header by a path a C driver resolves against
the flags file's own directory.

The directory defaults to the working directory and must already exist. A
` + ic10.PreludeFileName + ` this command wrote directly into it is removed, since nothing
names that path and a second copy of the header would only go stale. A file of
that name it did not write is reported and left alone.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "."
			if len(args) == 1 {
				dir = args[0]
			}
			return writePrelude(cmd, dir)
		},
	}
}

// writePrelude writes the flags file into dir and the header into the
// generated directory beneath it, naming each on the command's output stream
// once both writes have succeeded, so a redirection under a non-zero status
// catches nothing — consistent with the compiler's own exit statuses.
func writePrelude(cmd *cobra.Command, dir string) error {
	headerDir := filepath.Join(dir, ic10.PreludeDirName)
	// Mkdir, not MkdirAll: an absent dir is reported rather than silently
	// created for a mistyped path.
	if err := os.Mkdir(headerDir, 0o755); err != nil && !errors.Is(err, fs.ErrExist) {
		return withStatus(exitFailure, fmt.Errorf("creating %s: %w", headerDir, err))
	}

	// The built-in flags file is generated by internal/ic10; a shape it
	// cannot read is a defect in this binary, not the caller's input.
	flags, err := ic10.CompileFlagsIncluding(path.Join(ic10.PreludeDirName, ic10.PreludeFileName))
	if err != nil {
		return withStatus(exitInternal, err)
	}

	files := []struct {
		path     string
		contents string
	}{
		{path: filepath.Join(headerDir, ic10.PreludeFileName), contents: ic10.Prelude},
		{path: filepath.Join(dir, ic10.CompileFlagsFileName), contents: flags},
	}
	written := make([]string, len(files))
	for i, file := range files {
		if err := writeFile(file.path, file.contents); err != nil {
			return withStatus(exitFailure, err)
		}
		written[i] = file.path
	}
	if err := removeFlatHeader(cmd, dir); err != nil {
		return err
	}
	return writeLine(cmd.OutOrStdout(), "the list of files written "+outputStream, strings.Join(written, "\n"))
}

// writeFile replaces the file at path with contents. The open is
// non-blocking, since path is caller-controlled and could be a named pipe
// with no reader. It truncates, so a shorter header never leaves a stale
// tail of an older one readable underneath it.
func writeFile(path, contents string) error {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC|syscall.O_NONBLOCK, 0o644)
	if err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return writeThrough(path, f, contents)
}

// writeThrough writes contents through w and closes it, reporting a write or
// close that did not finish. A close failure on a written file is a write
// failure too: buffered bytes not yet landed are where a quota or a full
// filesystem surfaces, so it joins the write's result rather than replacing it.
func writeThrough(path string, w io.WriteCloser, contents string) (err error) {
	defer func() {
		if closeErr := w.Close(); closeErr != nil {
			err = errors.Join(err, fmt.Errorf("closing %s: %w", path, closeErr))
		}
	}()
	n, err := io.WriteString(w, contents)
	return writeFailure(path, n, len(contents), err)
}

// generatedHeaderMarker is the first line of the header this binary carries,
// which every generated prelude opens with regardless of game version. It is
// a conventional generated-code marker rather than one specific to this
// command, so a same-opening file is taken for one an earlier run left.
func generatedHeaderMarker() string {
	marker, _, _ := strings.Cut(ic10.Prelude, "\n")
	return marker
}

// removeFlatHeader deletes a header this command wrote directly into dir,
// the location an older flat layout used — the flags file names only the
// copy under the generated directory. A same-named file this command did not
// recognise is reported and left alone, since dir defaults to the caller's own.
func removeFlatHeader(cmd *cobra.Command, dir string) error {
	flat := filepath.Join(dir, ic10.PreludeFileName)
	opening, err := readHeaderOpening(flat)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return withStatus(exitFailure, err)
	}
	note := "what became of " + flat + " " + errorStream
	if opening != generatedHeaderMarker() {
		return writeLine(cmd.ErrOrStderr(), note,
			fmt.Sprintf("left %s alone, which no %s names but which this command did not write",
				flat, ic10.CompileFlagsFileName))
	}
	if err := os.Remove(flat); err != nil {
		return withStatus(exitFailure, fmt.Errorf("removing %s: %w", flat, err))
	}
	return writeLine(cmd.ErrOrStderr(), note,
		fmt.Sprintf("removed %s, which no %s names", flat, ic10.CompileFlagsFileName))
}

// readHeaderOpening reads as much of path as it takes to recognise a header
// this command wrote, answering with nothing for a name that cannot be one.
// The name is Lstat'd rather than followed: deleting it (see
// [removeFlatHeader]) must not reach through a caller's symlink.
func readHeaderOpening(path string) (_ string, err error) {
	if named, err := os.Lstat(path); err != nil {
		return "", fmt.Errorf("reading %s: %w", path, err)
	} else if !named.Mode().IsRegular() {
		return "", nil
	}

	f, err := os.OpenFile(path, os.O_RDONLY|syscall.O_NONBLOCK, 0)
	if err != nil {
		return "", fmt.Errorf("reading %s: %w", path, err)
	}
	defer func() {
		// A read-only handle's close failure doesn't taint bytes already
		// read; join rather than replace.
		if closeErr := f.Close(); closeErr != nil {
			err = errors.Join(err, fmt.Errorf("closing %s: %w", path, closeErr))
		}
	}()
	return readOpening(path, f)
}

// readOpening reads as much out of f as it takes to recognise a header this
// command wrote, checking the open handle rather than the name so the file
// examined is the file read whatever the name resolved to in between. Only
// the opening line is read: the caller's file can be arbitrarily large.
func readOpening(path string, f fs.File) (string, error) {
	held, err := f.Stat()
	if err != nil {
		return "", fmt.Errorf("reading %s: %w", path, err)
	}
	if !held.Mode().IsRegular() {
		return "", nil
	}

	opening := make([]byte, len(generatedHeaderMarker()))
	n, err := io.ReadFull(f, opening)
	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
		return "", fmt.Errorf("reading %s: %w", path, err)
	}
	return string(opening[:n]), nil
}
