// Code generated by tools/nodegen. DO NOT EDIT.

// Package tsnode is the tree-sitter C grammar's own description of itself,
// rendered into Go. Nothing hand-written belongs here; a name the grammar does
// not give belongs in the package that reads these tables.
package tsnode

// Kind is a node kind as tree_sitter.Node.Kind reports it: the grammar rule
// behind a named node, the spelling itself for an anonymous one. Kinds are
// matched rather than kind ids, which the grammar gives several of per name.
type Kind string

// Field names one slot of a node, as tree_sitter.Node.ChildByFieldName takes it.
type Field string

// Node kinds the grammar can produce.
const (
	KindNewline                         Kind = "\n"
	KindBang                            Kind = "!"
	KindBangEq                          Kind = "!="
	KindQuote                           Kind = "\""
	KindHashDefine                      Kind = "#define"
	KindHashElif                        Kind = "#elif"
	KindHashElifdef                     Kind = "#elifdef"
	KindHashElifndef                    Kind = "#elifndef"
	KindHashElse                        Kind = "#else"
	KindHashEndif                       Kind = "#endif"
	KindHashIf                          Kind = "#if"
	KindHashIfdef                       Kind = "#ifdef"
	KindHashIfndef                      Kind = "#ifndef"
	KindHashInclude                     Kind = "#include"
	KindPercent                         Kind = "%"
	KindPercentEq                       Kind = "%="
	KindAmp                             Kind = "&"
	KindAmpAmp                          Kind = "&&"
	KindAmpEq                           Kind = "&="
	KindTick                            Kind = "'"
	KindLparen                          Kind = "("
	KindRparen                          Kind = ")"
	KindStar                            Kind = "*"
	KindStarEq                          Kind = "*="
	KindPlus                            Kind = "+"
	KindPlusPlus                        Kind = "++"
	KindPlusEq                          Kind = "+="
	KindComma                           Kind = ","
	KindMinus                           Kind = "-"
	KindMinusMinus                      Kind = "--"
	KindMinusEq                         Kind = "-="
	KindMinusGt                         Kind = "->"
	KindDot                             Kind = "."
	KindDotDotDot                       Kind = "..."
	KindSlash                           Kind = "/"
	KindSlashEq                         Kind = "/="
	KindColon                           Kind = ":"
	KindColonColon                      Kind = "::"
	KindSemi                            Kind = ";"
	KindLt                              Kind = "<"
	KindLtLt                            Kind = "<<"
	KindLtLtEq                          Kind = "<<="
	KindLtEq                            Kind = "<="
	KindEq                              Kind = "="
	KindEqEq                            Kind = "=="
	KindGt                              Kind = ">"
	KindGtEq                            Kind = ">="
	KindGtGt                            Kind = ">>"
	KindGtGtEq                          Kind = ">>="
	KindQuestion                        Kind = "?"
	KindWideStringPrefix                Kind = "L\""
	KindWideCharPrefix                  Kind = "L'"
	KindNULL                            Kind = "NULL"
	KindUtf32StringPrefix               Kind = "U\""
	KindUtf32CharPrefix                 Kind = "U'"
	KindLbrack                          Kind = "["
	KindLbrackLbrack                    Kind = "[["
	KindRbrack                          Kind = "]"
	KindRbrackRbrack                    Kind = "]]"
	KindCaret                           Kind = "^"
	KindCaretEq                         Kind = "^="
	KindUnderAlignas                    Kind = "_Alignas"
	KindUnderAlignof                    Kind = "_Alignof"
	KindUnderAtomic                     Kind = "_Atomic"
	KindUnderGeneric                    Kind = "_Generic"
	KindUnderNonnull                    Kind = "_Nonnull"
	KindUnderNoreturn                   Kind = "_Noreturn"
	KindUnderUnderAlignof               Kind = "__alignof"
	KindUnderUnderAlignofUnderUnder     Kind = "__alignof__"
	KindUnderUnderAsm                   Kind = "__asm"
	KindUnderUnderAsmUnderUnder         Kind = "__asm__"
	KindUnderUnderAttribute             Kind = "__attribute"
	KindUnderUnderAttributeUnderUnder   Kind = "__attribute__"
	KindUnderUnderBased                 Kind = "__based"
	KindUnderUnderCdecl                 Kind = "__cdecl"
	KindUnderUnderClrcall               Kind = "__clrcall"
	KindUnderUnderDeclspec              Kind = "__declspec"
	KindUnderUnderExcept                Kind = "__except"
	KindUnderUnderExtensionUnderUnder   Kind = "__extension__"
	KindUnderUnderFastcall              Kind = "__fastcall"
	KindUnderUnderFinally               Kind = "__finally"
	KindUnderUnderForceinline           Kind = "__forceinline"
	KindUnderUnderInline                Kind = "__inline"
	KindUnderUnderInlineUnderUnder      Kind = "__inline__"
	KindUnderUnderLeave                 Kind = "__leave"
	KindUnderUnderRestrictUnderUnder    Kind = "__restrict__"
	KindUnderUnderStdcall               Kind = "__stdcall"
	KindUnderUnderThiscall              Kind = "__thiscall"
	KindUnderUnderThread                Kind = "__thread"
	KindUnderUnderTry                   Kind = "__try"
	KindUnderUnderUnaligned             Kind = "__unaligned"
	KindUnderUnderVectorcall            Kind = "__vectorcall"
	KindUnderUnderVolatileUnderUnder    Kind = "__volatile__"
	KindAbstractDeclarator              Kind = "_abstract_declarator"
	KindUnderAlignofLower               Kind = "_alignof"
	KindDeclarator                      Kind = "_declarator"
	KindFieldDeclarator                 Kind = "_field_declarator"
	KindTypeDeclarator                  Kind = "_type_declarator"
	KindUnderUnaligned                  Kind = "_unaligned"
	KindAbstractArrayDeclarator         Kind = "abstract_array_declarator"
	KindAbstractFunctionDeclarator      Kind = "abstract_function_declarator"
	KindAbstractParenthesizedDeclarator Kind = "abstract_parenthesized_declarator"
	KindAbstractPointerDeclarator       Kind = "abstract_pointer_declarator"
	KindAlignas                         Kind = "alignas"
	KindAlignasQualifier                Kind = "alignas_qualifier"
	KindAlignof                         Kind = "alignof"
	KindAlignofExpression               Kind = "alignof_expression"
	KindArgumentList                    Kind = "argument_list"
	KindArrayDeclarator                 Kind = "array_declarator"
	KindAsm                             Kind = "asm"
	KindAssignmentExpression            Kind = "assignment_expression"
	KindAttribute                       Kind = "attribute"
	KindAttributeDeclaration            Kind = "attribute_declaration"
	KindAttributeSpecifier              Kind = "attribute_specifier"
	KindAttributedDeclarator            Kind = "attributed_declarator"
	KindAttributedStatement             Kind = "attributed_statement"
	KindAuto                            Kind = "auto"
	KindBinaryExpression                Kind = "binary_expression"
	KindBitfieldClause                  Kind = "bitfield_clause"
	KindBreak                           Kind = "break"
	KindBreakStatement                  Kind = "break_statement"
	KindCallExpression                  Kind = "call_expression"
	KindCase                            Kind = "case"
	KindCaseStatement                   Kind = "case_statement"
	KindCastExpression                  Kind = "cast_expression"
	KindCharLiteral                     Kind = "char_literal"
	KindCharacter                       Kind = "character"
	KindCommaExpression                 Kind = "comma_expression"
	KindComment                         Kind = "comment"
	KindCompoundLiteralExpression       Kind = "compound_literal_expression"
	KindCompoundStatement               Kind = "compound_statement"
	KindConcatenatedString              Kind = "concatenated_string"
	KindConditionalExpression           Kind = "conditional_expression"
	KindConst                           Kind = "const"
	KindConstexpr                       Kind = "constexpr"
	KindContinue                        Kind = "continue"
	KindContinueStatement               Kind = "continue_statement"
	KindDeclaration                     Kind = "declaration"
	KindDeclarationList                 Kind = "declaration_list"
	KindDefault                         Kind = "default"
	KindDefined                         Kind = "defined"
	KindDo                              Kind = "do"
	KindDoStatement                     Kind = "do_statement"
	KindElse                            Kind = "else"
	KindElseClause                      Kind = "else_clause"
	KindEnum                            Kind = "enum"
	KindEnumSpecifier                   Kind = "enum_specifier"
	KindEnumerator                      Kind = "enumerator"
	KindEnumeratorList                  Kind = "enumerator_list"
	KindEscapeSequence                  Kind = "escape_sequence"
	KindExpression                      Kind = "expression"
	KindExpressionStatement             Kind = "expression_statement"
	KindExtensionExpression             Kind = "extension_expression"
	KindExtern                          Kind = "extern"
	KindFalse                           Kind = "false"
	KindFieldDeclaration                Kind = "field_declaration"
	KindFieldDeclarationList            Kind = "field_declaration_list"
	KindFieldDesignator                 Kind = "field_designator"
	KindFieldExpression                 Kind = "field_expression"
	KindFieldIdentifier                 Kind = "field_identifier"
	KindFor                             Kind = "for"
	KindForStatement                    Kind = "for_statement"
	KindFunctionDeclarator              Kind = "function_declarator"
	KindFunctionDefinition              Kind = "function_definition"
	KindGenericExpression               Kind = "generic_expression"
	KindGnuAsmClobberList               Kind = "gnu_asm_clobber_list"
	KindGnuAsmExpression                Kind = "gnu_asm_expression"
	KindGnuAsmGotoList                  Kind = "gnu_asm_goto_list"
	KindGnuAsmInputOperand              Kind = "gnu_asm_input_operand"
	KindGnuAsmInputOperandList          Kind = "gnu_asm_input_operand_list"
	KindGnuAsmOutputOperand             Kind = "gnu_asm_output_operand"
	KindGnuAsmOutputOperandList         Kind = "gnu_asm_output_operand_list"
	KindGnuAsmQualifier                 Kind = "gnu_asm_qualifier"
	KindGoto                            Kind = "goto"
	KindGotoStatement                   Kind = "goto_statement"
	KindIdentifier                      Kind = "identifier"
	KindIf                              Kind = "if"
	KindIfStatement                     Kind = "if_statement"
	KindInitDeclarator                  Kind = "init_declarator"
	KindInitializerList                 Kind = "initializer_list"
	KindInitializerPair                 Kind = "initializer_pair"
	KindInline                          Kind = "inline"
	KindLabeledStatement                Kind = "labeled_statement"
	KindLinkageSpecification            Kind = "linkage_specification"
	KindLong                            Kind = "long"
	KindMacroTypeSpecifier              Kind = "macro_type_specifier"
	KindMsBasedModifier                 Kind = "ms_based_modifier"
	KindMsCallModifier                  Kind = "ms_call_modifier"
	KindMsDeclspecModifier              Kind = "ms_declspec_modifier"
	KindMsPointerModifier               Kind = "ms_pointer_modifier"
	KindMsRestrictModifier              Kind = "ms_restrict_modifier"
	KindMsSignedPtrModifier             Kind = "ms_signed_ptr_modifier"
	KindMsUnalignedPtrModifier          Kind = "ms_unaligned_ptr_modifier"
	KindMsUnsignedPtrModifier           Kind = "ms_unsigned_ptr_modifier"
	KindNoreturn                        Kind = "noreturn"
	KindNull                            Kind = "null"
	KindNullptr                         Kind = "nullptr"
	KindNumberLiteral                   Kind = "number_literal"
	KindOffsetof                        Kind = "offsetof"
	KindOffsetofExpression              Kind = "offsetof_expression"
	KindParameterDeclaration            Kind = "parameter_declaration"
	KindParameterList                   Kind = "parameter_list"
	KindParenthesizedDeclarator         Kind = "parenthesized_declarator"
	KindParenthesizedExpression         Kind = "parenthesized_expression"
	KindPointerDeclarator               Kind = "pointer_declarator"
	KindPointerExpression               Kind = "pointer_expression"
	KindPreprocArg                      Kind = "preproc_arg"
	KindPreprocCall                     Kind = "preproc_call"
	KindPreprocDef                      Kind = "preproc_def"
	KindPreprocDefined                  Kind = "preproc_defined"
	KindPreprocDirective                Kind = "preproc_directive"
	KindPreprocElif                     Kind = "preproc_elif"
	KindPreprocElifdef                  Kind = "preproc_elifdef"
	KindPreprocElse                     Kind = "preproc_else"
	KindPreprocFunctionDef              Kind = "preproc_function_def"
	KindPreprocIf                       Kind = "preproc_if"
	KindPreprocIfdef                    Kind = "preproc_ifdef"
	KindPreprocInclude                  Kind = "preproc_include"
	KindPreprocParams                   Kind = "preproc_params"
	KindPrimitiveType                   Kind = "primitive_type"
	KindRegister                        Kind = "register"
	KindRestrict                        Kind = "restrict"
	KindReturn                          Kind = "return"
	KindReturnStatement                 Kind = "return_statement"
	KindSehExceptClause                 Kind = "seh_except_clause"
	KindSehFinallyClause                Kind = "seh_finally_clause"
	KindSehLeaveStatement               Kind = "seh_leave_statement"
	KindSehTryStatement                 Kind = "seh_try_statement"
	KindShort                           Kind = "short"
	KindSigned                          Kind = "signed"
	KindSizedTypeSpecifier              Kind = "sized_type_specifier"
	KindSizeof                          Kind = "sizeof"
	KindSizeofExpression                Kind = "sizeof_expression"
	KindStatement                       Kind = "statement"
	KindStatementIdentifier             Kind = "statement_identifier"
	KindStatic                          Kind = "static"
	KindStorageClassSpecifier           Kind = "storage_class_specifier"
	KindStringContent                   Kind = "string_content"
	KindStringLiteral                   Kind = "string_literal"
	KindStruct                          Kind = "struct"
	KindStructSpecifier                 Kind = "struct_specifier"
	KindSubscriptDesignator             Kind = "subscript_designator"
	KindSubscriptExpression             Kind = "subscript_expression"
	KindSubscriptRangeDesignator        Kind = "subscript_range_designator"
	KindSwitch                          Kind = "switch"
	KindSwitchStatement                 Kind = "switch_statement"
	KindSystemLibString                 Kind = "system_lib_string"
	KindThreadUnderLocal                Kind = "thread_local"
	KindTranslationUnit                 Kind = "translation_unit"
	KindTrue                            Kind = "true"
	KindTypeDefinition                  Kind = "type_definition"
	KindTypeDescriptor                  Kind = "type_descriptor"
	KindTypeIdentifier                  Kind = "type_identifier"
	KindTypeQualifier                   Kind = "type_qualifier"
	KindTypeSpecifier                   Kind = "type_specifier"
	KindTypedef                         Kind = "typedef"
	KindUtf16StringPrefix               Kind = "u\""
	KindUtf16CharPrefix                 Kind = "u'"
	KindUtf8StringPrefix                Kind = "u8\""
	KindUtf8CharPrefix                  Kind = "u8'"
	KindUnaryExpression                 Kind = "unary_expression"
	KindUnion                           Kind = "union"
	KindUnionSpecifier                  Kind = "union_specifier"
	KindUnsigned                        Kind = "unsigned"
	KindUpdateExpression                Kind = "update_expression"
	KindVariadicParameter               Kind = "variadic_parameter"
	KindVolatile                        Kind = "volatile"
	KindWhile                           Kind = "while"
	KindWhileStatement                  Kind = "while_statement"
	KindLbrace                          Kind = "{"
	KindPipe                            Kind = "|"
	KindPipeEq                          Kind = "|="
	KindPipePipe                        Kind = "||"
	KindRbrace                          Kind = "}"
	KindTilde                           Kind = "~"
)

// Field names the grammar gives to node slots.
const (
	FieldAlternative    Field = "alternative"
	FieldArgument       Field = "argument"
	FieldArguments      Field = "arguments"
	FieldAssemblyCode   Field = "assembly_code"
	FieldBody           Field = "body"
	FieldClobbers       Field = "clobbers"
	FieldCondition      Field = "condition"
	FieldConsequence    Field = "consequence"
	FieldConstraint     Field = "constraint"
	FieldDeclarator     Field = "declarator"
	FieldDesignator     Field = "designator"
	FieldDirective      Field = "directive"
	FieldEnd            Field = "end"
	FieldField          Field = "field"
	FieldFilter         Field = "filter"
	FieldFunction       Field = "function"
	FieldGotoLabels     Field = "goto_labels"
	FieldIndex          Field = "index"
	FieldInitializer    Field = "initializer"
	FieldInputOperands  Field = "input_operands"
	FieldLabel          Field = "label"
	FieldLeft           Field = "left"
	FieldMember         Field = "member"
	FieldName           Field = "name"
	FieldOperand        Field = "operand"
	FieldOperator       Field = "operator"
	FieldOutputOperands Field = "output_operands"
	FieldParameters     Field = "parameters"
	FieldPath           Field = "path"
	FieldPrefix         Field = "prefix"
	FieldRegister       Field = "register"
	FieldRight          Field = "right"
	FieldSize           Field = "size"
	FieldStart          Field = "start"
	FieldSymbol         Field = "symbol"
	FieldType           Field = "type"
	FieldUnderlyingType Field = "underlying_type"
	FieldUpdate         Field = "update"
	FieldValue          Field = "value"
)

// AllKinds is every kind the grammar can produce, in name order.
var AllKinds = []Kind{
	KindNewline,
	KindBang,
	KindBangEq,
	KindQuote,
	KindHashDefine,
	KindHashElif,
	KindHashElifdef,
	KindHashElifndef,
	KindHashElse,
	KindHashEndif,
	KindHashIf,
	KindHashIfdef,
	KindHashIfndef,
	KindHashInclude,
	KindPercent,
	KindPercentEq,
	KindAmp,
	KindAmpAmp,
	KindAmpEq,
	KindTick,
	KindLparen,
	KindRparen,
	KindStar,
	KindStarEq,
	KindPlus,
	KindPlusPlus,
	KindPlusEq,
	KindComma,
	KindMinus,
	KindMinusMinus,
	KindMinusEq,
	KindMinusGt,
	KindDot,
	KindDotDotDot,
	KindSlash,
	KindSlashEq,
	KindColon,
	KindColonColon,
	KindSemi,
	KindLt,
	KindLtLt,
	KindLtLtEq,
	KindLtEq,
	KindEq,
	KindEqEq,
	KindGt,
	KindGtEq,
	KindGtGt,
	KindGtGtEq,
	KindQuestion,
	KindWideStringPrefix,
	KindWideCharPrefix,
	KindNULL,
	KindUtf32StringPrefix,
	KindUtf32CharPrefix,
	KindLbrack,
	KindLbrackLbrack,
	KindRbrack,
	KindRbrackRbrack,
	KindCaret,
	KindCaretEq,
	KindUnderAlignas,
	KindUnderAlignof,
	KindUnderAtomic,
	KindUnderGeneric,
	KindUnderNonnull,
	KindUnderNoreturn,
	KindUnderUnderAlignof,
	KindUnderUnderAlignofUnderUnder,
	KindUnderUnderAsm,
	KindUnderUnderAsmUnderUnder,
	KindUnderUnderAttribute,
	KindUnderUnderAttributeUnderUnder,
	KindUnderUnderBased,
	KindUnderUnderCdecl,
	KindUnderUnderClrcall,
	KindUnderUnderDeclspec,
	KindUnderUnderExcept,
	KindUnderUnderExtensionUnderUnder,
	KindUnderUnderFastcall,
	KindUnderUnderFinally,
	KindUnderUnderForceinline,
	KindUnderUnderInline,
	KindUnderUnderInlineUnderUnder,
	KindUnderUnderLeave,
	KindUnderUnderRestrictUnderUnder,
	KindUnderUnderStdcall,
	KindUnderUnderThiscall,
	KindUnderUnderThread,
	KindUnderUnderTry,
	KindUnderUnderUnaligned,
	KindUnderUnderVectorcall,
	KindUnderUnderVolatileUnderUnder,
	KindAbstractDeclarator,
	KindUnderAlignofLower,
	KindDeclarator,
	KindFieldDeclarator,
	KindTypeDeclarator,
	KindUnderUnaligned,
	KindAbstractArrayDeclarator,
	KindAbstractFunctionDeclarator,
	KindAbstractParenthesizedDeclarator,
	KindAbstractPointerDeclarator,
	KindAlignas,
	KindAlignasQualifier,
	KindAlignof,
	KindAlignofExpression,
	KindArgumentList,
	KindArrayDeclarator,
	KindAsm,
	KindAssignmentExpression,
	KindAttribute,
	KindAttributeDeclaration,
	KindAttributeSpecifier,
	KindAttributedDeclarator,
	KindAttributedStatement,
	KindAuto,
	KindBinaryExpression,
	KindBitfieldClause,
	KindBreak,
	KindBreakStatement,
	KindCallExpression,
	KindCase,
	KindCaseStatement,
	KindCastExpression,
	KindCharLiteral,
	KindCharacter,
	KindCommaExpression,
	KindComment,
	KindCompoundLiteralExpression,
	KindCompoundStatement,
	KindConcatenatedString,
	KindConditionalExpression,
	KindConst,
	KindConstexpr,
	KindContinue,
	KindContinueStatement,
	KindDeclaration,
	KindDeclarationList,
	KindDefault,
	KindDefined,
	KindDo,
	KindDoStatement,
	KindElse,
	KindElseClause,
	KindEnum,
	KindEnumSpecifier,
	KindEnumerator,
	KindEnumeratorList,
	KindEscapeSequence,
	KindExpression,
	KindExpressionStatement,
	KindExtensionExpression,
	KindExtern,
	KindFalse,
	KindFieldDeclaration,
	KindFieldDeclarationList,
	KindFieldDesignator,
	KindFieldExpression,
	KindFieldIdentifier,
	KindFor,
	KindForStatement,
	KindFunctionDeclarator,
	KindFunctionDefinition,
	KindGenericExpression,
	KindGnuAsmClobberList,
	KindGnuAsmExpression,
	KindGnuAsmGotoList,
	KindGnuAsmInputOperand,
	KindGnuAsmInputOperandList,
	KindGnuAsmOutputOperand,
	KindGnuAsmOutputOperandList,
	KindGnuAsmQualifier,
	KindGoto,
	KindGotoStatement,
	KindIdentifier,
	KindIf,
	KindIfStatement,
	KindInitDeclarator,
	KindInitializerList,
	KindInitializerPair,
	KindInline,
	KindLabeledStatement,
	KindLinkageSpecification,
	KindLong,
	KindMacroTypeSpecifier,
	KindMsBasedModifier,
	KindMsCallModifier,
	KindMsDeclspecModifier,
	KindMsPointerModifier,
	KindMsRestrictModifier,
	KindMsSignedPtrModifier,
	KindMsUnalignedPtrModifier,
	KindMsUnsignedPtrModifier,
	KindNoreturn,
	KindNull,
	KindNullptr,
	KindNumberLiteral,
	KindOffsetof,
	KindOffsetofExpression,
	KindParameterDeclaration,
	KindParameterList,
	KindParenthesizedDeclarator,
	KindParenthesizedExpression,
	KindPointerDeclarator,
	KindPointerExpression,
	KindPreprocArg,
	KindPreprocCall,
	KindPreprocDef,
	KindPreprocDefined,
	KindPreprocDirective,
	KindPreprocElif,
	KindPreprocElifdef,
	KindPreprocElse,
	KindPreprocFunctionDef,
	KindPreprocIf,
	KindPreprocIfdef,
	KindPreprocInclude,
	KindPreprocParams,
	KindPrimitiveType,
	KindRegister,
	KindRestrict,
	KindReturn,
	KindReturnStatement,
	KindSehExceptClause,
	KindSehFinallyClause,
	KindSehLeaveStatement,
	KindSehTryStatement,
	KindShort,
	KindSigned,
	KindSizedTypeSpecifier,
	KindSizeof,
	KindSizeofExpression,
	KindStatement,
	KindStatementIdentifier,
	KindStatic,
	KindStorageClassSpecifier,
	KindStringContent,
	KindStringLiteral,
	KindStruct,
	KindStructSpecifier,
	KindSubscriptDesignator,
	KindSubscriptExpression,
	KindSubscriptRangeDesignator,
	KindSwitch,
	KindSwitchStatement,
	KindSystemLibString,
	KindThreadUnderLocal,
	KindTranslationUnit,
	KindTrue,
	KindTypeDefinition,
	KindTypeDescriptor,
	KindTypeIdentifier,
	KindTypeQualifier,
	KindTypeSpecifier,
	KindTypedef,
	KindUtf16StringPrefix,
	KindUtf16CharPrefix,
	KindUtf8StringPrefix,
	KindUtf8CharPrefix,
	KindUnaryExpression,
	KindUnion,
	KindUnionSpecifier,
	KindUnsigned,
	KindUpdateExpression,
	KindVariadicParameter,
	KindVolatile,
	KindWhile,
	KindWhileStatement,
	KindLbrace,
	KindPipe,
	KindPipeEq,
	KindPipePipe,
	KindRbrace,
	KindTilde,
}

// Extras are the kinds the grammar admits between any two tokens, so a walk
// reading children positionally has to step over them anywhere.
var Extras = []Kind{
	KindComment,
}

// Tokens are the kinds the grammar spells rather than names; the kind is the spelling.
var Tokens = []Kind{
	KindNewline,
	KindBang,
	KindBangEq,
	KindQuote,
	KindHashDefine,
	KindHashElif,
	KindHashElifdef,
	KindHashElifndef,
	KindHashElse,
	KindHashEndif,
	KindHashIf,
	KindHashIfdef,
	KindHashIfndef,
	KindHashInclude,
	KindPercent,
	KindPercentEq,
	KindAmp,
	KindAmpAmp,
	KindAmpEq,
	KindTick,
	KindLparen,
	KindRparen,
	KindStar,
	KindStarEq,
	KindPlus,
	KindPlusPlus,
	KindPlusEq,
	KindComma,
	KindMinus,
	KindMinusMinus,
	KindMinusEq,
	KindMinusGt,
	KindDot,
	KindDotDotDot,
	KindSlash,
	KindSlashEq,
	KindColon,
	KindColonColon,
	KindSemi,
	KindLt,
	KindLtLt,
	KindLtLtEq,
	KindLtEq,
	KindEq,
	KindEqEq,
	KindGt,
	KindGtEq,
	KindGtGt,
	KindGtGtEq,
	KindQuestion,
	KindWideStringPrefix,
	KindWideCharPrefix,
	KindNULL,
	KindUtf32StringPrefix,
	KindUtf32CharPrefix,
	KindLbrack,
	KindLbrackLbrack,
	KindRbrack,
	KindRbrackRbrack,
	KindCaret,
	KindCaretEq,
	KindUnderAlignas,
	KindUnderAlignof,
	KindUnderAtomic,
	KindUnderGeneric,
	KindUnderNonnull,
	KindUnderNoreturn,
	KindUnderUnderAlignof,
	KindUnderUnderAlignofUnderUnder,
	KindUnderUnderAsm,
	KindUnderUnderAsmUnderUnder,
	KindUnderUnderAttribute,
	KindUnderUnderAttributeUnderUnder,
	KindUnderUnderBased,
	KindUnderUnderCdecl,
	KindUnderUnderClrcall,
	KindUnderUnderDeclspec,
	KindUnderUnderExcept,
	KindUnderUnderExtensionUnderUnder,
	KindUnderUnderFastcall,
	KindUnderUnderFinally,
	KindUnderUnderForceinline,
	KindUnderUnderInline,
	KindUnderUnderInlineUnderUnder,
	KindUnderUnderLeave,
	KindUnderUnderRestrictUnderUnder,
	KindUnderUnderStdcall,
	KindUnderUnderThiscall,
	KindUnderUnderThread,
	KindUnderUnderTry,
	KindUnderUnderUnaligned,
	KindUnderUnderVectorcall,
	KindUnderUnderVolatileUnderUnder,
	KindUnderAlignofLower,
	KindUnderUnaligned,
	KindAlignas,
	KindAlignof,
	KindAsm,
	KindAuto,
	KindBreak,
	KindCase,
	KindConst,
	KindConstexpr,
	KindContinue,
	KindDefault,
	KindDefined,
	KindDo,
	KindElse,
	KindEnum,
	KindExtern,
	KindFor,
	KindGoto,
	KindIf,
	KindInline,
	KindLong,
	KindNoreturn,
	KindNullptr,
	KindOffsetof,
	KindRegister,
	KindRestrict,
	KindReturn,
	KindShort,
	KindSigned,
	KindSizeof,
	KindStatic,
	KindStruct,
	KindSwitch,
	KindThreadUnderLocal,
	KindTypedef,
	KindUtf16StringPrefix,
	KindUtf16CharPrefix,
	KindUtf8StringPrefix,
	KindUtf8CharPrefix,
	KindUnion,
	KindUnsigned,
	KindVolatile,
	KindWhile,
	KindLbrace,
	KindPipe,
	KindPipeEq,
	KindPipePipe,
	KindRbrace,
	KindTilde,
}

// Spellings is every literal the grammar's rules are written with, in name
// order. It reaches where [Tokens] cannot: a grammar naming a single node for a
// whole token (C's true, false, primitive types) leaves the spelling only here.
var Spellings = []string{
	"\n",
	"!",
	"!=",
	"\"",
	"%",
	"%=",
	"&",
	"&&",
	"&=",
	"'",
	"(",
	")",
	"*",
	"*=",
	"+",
	"++",
	"+=",
	",",
	"-",
	"--",
	"-=",
	"->",
	".",
	"...",
	"/",
	"/*",
	"//",
	"/=",
	":",
	"::",
	";",
	"<",
	"<<",
	"<<=",
	"<=",
	"=",
	"==",
	">",
	">=",
	">>",
	">>=",
	"?",
	"FALSE",
	"L\"",
	"L'",
	"NULL",
	"TRUE",
	"U\"",
	"U'",
	"[",
	"[[",
	"\\",
	"\\>",
	"]",
	"]]",
	"^",
	"^=",
	"_Alignas",
	"_Alignof",
	"_Atomic",
	"_Generic",
	"_Nonnull",
	"_Noreturn",
	"__alignof",
	"__alignof__",
	"__asm",
	"__asm__",
	"__attribute",
	"__attribute__",
	"__based",
	"__cdecl",
	"__clrcall",
	"__declspec",
	"__except",
	"__extension__",
	"__fastcall",
	"__finally",
	"__forceinline",
	"__inline",
	"__inline__",
	"__leave",
	"__restrict",
	"__restrict__",
	"__sptr",
	"__stdcall",
	"__thiscall",
	"__thread",
	"__try",
	"__unaligned",
	"__uptr",
	"__vectorcall",
	"__volatile__",
	"_alignof",
	"_unaligned",
	"alignas",
	"alignof",
	"asm",
	"auto",
	"bool",
	"break",
	"case",
	"char",
	"char16_t",
	"char32_t",
	"char64_t",
	"char8_t",
	"charptr_t",
	"const",
	"constexpr",
	"continue",
	"default",
	"defined",
	"do",
	"double",
	"else",
	"enum",
	"extern",
	"false",
	"float",
	"for",
	"goto",
	"if",
	"inline",
	"int",
	"int16_t",
	"int32_t",
	"int64_t",
	"int8_t",
	"intptr_t",
	"long",
	"max_align_t",
	"noreturn",
	"nullptr",
	"nullptr_t",
	"offsetof",
	"ptrdiff_t",
	"register",
	"restrict",
	"return",
	"short",
	"signed",
	"size_t",
	"sizeof",
	"ssize_t",
	"static",
	"struct",
	"switch",
	"thread_local",
	"true",
	"typedef",
	"u\"",
	"u'",
	"u8\"",
	"u8'",
	"uint16_t",
	"uint32_t",
	"uint64_t",
	"uint8_t",
	"uintptr_t",
	"union",
	"unsigned",
	"void",
	"volatile",
	"while",
	"{",
	"|",
	"|=",
	"||",
	"}",
	"~",
}

// Subtypes expands each supertype into the kinds that stand for it. A supertype
// is never itself a node, so this is the set of forms a slot declared as the
// supertype has to account for.
var Subtypes = map[Kind][]Kind{
	KindAbstractDeclarator: {
		KindAbstractArrayDeclarator,
		KindAbstractFunctionDeclarator,
		KindAbstractParenthesizedDeclarator,
		KindAbstractPointerDeclarator,
	},
	KindDeclarator: {
		KindArrayDeclarator,
		KindAttributedDeclarator,
		KindFunctionDeclarator,
		KindIdentifier,
		KindParenthesizedDeclarator,
		KindPointerDeclarator,
	},
	KindFieldDeclarator: {
		KindArrayDeclarator,
		KindAttributedDeclarator,
		KindFieldIdentifier,
		KindFunctionDeclarator,
		KindParenthesizedDeclarator,
		KindPointerDeclarator,
	},
	KindTypeDeclarator: {
		KindArrayDeclarator,
		KindAttributedDeclarator,
		KindFunctionDeclarator,
		KindParenthesizedDeclarator,
		KindPointerDeclarator,
		KindPrimitiveType,
		KindTypeIdentifier,
	},
	KindExpression: {
		KindAlignofExpression,
		KindAssignmentExpression,
		KindBinaryExpression,
		KindCallExpression,
		KindCastExpression,
		KindCharLiteral,
		KindCompoundLiteralExpression,
		KindConcatenatedString,
		KindConditionalExpression,
		KindExtensionExpression,
		KindFalse,
		KindFieldExpression,
		KindGenericExpression,
		KindGnuAsmExpression,
		KindIdentifier,
		KindNull,
		KindNumberLiteral,
		KindOffsetofExpression,
		KindParenthesizedExpression,
		KindPointerExpression,
		KindSizeofExpression,
		KindStringLiteral,
		KindSubscriptExpression,
		KindTrue,
		KindUnaryExpression,
		KindUpdateExpression,
	},
	KindStatement: {
		KindAttributedStatement,
		KindBreakStatement,
		KindCaseStatement,
		KindCompoundStatement,
		KindContinueStatement,
		KindDoStatement,
		KindExpressionStatement,
		KindForStatement,
		KindGotoStatement,
		KindIfStatement,
		KindLabeledStatement,
		KindReturnStatement,
		KindSehLeaveStatement,
		KindSehTryStatement,
		KindSwitchStatement,
		KindWhileStatement,
	},
	KindTypeSpecifier: {
		KindEnumSpecifier,
		KindMacroTypeSpecifier,
		KindPrimitiveType,
		KindSizedTypeSpecifier,
		KindStructSpecifier,
		KindTypeIdentifier,
		KindUnionSpecifier,
	},
}

// FieldTypes gives the kinds the grammar admits in each field of each kind, so a
// table keyed on a field's alternatives can be held to the ones that exist.
var FieldTypes = map[Kind]map[Field][]Kind{
	KindAbstractArrayDeclarator: {
		FieldDeclarator: {
			KindAbstractDeclarator,
		},
		FieldSize: {
			KindStar,
			KindExpression,
		},
	},
	KindAbstractFunctionDeclarator: {
		FieldDeclarator: {
			KindAbstractDeclarator,
		},
		FieldParameters: {
			KindParameterList,
		},
	},
	KindAbstractPointerDeclarator: {
		FieldDeclarator: {
			KindAbstractDeclarator,
		},
	},
	KindAlignofExpression: {
		FieldType: {
			KindTypeDescriptor,
		},
	},
	KindArrayDeclarator: {
		FieldDeclarator: {
			KindDeclarator,
			KindFieldDeclarator,
			KindTypeDeclarator,
		},
		FieldSize: {
			KindStar,
			KindExpression,
		},
	},
	KindAssignmentExpression: {
		FieldLeft: {
			KindCallExpression,
			KindFieldExpression,
			KindIdentifier,
			KindParenthesizedExpression,
			KindPointerExpression,
			KindSubscriptExpression,
		},
		FieldOperator: {
			KindPercentEq,
			KindAmpEq,
			KindStarEq,
			KindPlusEq,
			KindMinusEq,
			KindSlashEq,
			KindLtLtEq,
			KindEq,
			KindGtGtEq,
			KindCaretEq,
			KindPipeEq,
		},
		FieldRight: {
			KindExpression,
		},
	},
	KindAttribute: {
		FieldName: {
			KindIdentifier,
		},
		FieldPrefix: {
			KindIdentifier,
		},
	},
	KindBinaryExpression: {
		FieldLeft: {
			KindExpression,
			KindPreprocDefined,
		},
		FieldOperator: {
			KindBangEq,
			KindPercent,
			KindAmp,
			KindAmpAmp,
			KindStar,
			KindPlus,
			KindMinus,
			KindSlash,
			KindLt,
			KindLtLt,
			KindLtEq,
			KindEqEq,
			KindGt,
			KindGtEq,
			KindGtGt,
			KindCaret,
			KindPipe,
			KindPipePipe,
		},
		FieldRight: {
			KindExpression,
			KindPreprocDefined,
		},
	},
	KindCallExpression: {
		FieldArguments: {
			KindArgumentList,
		},
		FieldFunction: {
			KindExpression,
		},
	},
	KindCaseStatement: {
		FieldValue: {
			KindExpression,
		},
	},
	KindCastExpression: {
		FieldType: {
			KindTypeDescriptor,
		},
		FieldValue: {
			KindExpression,
		},
	},
	KindCommaExpression: {
		FieldLeft: {
			KindExpression,
		},
		FieldRight: {
			KindCommaExpression,
			KindExpression,
		},
	},
	KindCompoundLiteralExpression: {
		FieldType: {
			KindTypeDescriptor,
		},
		FieldValue: {
			KindInitializerList,
		},
	},
	KindConditionalExpression: {
		FieldAlternative: {
			KindExpression,
		},
		FieldCondition: {
			KindExpression,
		},
		FieldConsequence: {
			KindCommaExpression,
			KindExpression,
		},
	},
	KindDeclaration: {
		FieldDeclarator: {
			KindArrayDeclarator,
			KindAttributedDeclarator,
			KindFunctionDeclarator,
			KindGnuAsmExpression,
			KindIdentifier,
			KindInitDeclarator,
			KindMsCallModifier,
			KindParenthesizedDeclarator,
			KindPointerDeclarator,
		},
		FieldType: {
			KindTypeSpecifier,
		},
	},
	KindDoStatement: {
		FieldBody: {
			KindStatement,
		},
		FieldCondition: {
			KindParenthesizedExpression,
		},
	},
	KindEnumSpecifier: {
		FieldBody: {
			KindEnumeratorList,
		},
		FieldName: {
			KindTypeIdentifier,
		},
		FieldUnderlyingType: {
			KindPrimitiveType,
		},
	},
	KindEnumerator: {
		FieldName: {
			KindIdentifier,
		},
		FieldValue: {
			KindExpression,
		},
	},
	KindFieldDeclaration: {
		FieldDeclarator: {
			KindFieldDeclarator,
		},
		FieldType: {
			KindTypeSpecifier,
		},
	},
	KindFieldExpression: {
		FieldArgument: {
			KindExpression,
		},
		FieldField: {
			KindFieldIdentifier,
		},
		FieldOperator: {
			KindMinusGt,
			KindDot,
		},
	},
	KindForStatement: {
		FieldBody: {
			KindStatement,
		},
		FieldCondition: {
			KindCommaExpression,
			KindExpression,
		},
		FieldInitializer: {
			KindCommaExpression,
			KindDeclaration,
			KindExpression,
		},
		FieldUpdate: {
			KindCommaExpression,
			KindExpression,
		},
	},
	KindFunctionDeclarator: {
		FieldDeclarator: {
			KindDeclarator,
			KindFieldDeclarator,
			KindTypeDeclarator,
		},
		FieldParameters: {
			KindParameterList,
		},
	},
	KindFunctionDefinition: {
		FieldBody: {
			KindCompoundStatement,
		},
		FieldDeclarator: {
			KindDeclarator,
		},
		FieldType: {
			KindTypeSpecifier,
		},
	},
	KindGnuAsmClobberList: {
		FieldRegister: {
			KindConcatenatedString,
			KindStringLiteral,
		},
	},
	KindGnuAsmExpression: {
		FieldAssemblyCode: {
			KindConcatenatedString,
			KindStringLiteral,
		},
		FieldClobbers: {
			KindGnuAsmClobberList,
		},
		FieldGotoLabels: {
			KindGnuAsmGotoList,
		},
		FieldInputOperands: {
			KindGnuAsmInputOperandList,
		},
		FieldOutputOperands: {
			KindGnuAsmOutputOperandList,
		},
	},
	KindGnuAsmGotoList: {
		FieldLabel: {
			KindIdentifier,
		},
	},
	KindGnuAsmInputOperand: {
		FieldConstraint: {
			KindStringLiteral,
		},
		FieldSymbol: {
			KindIdentifier,
		},
		FieldValue: {
			KindExpression,
		},
	},
	KindGnuAsmInputOperandList: {
		FieldOperand: {
			KindGnuAsmInputOperand,
		},
	},
	KindGnuAsmOutputOperand: {
		FieldConstraint: {
			KindStringLiteral,
		},
		FieldSymbol: {
			KindIdentifier,
		},
		FieldValue: {
			KindExpression,
		},
	},
	KindGnuAsmOutputOperandList: {
		FieldOperand: {
			KindGnuAsmOutputOperand,
		},
	},
	KindGotoStatement: {
		FieldLabel: {
			KindStatementIdentifier,
		},
	},
	KindIfStatement: {
		FieldAlternative: {
			KindElseClause,
		},
		FieldCondition: {
			KindParenthesizedExpression,
		},
		FieldConsequence: {
			KindStatement,
		},
	},
	KindInitDeclarator: {
		FieldDeclarator: {
			KindDeclarator,
		},
		FieldValue: {
			KindExpression,
			KindInitializerList,
		},
	},
	KindInitializerPair: {
		FieldDesignator: {
			KindFieldDesignator,
			KindFieldIdentifier,
			KindSubscriptDesignator,
			KindSubscriptRangeDesignator,
		},
		FieldValue: {
			KindExpression,
			KindInitializerList,
		},
	},
	KindLabeledStatement: {
		FieldLabel: {
			KindStatementIdentifier,
		},
	},
	KindLinkageSpecification: {
		FieldBody: {
			KindDeclaration,
			KindDeclarationList,
			KindFunctionDefinition,
		},
		FieldValue: {
			KindStringLiteral,
		},
	},
	KindMacroTypeSpecifier: {
		FieldName: {
			KindIdentifier,
		},
		FieldType: {
			KindTypeDescriptor,
		},
	},
	KindOffsetofExpression: {
		FieldMember: {
			KindFieldIdentifier,
		},
		FieldType: {
			KindTypeDescriptor,
		},
	},
	KindParameterDeclaration: {
		FieldDeclarator: {
			KindAbstractDeclarator,
			KindDeclarator,
		},
		FieldType: {
			KindTypeSpecifier,
		},
	},
	KindPointerDeclarator: {
		FieldDeclarator: {
			KindDeclarator,
			KindFieldDeclarator,
			KindTypeDeclarator,
		},
	},
	KindPointerExpression: {
		FieldArgument: {
			KindExpression,
		},
		FieldOperator: {
			KindAmp,
			KindStar,
		},
	},
	KindPreprocCall: {
		FieldArgument: {
			KindPreprocArg,
		},
		FieldDirective: {
			KindPreprocDirective,
		},
	},
	KindPreprocDef: {
		FieldName: {
			KindIdentifier,
		},
		FieldValue: {
			KindPreprocArg,
		},
	},
	KindPreprocElif: {
		FieldAlternative: {
			KindPreprocElif,
			KindPreprocElifdef,
			KindPreprocElse,
		},
		FieldCondition: {
			KindBinaryExpression,
			KindCallExpression,
			KindCharLiteral,
			KindIdentifier,
			KindNumberLiteral,
			KindParenthesizedExpression,
			KindPreprocDefined,
			KindUnaryExpression,
		},
	},
	KindPreprocElifdef: {
		FieldAlternative: {
			KindPreprocElif,
			KindPreprocElifdef,
			KindPreprocElse,
		},
		FieldName: {
			KindIdentifier,
		},
	},
	KindPreprocFunctionDef: {
		FieldName: {
			KindIdentifier,
		},
		FieldParameters: {
			KindPreprocParams,
		},
		FieldValue: {
			KindPreprocArg,
		},
	},
	KindPreprocIf: {
		FieldAlternative: {
			KindPreprocElif,
			KindPreprocElifdef,
			KindPreprocElse,
		},
		FieldCondition: {
			KindBinaryExpression,
			KindCallExpression,
			KindCharLiteral,
			KindIdentifier,
			KindNumberLiteral,
			KindParenthesizedExpression,
			KindPreprocDefined,
			KindUnaryExpression,
		},
	},
	KindPreprocIfdef: {
		FieldAlternative: {
			KindPreprocElif,
			KindPreprocElifdef,
			KindPreprocElse,
		},
		FieldName: {
			KindIdentifier,
		},
	},
	KindPreprocInclude: {
		FieldPath: {
			KindCallExpression,
			KindIdentifier,
			KindStringLiteral,
			KindSystemLibString,
		},
	},
	KindSehExceptClause: {
		FieldBody: {
			KindCompoundStatement,
		},
		FieldFilter: {
			KindParenthesizedExpression,
		},
	},
	KindSehFinallyClause: {
		FieldBody: {
			KindCompoundStatement,
		},
	},
	KindSehTryStatement: {
		FieldBody: {
			KindCompoundStatement,
		},
	},
	KindSizedTypeSpecifier: {
		FieldType: {
			KindPrimitiveType,
			KindTypeIdentifier,
		},
	},
	KindSizeofExpression: {
		FieldType: {
			KindTypeDescriptor,
		},
		FieldValue: {
			KindExpression,
		},
	},
	KindStructSpecifier: {
		FieldBody: {
			KindFieldDeclarationList,
		},
		FieldName: {
			KindTypeIdentifier,
		},
	},
	KindSubscriptExpression: {
		FieldArgument: {
			KindExpression,
		},
		FieldIndex: {
			KindExpression,
		},
	},
	KindSubscriptRangeDesignator: {
		FieldEnd: {
			KindExpression,
		},
		FieldStart: {
			KindExpression,
		},
	},
	KindSwitchStatement: {
		FieldBody: {
			KindCompoundStatement,
		},
		FieldCondition: {
			KindParenthesizedExpression,
		},
	},
	KindTypeDefinition: {
		FieldDeclarator: {
			KindTypeDeclarator,
		},
		FieldType: {
			KindTypeSpecifier,
		},
	},
	KindTypeDescriptor: {
		FieldDeclarator: {
			KindAbstractDeclarator,
		},
		FieldType: {
			KindTypeSpecifier,
		},
	},
	KindUnaryExpression: {
		FieldArgument: {
			KindExpression,
			KindPreprocDefined,
		},
		FieldOperator: {
			KindBang,
			KindPlus,
			KindMinus,
			KindTilde,
		},
	},
	KindUnionSpecifier: {
		FieldBody: {
			KindFieldDeclarationList,
		},
		FieldName: {
			KindTypeIdentifier,
		},
	},
	KindUpdateExpression: {
		FieldArgument: {
			KindExpression,
		},
		FieldOperator: {
			KindPlusPlus,
			KindMinusMinus,
		},
	},
	KindWhileStatement: {
		FieldBody: {
			KindStatement,
		},
		FieldCondition: {
			KindParenthesizedExpression,
		},
	},
}

// ChildTypes gives the kinds the grammar admits inside each kind outside every
// named slot. A walk navigating by field alone reads none of them, so a kind here
// that such a walk neither reads nor refuses is one it drops in silence.
var ChildTypes = map[Kind][]Kind{
	KindAbstractArrayDeclarator: {
		KindTypeQualifier,
	},
	KindAbstractParenthesizedDeclarator: {
		KindAbstractDeclarator,
		KindMsCallModifier,
	},
	KindAbstractPointerDeclarator: {
		KindMsPointerModifier,
		KindTypeQualifier,
	},
	KindAlignasQualifier: {
		KindExpression,
		KindTypeDescriptor,
	},
	KindArgumentList: {
		KindCompoundStatement,
		KindExpression,
		KindPreprocDefined,
	},
	KindArrayDeclarator: {
		KindTypeQualifier,
	},
	KindAttribute: {
		KindArgumentList,
	},
	KindAttributeDeclaration: {
		KindAttribute,
	},
	KindAttributeSpecifier: {
		KindArgumentList,
	},
	KindAttributedDeclarator: {
		KindDeclarator,
		KindFieldDeclarator,
		KindTypeDeclarator,
		KindAttributeDeclaration,
	},
	KindAttributedStatement: {
		KindAttributeDeclaration,
		KindStatement,
	},
	KindBitfieldClause: {
		KindExpression,
	},
	KindCaseStatement: {
		KindAttributedStatement,
		KindBreakStatement,
		KindCompoundStatement,
		KindContinueStatement,
		KindDeclaration,
		KindDoStatement,
		KindExpressionStatement,
		KindForStatement,
		KindGotoStatement,
		KindIfStatement,
		KindLabeledStatement,
		KindReturnStatement,
		KindSehLeaveStatement,
		KindSehTryStatement,
		KindSwitchStatement,
		KindTypeDefinition,
		KindWhileStatement,
	},
	KindCharLiteral: {
		KindCharacter,
		KindEscapeSequence,
	},
	KindCompoundStatement: {
		KindDeclaration,
		KindFunctionDefinition,
		KindLinkageSpecification,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
		KindPreprocInclude,
		KindStatement,
		KindTypeDefinition,
		KindTypeSpecifier,
	},
	KindConcatenatedString: {
		KindIdentifier,
		KindStringLiteral,
	},
	KindDeclaration: {
		KindAttributeDeclaration,
		KindAttributeSpecifier,
		KindMsDeclspecModifier,
		KindStorageClassSpecifier,
		KindTypeQualifier,
	},
	KindDeclarationList: {
		KindDeclaration,
		KindFunctionDefinition,
		KindLinkageSpecification,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
		KindPreprocInclude,
		KindStatement,
		KindTypeDefinition,
		KindTypeSpecifier,
	},
	KindElseClause: {
		KindStatement,
	},
	KindEnumSpecifier: {
		KindAttributeSpecifier,
	},
	KindEnumeratorList: {
		KindEnumerator,
		KindPreprocCall,
		KindPreprocIf,
		KindPreprocIfdef,
	},
	KindExpressionStatement: {
		KindCommaExpression,
		KindExpression,
	},
	KindExtensionExpression: {
		KindExpression,
	},
	KindFieldDeclaration: {
		KindAttributeDeclaration,
		KindAttributeSpecifier,
		KindBitfieldClause,
		KindMsDeclspecModifier,
		KindStorageClassSpecifier,
		KindTypeQualifier,
	},
	KindFieldDeclarationList: {
		KindFieldDeclaration,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
	},
	KindFieldDesignator: {
		KindFieldIdentifier,
	},
	KindFunctionDeclarator: {
		KindAttributeSpecifier,
		KindCallExpression,
		KindGnuAsmExpression,
		KindIdentifier,
	},
	KindFunctionDefinition: {
		KindAttributeDeclaration,
		KindAttributeSpecifier,
		KindDeclaration,
		KindMsCallModifier,
		KindMsDeclspecModifier,
		KindStorageClassSpecifier,
		KindTypeQualifier,
	},
	KindGenericExpression: {
		KindExpression,
		KindTypeDescriptor,
	},
	KindGnuAsmExpression: {
		KindGnuAsmQualifier,
	},
	KindInitializerList: {
		KindExpression,
		KindInitializerList,
		KindInitializerPair,
	},
	KindLabeledStatement: {
		KindDeclaration,
		KindStatement,
	},
	KindMsBasedModifier: {
		KindArgumentList,
	},
	KindMsDeclspecModifier: {
		KindIdentifier,
	},
	KindMsPointerModifier: {
		KindMsRestrictModifier,
		KindMsSignedPtrModifier,
		KindMsUnalignedPtrModifier,
		KindMsUnsignedPtrModifier,
	},
	KindParameterDeclaration: {
		KindAttributeDeclaration,
		KindAttributeSpecifier,
		KindMsDeclspecModifier,
		KindStorageClassSpecifier,
		KindTypeQualifier,
	},
	KindParameterList: {
		KindCompoundStatement,
		KindIdentifier,
		KindParameterDeclaration,
		KindVariadicParameter,
	},
	KindParenthesizedDeclarator: {
		KindDeclarator,
		KindFieldDeclarator,
		KindTypeDeclarator,
		KindMsCallModifier,
	},
	KindParenthesizedExpression: {
		KindCommaExpression,
		KindCompoundStatement,
		KindExpression,
		KindPreprocDefined,
	},
	KindPointerDeclarator: {
		KindMsBasedModifier,
		KindMsPointerModifier,
		KindTypeQualifier,
	},
	KindPreprocDefined: {
		KindIdentifier,
	},
	KindPreprocElif: {
		KindDeclaration,
		KindEnumerator,
		KindFieldDeclaration,
		KindFunctionDefinition,
		KindLinkageSpecification,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
		KindPreprocInclude,
		KindStatement,
		KindTypeDefinition,
		KindTypeSpecifier,
	},
	KindPreprocElifdef: {
		KindDeclaration,
		KindEnumerator,
		KindFieldDeclaration,
		KindFunctionDefinition,
		KindLinkageSpecification,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
		KindPreprocInclude,
		KindStatement,
		KindTypeDefinition,
		KindTypeSpecifier,
	},
	KindPreprocElse: {
		KindDeclaration,
		KindEnumerator,
		KindFieldDeclaration,
		KindFunctionDefinition,
		KindLinkageSpecification,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
		KindPreprocInclude,
		KindStatement,
		KindTypeDefinition,
		KindTypeSpecifier,
	},
	KindPreprocIf: {
		KindDeclaration,
		KindEnumerator,
		KindFieldDeclaration,
		KindFunctionDefinition,
		KindLinkageSpecification,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
		KindPreprocInclude,
		KindStatement,
		KindTypeDefinition,
		KindTypeSpecifier,
	},
	KindPreprocIfdef: {
		KindDeclaration,
		KindEnumerator,
		KindFieldDeclaration,
		KindFunctionDefinition,
		KindLinkageSpecification,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
		KindPreprocInclude,
		KindStatement,
		KindTypeDefinition,
		KindTypeSpecifier,
	},
	KindPreprocParams: {
		KindIdentifier,
	},
	KindReturnStatement: {
		KindCommaExpression,
		KindExpression,
	},
	KindSehTryStatement: {
		KindSehExceptClause,
		KindSehFinallyClause,
	},
	KindSizedTypeSpecifier: {
		KindTypeQualifier,
	},
	KindStringLiteral: {
		KindEscapeSequence,
		KindStringContent,
	},
	KindStructSpecifier: {
		KindAttributeSpecifier,
		KindMsDeclspecModifier,
	},
	KindSubscriptDesignator: {
		KindExpression,
	},
	KindTranslationUnit: {
		KindAttributedStatement,
		KindBreakStatement,
		KindCaseStatement,
		KindCompoundStatement,
		KindContinueStatement,
		KindDeclaration,
		KindDoStatement,
		KindExpressionStatement,
		KindForStatement,
		KindFunctionDefinition,
		KindGotoStatement,
		KindIfStatement,
		KindLabeledStatement,
		KindLinkageSpecification,
		KindPreprocCall,
		KindPreprocDef,
		KindPreprocFunctionDef,
		KindPreprocIf,
		KindPreprocIfdef,
		KindPreprocInclude,
		KindReturnStatement,
		KindSwitchStatement,
		KindTypeDefinition,
		KindTypeSpecifier,
		KindWhileStatement,
	},
	KindTypeDefinition: {
		KindAttributeSpecifier,
		KindTypeQualifier,
	},
	KindTypeDescriptor: {
		KindTypeQualifier,
	},
	KindTypeQualifier: {
		KindAlignasQualifier,
	},
	KindUnionSpecifier: {
		KindAttributeSpecifier,
		KindMsDeclspecModifier,
	},
}
