// Code generated by tools/isagen. DO NOT EDIT.

// Package isa is the Stationeers IC10 instruction set and the game's prefab
// roster, extracted from the game assembly. Nothing hand-written belongs here; a
// name the extraction does not give belongs in the package that reads these
// tables. The tables are shared package-level slices, not a copy per caller.
package isa

import (
	"math"
	"strconv"
)

// ManifestID is the Steam depot manifest these tables were extracted from. It
// names the assembly's exact bytes, so a re-extraction from it lands here again.
const ManifestID = "2546537964923579038"

// GameVersion is the assembly file version these tables were extracted from.
const GameVersion = "0.2.6403.27689"

// Direction is what an instruction does to the register an operand names, read
// from the operation class the chip builds rather than from operand position. The
// zero value is DirectionUnknown: an operand built elsewhere states nothing.
type Direction uint8

const (
	DirectionUnknown Direction = iota
	DirectionRead
	DirectionWrite
	DirectionReadWrite
)

var directionNames = [...]string{"unknown", "read", "write", "readwrite"}

func (v Direction) String() string {
	if int(v) >= len(directionNames) {
		return "Direction(" + strconv.FormatUint(uint64(v), 10) + ")"
	}
	return directionNames[v]
}

// Conversion is the reader the operation calls on an operand, which bounds and
// reduces the double the register holds. It is per operand. The zero value is
// ConversionUnknown: an operand built elsewhere states nothing.
type Conversion uint8

const (
	ConversionUnknown Conversion = iota
	ConversionNone
	ConversionInt
	ConversionNarrowedInt
	ConversionSignedLong
	ConversionUnsignedLong
)

var conversionNames = [...]string{"unknown", "none", "int", "narrowed_int", "signed_long", "unsigned_long"}

func (v Conversion) String() string {
	if int(v) >= len(conversionNames) {
		return "Conversion(" + strconv.FormatUint(uint64(v), 10) + ")"
	}
	return conversionNames[v]
}

// OperandKind is a class of value an operand position accepts.
type OperandKind uint8

const (
	OperandRegister OperandKind = iota
	OperandNumber
	OperandInteger
	OperandDevice
	OperandRefID
	OperandLogicType
	OperandLogicSlotType
	OperandBatchMode
	OperandReagentMode
	OperandDeviceHash
	OperandNameHash
	OperandSlotIndex
	OperandString
)

var operandKindTokens = [...]string{"r?", "num", "int", "d?", "id", "logicType", "logicSlotType", "batchMode", "reagentMode", "deviceHash", "nameHash", "slotIndex", "str"}

func (v OperandKind) String() string {
	if int(v) >= len(operandKindTokens) {
		return "OperandKind(" + strconv.FormatUint(uint64(v), 10) + ")"
	}
	return operandKindTokens[v]
}

// Instruction is one mnemonic the chip's assembler accepts.
type Instruction struct {
	Mnemonic string
	// Opcode is the ScriptCommand ordinal, which is also this entry's index in
	// Instructions.
	Opcode uint16
	// Deprecated is the game's retirement flag; a deprecated instruction still
	// assembles and still runs.
	Deprecated bool
	// Example is the game's help text with its colour markup stripped.
	Example string
	// Operands lists the positional operands in order, nil for operandless forms.
	Operands []Operand
	// Implicit lists the registers the instruction reaches without an operand
	// naming them, in register order.
	Implicit []ImplicitUse
}

// Operand is one positional operand.
type Operand struct {
	// Name is the operand's name in the game's help text, empty where it has none.
	Name string
	// Kinds lists the accepted alternatives in help-text order, and is never empty.
	Kinds      []OperandKind
	Direction  Direction
	Conversion Conversion
}

// ImplicitUse is a register an instruction reaches without an operand naming it.
// Register indexes the game's register file.
type ImplicitUse struct {
	Register  uint8
	Direction Direction
}

// EnumMember is one member of an operand enum: the spelling the chip's
// assembler resolves, and the number it resolves to.
type EnumMember struct {
	Name  string
	Value int64
	// Deprecated is the game's retirement flag; a deprecated member still resolves.
	Deprecated bool
}

// Constant is a numeric literal the chip's assembler accepts wherever a number
// is accepted. Values come from the game and are not recomputed.
type Constant struct {
	Name  string
	Value float64
}

// Opcodes in game enum order. They are untyped so a consumer naming one can
// hold it in an opcode type of its own.
const (
	OpL      = 0
	OpS      = 1
	OpLs     = 2
	OpLr     = 3
	OpSb     = 4
	OpLb     = 5
	OpAlias  = 6
	OpMove   = 7
	OpAdd    = 8
	OpSub    = 9
	OpSdse   = 10
	OpSdns   = 11
	OpSlt    = 12
	OpSgt    = 13
	OpSle    = 14
	OpSge    = 15
	OpSeq    = 16
	OpSne    = 17
	OpSap    = 18
	OpSna    = 19
	OpAnd    = 20
	OpOr     = 21
	OpXor    = 22
	OpNor    = 23
	OpMul    = 24
	OpDiv    = 25
	OpMod    = 26
	OpJ      = 27
	OpBltz   = 28
	OpBgez   = 29
	OpBlez   = 30
	OpBgtz   = 31
	OpBdse   = 32
	OpBdns   = 33
	OpBeq    = 34
	OpBne    = 35
	OpBap    = 36
	OpBna    = 37
	OpJal    = 38
	OpBrdse  = 39
	OpBrdns  = 40
	OpBltzal = 41
	OpBgezal = 42
	OpBlezal = 43
	OpBgtzal = 44
	OpBeqal  = 45
	OpBneal  = 46
	OpJr     = 47
	OpBdseal = 48
	OpBdnsal = 49
	OpBrltz  = 50
	OpBrgez  = 51
	OpBrlez  = 52
	OpBrgtz  = 53
	OpBreq   = 54
	OpBrne   = 55
	OpBrap   = 56
	OpBrna   = 57
	OpSqrt   = 58
	OpRound  = 59
	OpTrunc  = 60
	OpCeil   = 61
	OpFloor  = 62
	OpMax    = 63
	OpMin    = 64
	OpAbs    = 65
	OpLog    = 66
	OpExp    = 67
	OpRand   = 68
	OpYield  = 69
	OpLabel  = 70
	OpPeek   = 71
	OpPush   = 72
	OpPop    = 73
	OpHcf    = 74
	OpSelect = 75
	OpBlt    = 76
	OpBgt    = 77
	OpBle    = 78
	OpBge    = 79
	OpBrlt   = 80
	OpBrgt   = 81
	OpBrle   = 82
	OpBrge   = 83
	OpBltal  = 84
	OpBgtal  = 85
	OpBleal  = 86
	OpBgeal  = 87
	OpBapal  = 88
	OpBnaal  = 89
	OpBeqz   = 90
	OpBnez   = 91
	OpBapz   = 92
	OpBnaz   = 93
	OpBreqz  = 94
	OpBrnez  = 95
	OpBrapz  = 96
	OpBrnaz  = 97
	OpBeqzal = 98
	OpBnezal = 99
	OpBapzal = 100
	OpBnazal = 101
	OpSltz   = 102
	OpSgtz   = 103
	OpSlez   = 104
	OpSgez   = 105
	OpSeqz   = 106
	OpSnez   = 107
	OpSapz   = 108
	OpSnaz   = 109
	OpDefine = 110
	OpSleep  = 111
	OpSin    = 112
	OpAsin   = 113
	OpTan    = 114
	OpAtan   = 115
	OpCos    = 116
	OpAcos   = 117
	OpAtan2  = 118
	OpBrnan  = 119
	OpBnan   = 120
	OpSnan   = 121
	OpSnanz  = 122
	OpLbs    = 123
	OpLbn    = 124
	OpSbn    = 125
	OpLbns   = 126
	OpSs     = 127
	OpSbs    = 128
	OpSrl    = 129
	OpSra    = 130
	OpSll    = 131
	OpSla    = 132
	OpNot    = 133
	OpLd     = 134
	OpSd     = 135
	OpPoke   = 136
	OpGetd   = 137
	OpPutd   = 138
	OpGet    = 139
	OpPut    = 140
	OpClr    = 141
	OpClrd   = 142
	OpRmap   = 143
	OpBdnvl  = 144
	OpBdnvs  = 145
	OpPow    = 146
	OpExt    = 147
	OpIns    = 148
	OpLerp   = 149
	OpSgn    = 150
	OpClamp  = 151
	OpRol    = 152
	OpRor    = 153
)

// Instructions holds every mnemonic the chip's assembler accepts, indexed by Opcode.
var Instructions = []Instruction{
	{Mnemonic: "l", Opcode: OpL, Example: "l r? device(d?|r?|id) logicType", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "s", Opcode: OpS, Example: "s device(d?|r?|id) logicType r?", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "ls", Opcode: OpLs, Example: "ls r? device(d?|r?|id) slotIndex logicSlotType", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "lr", Opcode: OpLr, Example: "lr r? device(d?|r?|id) reagentMode int", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandReagentMode}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandInteger}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sb", Opcode: OpSb, Example: "sb deviceHash logicType r?", Operands: []Operand{{Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "lb", Opcode: OpLb, Example: "lb r? deviceHash logicType batchMode", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandBatchMode}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "alias", Opcode: OpAlias, Example: "alias str r?|d?", Operands: []Operand{{Kinds: []OperandKind{OperandString}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandRegister, OperandDevice}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "move", Opcode: OpMove, Example: "move r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "add", Opcode: OpAdd, Example: "add r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sub", Opcode: OpSub, Example: "sub r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sdse", Opcode: OpSdse, Example: "sdse r? device(d?|r?|id)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sdns", Opcode: OpSdns, Example: "sdns r? device(d?|r?|id)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "slt", Opcode: OpSlt, Example: "slt r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sgt", Opcode: OpSgt, Example: "sgt r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sle", Opcode: OpSle, Example: "sle r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sge", Opcode: OpSge, Example: "sge r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "seq", Opcode: OpSeq, Example: "seq r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sne", Opcode: OpSne, Example: "sne r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sap", Opcode: OpSap, Example: "sap r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sna", Opcode: OpSna, Example: "sna r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "and", Opcode: OpAnd, Example: "and r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}}},
	{Mnemonic: "or", Opcode: OpOr, Example: "or r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}}},
	{Mnemonic: "xor", Opcode: OpXor, Example: "xor r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}}},
	{Mnemonic: "nor", Opcode: OpNor, Example: "nor r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}}},
	{Mnemonic: "mul", Opcode: OpMul, Example: "mul r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "div", Opcode: OpDiv, Example: "div r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "mod", Opcode: OpMod, Example: "mod r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "j", Opcode: OpJ, Example: "j int", Operands: []Operand{{Kinds: []OperandKind{OperandInteger}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bltz", Opcode: OpBltz, Example: "bltz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bgez", Opcode: OpBgez, Example: "bgez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "blez", Opcode: OpBlez, Example: "blez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bgtz", Opcode: OpBgtz, Example: "bgtz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bdse", Opcode: OpBdse, Example: "bdse device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bdns", Opcode: OpBdns, Example: "bdns device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "beq", Opcode: OpBeq, Example: "beq a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bne", Opcode: OpBne, Example: "bne a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bap", Opcode: OpBap, Example: "bap a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bna", Opcode: OpBna, Example: "bna a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "jal", Opcode: OpJal, Example: "jal int", Operands: []Operand{{Kinds: []OperandKind{OperandInteger}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionWrite}}},
	{Mnemonic: "brdse", Opcode: OpBrdse, Example: "brdse device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brdns", Opcode: OpBrdns, Example: "brdns device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bltzal", Opcode: OpBltzal, Example: "bltzal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bgezal", Opcode: OpBgezal, Example: "bgezal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "blezal", Opcode: OpBlezal, Example: "blezal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bgtzal", Opcode: OpBgtzal, Example: "bgtzal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "beqal", Opcode: OpBeqal, Example: "beqal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bneal", Opcode: OpBneal, Example: "bneal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "jr", Opcode: OpJr, Example: "jr int", Operands: []Operand{{Kinds: []OperandKind{OperandInteger}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bdseal", Opcode: OpBdseal, Example: "bdseal device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bdnsal", Opcode: OpBdnsal, Example: "bdnsal device(d?|r?|id) a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "brltz", Opcode: OpBrltz, Example: "brltz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brgez", Opcode: OpBrgez, Example: "brgez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brlez", Opcode: OpBrlez, Example: "brlez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brgtz", Opcode: OpBrgtz, Example: "brgtz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "breq", Opcode: OpBreq, Example: "breq a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brne", Opcode: OpBrne, Example: "brne a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brap", Opcode: OpBrap, Example: "brap a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brna", Opcode: OpBrna, Example: "brna a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sqrt", Opcode: OpSqrt, Example: "sqrt r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "round", Opcode: OpRound, Example: "round r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "trunc", Opcode: OpTrunc, Example: "trunc r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "ceil", Opcode: OpCeil, Example: "ceil r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "floor", Opcode: OpFloor, Example: "floor r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "max", Opcode: OpMax, Example: "max r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "min", Opcode: OpMin, Example: "min r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "abs", Opcode: OpAbs, Example: "abs r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "log", Opcode: OpLog, Example: "log r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "exp", Opcode: OpExp, Example: "exp r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "rand", Opcode: OpRand, Example: "rand r?", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}}},
	{Mnemonic: "yield", Opcode: OpYield, Example: "yield", Operands: nil},
	{Mnemonic: "label", Opcode: OpLabel, Deprecated: true, Example: "label d? str", Operands: []Operand{{Kinds: []OperandKind{OperandDevice}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandString}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "peek", Opcode: OpPeek, Example: "peek r?", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 16, Direction: DirectionRead}}},
	{Mnemonic: "push", Opcode: OpPush, Example: "push a(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 16, Direction: DirectionReadWrite}}},
	{Mnemonic: "pop", Opcode: OpPop, Example: "pop r?", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 16, Direction: DirectionReadWrite}}},
	{Mnemonic: "hcf", Opcode: OpHcf, Example: "hcf", Operands: nil},
	{Mnemonic: "select", Opcode: OpSelect, Example: "select r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "blt", Opcode: OpBlt, Example: "blt a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bgt", Opcode: OpBgt, Example: "bgt a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "ble", Opcode: OpBle, Example: "ble a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bge", Opcode: OpBge, Example: "bge a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brlt", Opcode: OpBrlt, Example: "brlt a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brgt", Opcode: OpBrgt, Example: "brgt a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brle", Opcode: OpBrle, Example: "brle a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brge", Opcode: OpBrge, Example: "brge a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bltal", Opcode: OpBltal, Example: "bltal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bgtal", Opcode: OpBgtal, Example: "bgtal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bleal", Opcode: OpBleal, Example: "bleal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bgeal", Opcode: OpBgeal, Example: "bgeal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bapal", Opcode: OpBapal, Example: "bapal a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bnaal", Opcode: OpBnaal, Example: "bnaal a(r?|num) b(r?|num) c(r?|num) d(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "d", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "beqz", Opcode: OpBeqz, Example: "beqz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bnez", Opcode: OpBnez, Example: "bnez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bapz", Opcode: OpBapz, Example: "bapz a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bnaz", Opcode: OpBnaz, Example: "bnaz a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "breqz", Opcode: OpBreqz, Example: "breqz a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brnez", Opcode: OpBrnez, Example: "brnez a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brapz", Opcode: OpBrapz, Example: "brapz a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brnaz", Opcode: OpBrnaz, Example: "brnaz a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "beqzal", Opcode: OpBeqzal, Example: "beqzal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bnezal", Opcode: OpBnezal, Example: "bnezal a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bapzal", Opcode: OpBapzal, Example: "bapzal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "bnazal", Opcode: OpBnazal, Example: "bnazal a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}, Implicit: []ImplicitUse{{Register: 17, Direction: DirectionReadWrite}}},
	{Mnemonic: "sltz", Opcode: OpSltz, Example: "sltz r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sgtz", Opcode: OpSgtz, Example: "sgtz r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "slez", Opcode: OpSlez, Example: "slez r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sgez", Opcode: OpSgez, Example: "sgez r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "seqz", Opcode: OpSeqz, Example: "seqz r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "snez", Opcode: OpSnez, Example: "snez r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sapz", Opcode: OpSapz, Example: "sapz r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "snaz", Opcode: OpSnaz, Example: "snaz r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "define", Opcode: OpDefine, Example: "define str num", Operands: []Operand{{Kinds: []OperandKind{OperandString}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sleep", Opcode: OpSleep, Example: "sleep a(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sin", Opcode: OpSin, Example: "sin r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "asin", Opcode: OpAsin, Example: "asin r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "tan", Opcode: OpTan, Example: "tan r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "atan", Opcode: OpAtan, Example: "atan r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "cos", Opcode: OpCos, Example: "cos r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "acos", Opcode: OpAcos, Example: "acos r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "atan2", Opcode: OpAtan2, Example: "atan2 r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "brnan", Opcode: OpBrnan, Example: "brnan a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bnan", Opcode: OpBnan, Example: "bnan a(r?|num) b(r?|num)", Operands: []Operand{{Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "snan", Opcode: OpSnan, Example: "snan r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "snanz", Opcode: OpSnanz, Example: "snanz r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "lbs", Opcode: OpLbs, Example: "lbs r? deviceHash slotIndex logicSlotType batchMode", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandBatchMode}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "lbn", Opcode: OpLbn, Example: "lbn r? deviceHash nameHash logicType batchMode", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandNameHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandBatchMode}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sbn", Opcode: OpSbn, Example: "sbn deviceHash nameHash logicType r?", Operands: []Operand{{Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandNameHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "lbns", Opcode: OpLbns, Example: "lbns r? deviceHash nameHash slotIndex logicSlotType batchMode", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandNameHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandBatchMode}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "ss", Opcode: OpSs, Example: "ss device(d?|r?|id) slotIndex logicSlotType r?", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sbs", Opcode: OpSbs, Example: "sbs deviceHash slotIndex logicSlotType r?", Operands: []Operand{{Kinds: []OperandKind{OperandDeviceHash}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandSlotIndex}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicSlotType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "srl", Opcode: OpSrl, Example: "srl r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionUnsignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}}},
	{Mnemonic: "sra", Opcode: OpSra, Example: "sra r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}}},
	{Mnemonic: "sll", Opcode: OpSll, Example: "sll r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}}},
	{Mnemonic: "sla", Opcode: OpSla, Example: "sla r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}}},
	{Mnemonic: "not", Opcode: OpNot, Example: "not r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionSignedLong}}},
	{Mnemonic: "ld", Opcode: OpLd, Deprecated: true, Example: "ld r? id(r?|id) logicType", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "id", Kinds: []OperandKind{OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sd", Opcode: OpSd, Deprecated: true, Example: "sd id(r?|id) logicType r?", Operands: []Operand{{Name: "id", Kinds: []OperandKind{OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandRegister}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "poke", Opcode: OpPoke, Example: "poke address(r?|num) value(r?|num)", Operands: []Operand{{Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "value", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "getd", Opcode: OpGetd, Deprecated: true, Example: "getd r? id(r?|id) address(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "id", Kinds: []OperandKind{OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "putd", Opcode: OpPutd, Deprecated: true, Example: "putd id(r?|id) address(r?|num) value(r?|num)", Operands: []Operand{{Name: "id", Kinds: []OperandKind{OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "value", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "get", Opcode: OpGet, Example: "get r? device(d?|r?|id) address(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "put", Opcode: OpPut, Example: "put device(d?|r?|id) address(r?|num) value(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "address", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "value", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "clr", Opcode: OpClr, Example: "clr d?", Operands: []Operand{{Kinds: []OperandKind{OperandDevice}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "clrd", Opcode: OpClrd, Example: "clrd id(r?|num)", Operands: []Operand{{Name: "id", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "rmap", Opcode: OpRmap, Example: "rmap r? d? reagentHash(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandDevice}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "reagentHash", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNarrowedInt}}},
	{Mnemonic: "bdnvl", Opcode: OpBdnvl, Example: "bdnvl device(d?|r?|id) logicType a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "bdnvs", Opcode: OpBdnvs, Example: "bdnvs device(d?|r?|id) logicType a(r?|num)", Operands: []Operand{{Name: "device", Kinds: []OperandKind{OperandDevice, OperandRegister, OperandRefID}, Direction: DirectionRead, Conversion: ConversionNone}, {Kinds: []OperandKind{OperandLogicType}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "pow", Opcode: OpPow, Example: "pow r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "ext", Opcode: OpExt, Example: "ext r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionUnsignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}}},
	{Mnemonic: "ins", Opcode: OpIns, Example: "ins r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionReadWrite, Conversion: ConversionUnsignedLong}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionUnsignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}}},
	{Mnemonic: "lerp", Opcode: OpLerp, Example: "lerp r? a(r?|num) b(r?|num) c(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "c", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "sgn", Opcode: OpSgn, Example: "sgn r? a(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "clamp", Opcode: OpClamp, Example: "clamp r? a(r?|num) min(r?|num) max(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "min", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}, {Name: "max", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionNone}}},
	{Mnemonic: "rol", Opcode: OpRol, Example: "rol r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionUnsignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}}},
	{Mnemonic: "ror", Opcode: OpRor, Example: "ror r? a(r?|num) b(r?|num)", Operands: []Operand{{Kinds: []OperandKind{OperandRegister}, Direction: DirectionWrite, Conversion: ConversionNone}, {Name: "a", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionUnsignedLong}, {Name: "b", Kinds: []OperandKind{OperandRegister, OperandNumber}, Direction: DirectionRead, Conversion: ConversionInt}}},
}

// LogicTypes holds the device properties addressable by l, s and the batch forms.
var LogicTypes = []EnumMember{
	{Name: "None", Value: 0, Deprecated: true},
	{Name: "Power", Value: 1},
	{Name: "Open", Value: 2},
	{Name: "Mode", Value: 3},
	{Name: "Error", Value: 4},
	{Name: "Pressure", Value: 5},
	{Name: "Temperature", Value: 6},
	{Name: "PressureExternal", Value: 7},
	{Name: "PressureInternal", Value: 8},
	{Name: "Activate", Value: 9},
	{Name: "Lock", Value: 10},
	{Name: "Charge", Value: 11},
	{Name: "Setting", Value: 12},
	{Name: "Reagents", Value: 13},
	{Name: "RatioOxygen", Value: 14},
	{Name: "RatioCarbonDioxide", Value: 15},
	{Name: "RatioNitrogen", Value: 16},
	{Name: "RatioPollutant", Value: 17},
	{Name: "RatioMethane", Value: 18},
	{Name: "RatioWater", Value: 19},
	{Name: "Horizontal", Value: 20},
	{Name: "Vertical", Value: 21},
	{Name: "SolarAngle", Value: 22},
	{Name: "Maximum", Value: 23},
	{Name: "Ratio", Value: 24},
	{Name: "PowerPotential", Value: 25},
	{Name: "PowerActual", Value: 26},
	{Name: "Quantity", Value: 27},
	{Name: "On", Value: 28},
	{Name: "ImportQuantity", Value: 29, Deprecated: true},
	{Name: "ImportSlotOccupant", Value: 30, Deprecated: true},
	{Name: "ExportQuantity", Value: 31, Deprecated: true},
	{Name: "ExportSlotOccupant", Value: 32, Deprecated: true},
	{Name: "RequiredPower", Value: 33},
	{Name: "HorizontalRatio", Value: 34},
	{Name: "VerticalRatio", Value: 35},
	{Name: "PowerRequired", Value: 36},
	{Name: "Idle", Value: 37},
	{Name: "Color", Value: 38},
	{Name: "ElevatorSpeed", Value: 39},
	{Name: "ElevatorLevel", Value: 40},
	{Name: "RecipeHash", Value: 41},
	{Name: "ExportSlotHash", Value: 42, Deprecated: true},
	{Name: "ImportSlotHash", Value: 43, Deprecated: true},
	{Name: "PlantHealth1", Value: 44, Deprecated: true},
	{Name: "PlantHealth2", Value: 45, Deprecated: true},
	{Name: "PlantHealth3", Value: 46, Deprecated: true},
	{Name: "PlantHealth4", Value: 47, Deprecated: true},
	{Name: "PlantGrowth1", Value: 48, Deprecated: true},
	{Name: "PlantGrowth2", Value: 49, Deprecated: true},
	{Name: "PlantGrowth3", Value: 50, Deprecated: true},
	{Name: "PlantGrowth4", Value: 51, Deprecated: true},
	{Name: "PlantEfficiency1", Value: 52, Deprecated: true},
	{Name: "PlantEfficiency2", Value: 53, Deprecated: true},
	{Name: "PlantEfficiency3", Value: 54, Deprecated: true},
	{Name: "PlantEfficiency4", Value: 55, Deprecated: true},
	{Name: "PlantHash1", Value: 56, Deprecated: true},
	{Name: "PlantHash2", Value: 57, Deprecated: true},
	{Name: "PlantHash3", Value: 58, Deprecated: true},
	{Name: "PlantHash4", Value: 59, Deprecated: true},
	{Name: "RequestHash", Value: 60},
	{Name: "CompletionRatio", Value: 61},
	{Name: "ClearMemory", Value: 62},
	{Name: "ExportCount", Value: 63},
	{Name: "ImportCount", Value: 64},
	{Name: "PowerGeneration", Value: 65},
	{Name: "TotalMoles", Value: 66},
	{Name: "Volume", Value: 67},
	{Name: "Plant", Value: 68},
	{Name: "Harvest", Value: 69},
	{Name: "Output", Value: 70},
	{Name: "PressureSetting", Value: 71},
	{Name: "TemperatureSetting", Value: 72},
	{Name: "TemperatureExternal", Value: 73},
	{Name: "Filtration", Value: 74},
	{Name: "AirRelease", Value: 75},
	{Name: "PositionX", Value: 76},
	{Name: "PositionY", Value: 77},
	{Name: "PositionZ", Value: 78},
	{Name: "VelocityMagnitude", Value: 79},
	{Name: "VelocityRelativeX", Value: 80},
	{Name: "VelocityRelativeY", Value: 81},
	{Name: "VelocityRelativeZ", Value: 82},
	{Name: "RatioNitrousOxide", Value: 83},
	{Name: "PrefabHash", Value: 84},
	{Name: "ForceWrite", Value: 85},
	{Name: "SignalStrength", Value: 86},
	{Name: "SignalID", Value: 87},
	{Name: "TargetX", Value: 88},
	{Name: "TargetY", Value: 89},
	{Name: "TargetZ", Value: 90},
	{Name: "SettingInput", Value: 91},
	{Name: "SettingOutput", Value: 92},
	{Name: "CurrentResearchPodType", Value: 93},
	{Name: "ManualResearchRequiredPod", Value: 94},
	{Name: "MineablesInVicinity", Value: 95},
	{Name: "MineablesInQueue", Value: 96},
	{Name: "NextWeatherEventTime", Value: 97},
	{Name: "Combustion", Value: 98},
	{Name: "Fuel", Value: 99},
	{Name: "ReturnFuelCost", Value: 100},
	{Name: "CollectableGoods", Value: 101},
	{Name: "Time", Value: 102},
	{Name: "Bpm", Value: 103},
	{Name: "EnvironmentEfficiency", Value: 104},
	{Name: "WorkingGasEfficiency", Value: 105},
	{Name: "PressureInput", Value: 106},
	{Name: "TemperatureInput", Value: 107},
	{Name: "RatioOxygenInput", Value: 108},
	{Name: "RatioCarbonDioxideInput", Value: 109},
	{Name: "RatioNitrogenInput", Value: 110},
	{Name: "RatioPollutantInput", Value: 111},
	{Name: "RatioMethaneInput", Value: 112},
	{Name: "RatioWaterInput", Value: 113},
	{Name: "RatioNitrousOxideInput", Value: 114},
	{Name: "TotalMolesInput", Value: 115},
	{Name: "PressureInput2", Value: 116},
	{Name: "TemperatureInput2", Value: 117},
	{Name: "RatioOxygenInput2", Value: 118},
	{Name: "RatioCarbonDioxideInput2", Value: 119},
	{Name: "RatioNitrogenInput2", Value: 120},
	{Name: "RatioPollutantInput2", Value: 121},
	{Name: "RatioMethaneInput2", Value: 122},
	{Name: "RatioWaterInput2", Value: 123},
	{Name: "RatioNitrousOxideInput2", Value: 124},
	{Name: "TotalMolesInput2", Value: 125},
	{Name: "PressureOutput", Value: 126},
	{Name: "TemperatureOutput", Value: 127},
	{Name: "RatioOxygenOutput", Value: 128},
	{Name: "RatioCarbonDioxideOutput", Value: 129},
	{Name: "RatioNitrogenOutput", Value: 130},
	{Name: "RatioPollutantOutput", Value: 131},
	{Name: "RatioMethaneOutput", Value: 132},
	{Name: "RatioWaterOutput", Value: 133},
	{Name: "RatioNitrousOxideOutput", Value: 134},
	{Name: "TotalMolesOutput", Value: 135},
	{Name: "PressureOutput2", Value: 136},
	{Name: "TemperatureOutput2", Value: 137},
	{Name: "RatioOxygenOutput2", Value: 138},
	{Name: "RatioCarbonDioxideOutput2", Value: 139},
	{Name: "RatioNitrogenOutput2", Value: 140},
	{Name: "RatioPollutantOutput2", Value: 141},
	{Name: "RatioMethaneOutput2", Value: 142},
	{Name: "RatioWaterOutput2", Value: 143},
	{Name: "RatioNitrousOxideOutput2", Value: 144},
	{Name: "TotalMolesOutput2", Value: 145},
	{Name: "CombustionInput", Value: 146},
	{Name: "CombustionInput2", Value: 147},
	{Name: "CombustionOutput", Value: 148},
	{Name: "CombustionOutput2", Value: 149},
	{Name: "OperationalTemperatureEfficiency", Value: 150},
	{Name: "TemperatureDifferentialEfficiency", Value: 151},
	{Name: "PressureEfficiency", Value: 152},
	{Name: "CombustionLimiter", Value: 153},
	{Name: "Throttle", Value: 154},
	{Name: "Rpm", Value: 155},
	{Name: "Stress", Value: 156},
	{Name: "InterrogationProgress", Value: 157},
	{Name: "TargetPadIndex", Value: 158},
	{Name: "SizeX", Value: 160},
	{Name: "SizeY", Value: 161},
	{Name: "SizeZ", Value: 162},
	{Name: "MinimumWattsToContact", Value: 163},
	{Name: "WattsReachingContact", Value: 164},
	{Name: "Channel0", Value: 165},
	{Name: "Channel1", Value: 166},
	{Name: "Channel2", Value: 167},
	{Name: "Channel3", Value: 168},
	{Name: "Channel4", Value: 169},
	{Name: "Channel5", Value: 170},
	{Name: "Channel6", Value: 171},
	{Name: "Channel7", Value: 172},
	{Name: "LineNumber", Value: 173},
	{Name: "Flush", Value: 174},
	{Name: "SoundAlert", Value: 175},
	{Name: "SolarIrradiance", Value: 176},
	{Name: "RatioLiquidNitrogen", Value: 177},
	{Name: "RatioLiquidNitrogenInput", Value: 178},
	{Name: "RatioLiquidNitrogenInput2", Value: 179},
	{Name: "RatioLiquidNitrogenOutput", Value: 180},
	{Name: "RatioLiquidNitrogenOutput2", Value: 181},
	{Name: "VolumeOfLiquid", Value: 182},
	{Name: "RatioLiquidOxygen", Value: 183},
	{Name: "RatioLiquidOxygenInput", Value: 184},
	{Name: "RatioLiquidOxygenInput2", Value: 185},
	{Name: "RatioLiquidOxygenOutput", Value: 186},
	{Name: "RatioLiquidOxygenOutput2", Value: 187},
	{Name: "RatioLiquidMethane", Value: 188},
	{Name: "RatioLiquidMethaneInput", Value: 189},
	{Name: "RatioLiquidMethaneInput2", Value: 190},
	{Name: "RatioLiquidMethaneOutput", Value: 191},
	{Name: "RatioLiquidMethaneOutput2", Value: 192},
	{Name: "RatioSteam", Value: 193},
	{Name: "RatioSteamInput", Value: 194},
	{Name: "RatioSteamInput2", Value: 195},
	{Name: "RatioSteamOutput", Value: 196},
	{Name: "RatioSteamOutput2", Value: 197},
	{Name: "ContactTypeId", Value: 198},
	{Name: "RatioLiquidCarbonDioxide", Value: 199},
	{Name: "RatioLiquidCarbonDioxideInput", Value: 200},
	{Name: "RatioLiquidCarbonDioxideInput2", Value: 201},
	{Name: "RatioLiquidCarbonDioxideOutput", Value: 202},
	{Name: "RatioLiquidCarbonDioxideOutput2", Value: 203},
	{Name: "RatioLiquidPollutant", Value: 204},
	{Name: "RatioLiquidPollutantInput", Value: 205},
	{Name: "RatioLiquidPollutantInput2", Value: 206},
	{Name: "RatioLiquidPollutantOutput", Value: 207},
	{Name: "RatioLiquidPollutantOutput2", Value: 208},
	{Name: "RatioLiquidNitrousOxide", Value: 209},
	{Name: "RatioLiquidNitrousOxideInput", Value: 210},
	{Name: "RatioLiquidNitrousOxideInput2", Value: 211},
	{Name: "RatioLiquidNitrousOxideOutput", Value: 212},
	{Name: "RatioLiquidNitrousOxideOutput2", Value: 213},
	{Name: "Progress", Value: 214},
	{Name: "DestinationCode", Value: 215},
	{Name: "Acceleration", Value: 216},
	{Name: "ReferenceId", Value: 217},
	{Name: "AutoShutOff", Value: 218},
	{Name: "Mass", Value: 219},
	{Name: "DryMass", Value: 220},
	{Name: "Thrust", Value: 221},
	{Name: "Weight", Value: 222},
	{Name: "ThrustToWeight", Value: 223},
	{Name: "TimeToDestination", Value: 224},
	{Name: "BurnTimeRemaining", Value: 225},
	{Name: "AutoLand", Value: 226},
	{Name: "ForwardX", Value: 227},
	{Name: "ForwardY", Value: 228},
	{Name: "ForwardZ", Value: 229},
	{Name: "Orientation", Value: 230},
	{Name: "VelocityX", Value: 231},
	{Name: "VelocityY", Value: 232},
	{Name: "VelocityZ", Value: 233},
	{Name: "PassedMoles", Value: 234},
	{Name: "ExhaustVelocity", Value: 235},
	{Name: "FlightControlRule", Value: 236},
	{Name: "ReEntryAltitude", Value: 237},
	{Name: "Apex", Value: 238},
	{Name: "EntityState", Value: 239},
	{Name: "DrillCondition", Value: 240},
	{Name: "Index", Value: 241},
	{Name: "CelestialHash", Value: 242},
	{Name: "AlignmentError", Value: 243},
	{Name: "DistanceAu", Value: 244},
	{Name: "OrbitPeriod", Value: 245},
	{Name: "Inclination", Value: 246},
	{Name: "Eccentricity", Value: 247},
	{Name: "SemiMajorAxis", Value: 248},
	{Name: "DistanceKm", Value: 249},
	{Name: "CelestialParentHash", Value: 250},
	{Name: "TrueAnomaly", Value: 251},
	{Name: "RatioHydrogen", Value: 252},
	{Name: "RatioLiquidHydrogen", Value: 253},
	{Name: "RatioPollutedWater", Value: 254},
	{Name: "Discover", Value: 255},
	{Name: "Chart", Value: 256},
	{Name: "Survey", Value: 257},
	{Name: "NavPoints", Value: 258},
	{Name: "ChartedNavPoints", Value: 259},
	{Name: "Sites", Value: 260},
	{Name: "CurrentCode", Value: 261},
	{Name: "Density", Value: 262},
	{Name: "Richness", Value: 263},
	{Name: "Size", Value: 264},
	{Name: "TotalQuantity", Value: 265},
	{Name: "MinedQuantity", Value: 266},
	{Name: "BestContactFilter", Value: 267},
	{Name: "NameHash", Value: 268},
	{Name: "Altitude", Value: 269},
	{Name: "TargetSlotIndex", Value: 270},
	{Name: "TargetPrefabHash", Value: 271},
	{Name: "Extended", Value: 272},
	{Name: "NetworkFault", Value: 273},
	{Name: "ProportionalGain", Value: 274},
	{Name: "IntegralGain", Value: 275},
	{Name: "DerivativeGain", Value: 276},
	{Name: "Minimum", Value: 277},
	{Name: "Setpoint", Value: 278},
	{Name: "Reset", Value: 279},
	{Name: "StackSize", Value: 280},
	{Name: "NextWeatherHash", Value: 281},
	{Name: "ContactSlotIndex", Value: 282},
	{Name: "RatioHydrazine", Value: 283},
	{Name: "RatioLiquidHydrazine", Value: 284},
	{Name: "RatioLiquidAlcohol", Value: 285},
	{Name: "RatioHelium", Value: 286},
	{Name: "RatioLiquidSodiumChloride", Value: 287},
	{Name: "RatioSilanol", Value: 288},
	{Name: "RatioLiquidSilanol", Value: 289},
	{Name: "RatioHydrochloricAcid", Value: 290},
	{Name: "RatioLiquidHydrochloricAcid", Value: 291},
	{Name: "RatioOzone", Value: 292},
	{Name: "RatioLiquidOzone", Value: 293},
	{Name: "RatioHydrogenInput", Value: 294},
	{Name: "RatioHydrogenInput2", Value: 295},
	{Name: "RatioHydrogenOutput", Value: 296},
	{Name: "RatioHydrogenOutput2", Value: 297},
	{Name: "RatioLiquidHydrogenInput", Value: 298},
	{Name: "RatioLiquidHydrogenInput2", Value: 299},
	{Name: "RatioLiquidHydrogenOutput", Value: 300},
	{Name: "RatioLiquidHydrogenOutput2", Value: 301},
	{Name: "RatioPollutedWaterInput", Value: 302},
	{Name: "RatioPollutedWaterInput2", Value: 303},
	{Name: "RatioPollutedWaterOutput", Value: 304},
	{Name: "RatioPollutedWaterOutput2", Value: 305},
	{Name: "RatioHydrazineInput", Value: 306},
	{Name: "RatioHydrazineInput2", Value: 307},
	{Name: "RatioHydrazineOutput", Value: 308},
	{Name: "RatioHydrazineOutput2", Value: 309},
	{Name: "RatioLiquidHydrazineInput", Value: 310},
	{Name: "RatioLiquidHydrazineInput2", Value: 311},
	{Name: "RatioLiquidHydrazineOutput", Value: 312},
	{Name: "RatioLiquidHydrazineOutput2", Value: 313},
	{Name: "RatioLiquidAlcoholInput", Value: 314},
	{Name: "RatioLiquidAlcoholInput2", Value: 315},
	{Name: "RatioLiquidAlcoholOutput", Value: 316},
	{Name: "RatioLiquidAlcoholOutput2", Value: 317},
	{Name: "RatioHeliumInput", Value: 318},
	{Name: "RatioHeliumInput2", Value: 319},
	{Name: "RatioHeliumOutput", Value: 320},
	{Name: "RatioHeliumOutput2", Value: 321},
	{Name: "RatioLiquidSodiumChlorideInput", Value: 322},
	{Name: "RatioLiquidSodiumChlorideInput2", Value: 323},
	{Name: "RatioLiquidSodiumChlorideOutput", Value: 324},
	{Name: "RatioLiquidSodiumChlorideOutput2", Value: 325},
	{Name: "RatioSilanolInput", Value: 326},
	{Name: "RatioSilanolInput2", Value: 327},
	{Name: "RatioSilanolOutput", Value: 328},
	{Name: "RatioSilanolOutput2", Value: 329},
	{Name: "RatioLiquidSilanolInput", Value: 330},
	{Name: "RatioLiquidSilanolInput2", Value: 331},
	{Name: "RatioLiquidSilanolOutput", Value: 332},
	{Name: "RatioLiquidSilanolOutput2", Value: 333},
	{Name: "RatioHydrochloricAcidInput", Value: 334},
	{Name: "RatioHydrochloricAcidInput2", Value: 335},
	{Name: "RatioHydrochloricAcidOutput", Value: 336},
	{Name: "RatioHydrochloricAcidOutput2", Value: 337},
	{Name: "RatioLiquidHydrochloricAcidInput", Value: 338},
	{Name: "RatioLiquidHydrochloricAcidInput2", Value: 339},
	{Name: "RatioLiquidHydrochloricAcidOutput", Value: 340},
	{Name: "RatioLiquidHydrochloricAcidOutput2", Value: 341},
	{Name: "RatioOzoneInput", Value: 342},
	{Name: "RatioOzoneInput2", Value: 343},
	{Name: "RatioOzoneOutput", Value: 344},
	{Name: "RatioOzoneOutput2", Value: 345},
	{Name: "RatioLiquidOzoneInput", Value: 346},
	{Name: "RatioLiquidOzoneInput2", Value: 347},
	{Name: "RatioLiquidOzoneOutput", Value: 348},
	{Name: "RatioLiquidOzoneOutput2", Value: 349},
	{Name: "HealthDamage", Value: 350},
	{Name: "StunDamage", Value: 351},
	{Name: "CurrentNodeType", Value: 352},
	{Name: "TargetNodeType", Value: 353},
	{Name: "EnergyConvected", Value: 354},
	{Name: "EnergyRadiated", Value: 355},
	{Name: "Dispense", Value: 356},
	{Name: "DispenseSlot", Value: 357},
	{Name: "Gravity", Value: 358},
}

// LogicSlotTypes holds the slot properties addressable by ls, ss and the batch slot forms.
var LogicSlotTypes = []EnumMember{
	{Name: "None", Value: 0},
	{Name: "Occupied", Value: 1},
	{Name: "OccupantHash", Value: 2},
	{Name: "Quantity", Value: 3},
	{Name: "Damage", Value: 4},
	{Name: "Efficiency", Value: 5},
	{Name: "Health", Value: 6},
	{Name: "Growth", Value: 7},
	{Name: "Pressure", Value: 8},
	{Name: "Temperature", Value: 9},
	{Name: "Charge", Value: 10},
	{Name: "ChargeRatio", Value: 11},
	{Name: "Class", Value: 12},
	{Name: "PressureWaste", Value: 13},
	{Name: "PressureAir", Value: 14},
	{Name: "MaxQuantity", Value: 15},
	{Name: "Mature", Value: 16},
	{Name: "PrefabHash", Value: 17},
	{Name: "Seeding", Value: 18},
	{Name: "LineNumber", Value: 19},
	{Name: "Volume", Value: 20},
	{Name: "Open", Value: 21},
	{Name: "On", Value: 22},
	{Name: "Lock", Value: 23},
	{Name: "SortingClass", Value: 24},
	{Name: "FilterType", Value: 25},
	{Name: "ReferenceId", Value: 26},
	{Name: "HarvestedHash", Value: 27},
	{Name: "Mode", Value: 28},
	{Name: "MaturityRatio", Value: 29},
	{Name: "SeedingRatio", Value: 30},
	{Name: "FreeSlots", Value: 31},
	{Name: "TotalSlots", Value: 32},
}

// BatchModes holds the aggregation modes accepted by the batch load forms.
var BatchModes = []EnumMember{
	{Name: "Average", Value: 0},
	{Name: "Sum", Value: 1},
	{Name: "Minimum", Value: 2},
	{Name: "Maximum", Value: 3},
	{Name: "Count", Value: 4},
}

// ReagentModes holds the reagent views accepted by lr.
var ReagentModes = []EnumMember{
	{Name: "Contents", Value: 0},
	{Name: "Required", Value: 1},
	{Name: "Recipe", Value: 2},
	{Name: "TotalContents", Value: 3},
}

// Constants are in the game's own declaration order.
var Constants = []Constant{
	{Name: "nan", Value: math.Float64frombits(0xfff8000000000000)},
	{Name: "pinf", Value: math.Inf(1)},
	{Name: "ninf", Value: math.Inf(-1)},
	{Name: "pi", Value: 3.141592653589793},
	{Name: "tau", Value: 6.283185307179586},
	{Name: "deg2rad", Value: 0.01745329238474369},
	{Name: "rad2deg", Value: 57.295780181884766},
	{Name: "epsilon", Value: 5e-324},
	{Name: "rgas", Value: 8.31446261815324},
}
