package main

import (
	_ "embed"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// harnessSource is the driver the compile unit is built around. It is
// hand-written and checked in, unlike everything beside it in the output
// directory: it is not the game's code and never was, and its protocol is
// a contract with whatever drives the resulting binary.

//go:embed harness/Harness.cs
var harnessSource string

// outputs are the files the slice writes, in the order the summary lists them.
const (
	chipFile      = "Chip.cs"
	supportFile   = "Support.cs"
	deviceFile    = "Device.cs"
	reagentFile   = "Reagents.cs"
	harnessFile   = "Harness.cs"
	generatedNote = "// Generated by tools/chipgen from the decompiled game source. Do not edit.\n" +
		"// The slices below are the game's own text; every change made to them is\n" +
		"// named in the comment above the slice it was made in.\n\n"
)

// sourcesFile is the C# compiler response file the slice writes beside
// the units, naming every one of them, so the compile list is derived from
// the run rather than repeated by hand elsewhere. It doubles as the record
// of a previous run, which is what makes clearing stale files safe.
const sourcesFile = "sources.rsp"

const sourcesHeader = "# Written by tools/chipgen. The compile units of one slice, in order.\n"

// slice writes the compile unit and returns a summary of what it cut.
// digestPath empty holds the decompile to the checked-in fingerprint and
// refuses one it does not describe; naming a path rewrites that fingerprint
// instead. The summary is printed, not written, since it describes this run and not the tree.
func slice(root, out, digestPath string) (string, error) {
	s := newSlicing(root)
	chip, err := sliceChip(s)
	if err != nil {
		return "", err
	}
	support, err := sliceSupport(s)
	if err != nil {
		return "", err
	}
	device, err := sliceDevice(s)
	if err != nil {
		return "", err
	}
	reagents, err := sliceReagents(s)
	if err != nil {
		return "", err
	}

	// Ahead of the write, so that a decompile nobody has read cannot leave a
	// compile unit on disk for a build to pick up.
	digestNote, err := settleDigest(s, digestPath)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(out, 0o755); err != nil {
		return "", fmt.Errorf("create %s: %w", out, err)
	}
	files := []struct {
		name string
		text string
	}{
		{chipFile, chipHeaderComment + chip.text},
		{supportFile, generatedNote + support},
		{deviceFile, generatedNote + device},
		{reagentFile, generatedNote + reagents},
		{harnessFile, harnessSource},
	}
	names := make([]string, len(files))
	written := map[string]bool{sourcesFile: true}
	for i, file := range files {
		names[i] = file.name
		written[file.name] = true
	}
	// Before the write rather than after it, so that a directory this tool is
	// refused the run of is left exactly as it was found. A refusal that had
	// already written the units would put its own record of an earlier run
	// there, and the second attempt would go through.
	stale, err := staleUnits(out, written)
	if err != nil {
		return "", err
	}

	for _, file := range files {
		path := filepath.Join(out, file.name)
		if err := os.WriteFile(path, []byte(file.text), 0o644); err != nil {
			return "", fmt.Errorf("write %s: %w", path, err)
		}
	}
	sources := filepath.Join(out, sourcesFile)
	if err := os.WriteFile(sources, []byte(sourcesHeader+strings.Join(names, "\n")+"\n"), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", sources, err)
	}
	for _, name := range stale {
		if err := os.Remove(filepath.Join(out, name)); err != nil {
			return "", fmt.Errorf("remove stale %s: %w", filepath.Join(out, name), err)
		}
	}

	var summary strings.Builder
	fmt.Fprintf(&summary, "wrote %s\n", out)
	fmt.Fprintf(&summary, "  %d operation classes, %d parse arms\n", len(chip.operations), len(chip.commands))
	fmt.Fprintf(&summary, "  %s\n", digestNote)
	for _, name := range sortedKeys(chip.droppedTypes) {
		fmt.Fprintf(&summary, "  dropped %s: %s\n", name, chip.droppedTypes[name])
	}
	if len(s.dropped) > 0 {
		fmt.Fprintf(&summary, "  dropped attributes: %s\n", strings.Join(sortedKeys(s.dropped), " "))
	}
	if len(stale) > 0 {
		fmt.Fprintf(&summary, "  removed, written by an earlier slice and not by this one: %s\n", strings.Join(stale, " "))
	}
	return summary.String(), nil
}

// settleDigest holds the decompile to the checked-in fingerprint, or rewrites
// it, and says which it did.
func settleDigest(s *slicing, digestPath string) (string, error) {
	if digestPath != "" {
		if err := os.WriteFile(digestPath, []byte(renderDigest(s.ledger, s.dropped)), 0o644); err != nil {
			return "", fmt.Errorf("write %s: %w", digestPath, err)
		}
		return fmt.Sprintf("rewrote %s from this run: %d records", digestPath, len(s.ledger.records)), nil
	}
	want, err := parseDigest(checkedDigest)
	if err != nil {
		return "", err
	}
	if err := compareDigest(s.ledger, s.dropped, want); err != nil {
		return "", err
	}
	return fmt.Sprintf("%d records match %s", len(s.ledger.records), digestFile), nil
}

// staleUnits names the C# in the output directory this run does not
// write, so a stale definition cannot outlive the game construct it came
// from and be compiled against later. Only C# directly under out counts;
// C# beside no record of an earlier slice is refused rather than silently owned.
func staleUnits(out string, written map[string]bool) ([]string, error) {
	entries, err := os.ReadDir(out)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", out, err)
	}
	var stale []string
	ours := false
	for _, entry := range entries {
		switch {
		case entry.IsDir():
		case entry.Name() == sourcesFile:
			ours = true
		case written[entry.Name()] || !strings.HasSuffix(entry.Name(), ".cs"):
		default:
			stale = append(stale, entry.Name())
		}
	}
	if len(stale) == 0 {
		return nil, nil
	}
	slices.Sort(stale)
	if !ours {
		return nil, fmt.Errorf("%s holds C# this slicer did not write and no %s naming an earlier run: %s\n"+
			"Remove them by hand, or point --out somewhere this tool owns",
			out, sourcesFile, strings.Join(stale, " "))
	}
	return stale, nil
}

// sortedKeys returns a map's keys in a stable order, so two runs over the same
// decompile print the same summary.
func sortedKeys[V any](m map[string]V) []string { return slices.Sorted(maps.Keys(m)) }

const chipHeaderComment = generatedNote +
	"using System;\n" +
	"using System.Collections.Generic;\n" +
	"using System.Globalization;\n" +
	"using System.Text;\n" +
	"using System.Text.RegularExpressions;\n\n"
