package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// generatedHeader marks the output as machine written. The exact wording is
// what golangci-lint and other tools match on to exclude the file.
const generatedHeader = "// Code generated by tools/isagen. DO NOT EDIT."

// outputs names the files generate writes. All five are checked in, and
// check:codegen fails on any that drifted from the JSON it was rendered from.
type outputs struct {
	// tables is the Go the compiler reads the machine through.
	tables string
	// devices is the Go view of the game things a program names by hash, which
	// the instruction set describes no part of.
	devices string
	// prelude and flags are the C editor's view of the same tables: a header
	// declaring what a MicroC program may name, and the argument file that
	// includes it.
	prelude string
	flags   string
	// fixtureFlags configures an editor opening one of the MicroC programs the
	// test corpus holds. It is the same argument file as flags, naming the same
	// header by a path that reaches it from there, so the corpus needs no copy
	// of the header and has nothing of its own to drift.
	fixtureFlags string
}

// generate reads the canonical ISA and device JSON and writes the tables, the
// C prelude and its flags files. It touches nothing else, so it runs on any
// machine without the game. The two inputs are held to one game build and to
// the same shape extraction holds them to, before anything is rendered, so a
// JSON that fails here was hand-edited or came from another build.
func generate(inPath, devicesPath string, out outputs) error {
	isa, err := readJSON[ISA](inPath)
	if err != nil {
		return err
	}
	extracted, err := readJSON[Devices](devicesPath)
	if err != nil {
		return err
	}
	if err := checkSameBuild(extracted, isa); err != nil {
		return err
	}
	if err := validate(isa); err != nil {
		return err
	}
	if err := validateDevices(extracted, isa); err != nil {
		return err
	}

	tables, err := renderTables(isa)
	if err != nil {
		return fmt.Errorf("render tables from %s: %w", inPath, err)
	}
	deviceTables, err := renderDevices(extracted, isa)
	if err != nil {
		return fmt.Errorf("render device tables from %s: %w", devicesPath, err)
	}
	prelude, err := renderPrelude(isa)
	if err != nil {
		return fmt.Errorf("render prelude from %s: %w", inPath, err)
	}
	flags, err := renderFlagsFor(out.flags, out.prelude)
	if err != nil {
		return err
	}
	fixtureFlags, err := renderFlagsFor(out.fixtureFlags, out.prelude)
	if err != nil {
		return err
	}

	for _, file := range []struct {
		path string
		data []byte
	}{
		{out.tables, tables},
		{out.devices, deviceTables},
		{out.prelude, prelude},
		{out.flags, flags},
		{out.fixtureFlags, fixtureFlags},
	} {
		if err := writeGenerated(file.path, file.data); err != nil {
			return err
		}
	}
	return nil
}

func writeGenerated(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// readJSON reads one of the canonical tables. Unknown fields are rejected so a
// table written by a newer isagen is reported rather than silently truncated.
func readJSON[T ISA | Devices | assetPrefabs](path string) (*T, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var table T
	if err := dec.Decode(&table); err != nil {
		return nil, fmt.Errorf("%s: decode: %w", path, err)
	}
	return &table, nil
}

// packageDoc heads the generated package. It is emitted rather than written by
// hand because a hand-written file in that package is exactly what it forbids.
const packageDoc = `// Package isa is the Stationeers IC10 instruction set and the game's prefab
// roster, extracted from the game assembly. Nothing hand-written belongs here; a
// name the extraction does not give belongs in the package that reads these
// tables. The tables are shared package-level slices, not a copy per caller.
package isa`

// instructionTypes are the shapes the instruction tables are written in.
const instructionTypes = `// Instruction is one mnemonic the chip's assembler accepts.
type Instruction struct {
	Mnemonic string
	// Opcode is the ScriptCommand ordinal, which is also this entry's index in
	// Instructions.
	Opcode uint16
	// Deprecated is the game's retirement flag; a deprecated instruction still
	// assembles and still runs.
	Deprecated bool
	// Example is the game's help text with its colour markup stripped.
	Example string
	// Operands lists the positional operands in order, nil for operandless forms.
	Operands []Operand
	// Implicit lists the registers the instruction reaches without an operand
	// naming them, in register order.
	Implicit []ImplicitUse
}

// Operand is one positional operand.
type Operand struct {
	// Name is the operand's name in the game's help text, empty where it has none.
	Name string
	// Kinds lists the accepted alternatives in help-text order, and is never empty.
	Kinds      []OperandKind
	Direction  Direction
	Conversion Conversion
}

// ImplicitUse is a register an instruction reaches without an operand naming it.
// Register indexes the game's register file.
type ImplicitUse struct {
	Register  uint8
	Direction Direction
}

// EnumMember is one member of an operand enum: the spelling the chip's
// assembler resolves, and the number it resolves to.
type EnumMember struct {
	Name  string
	Value int64
	// Deprecated is the game's retirement flag; a deprecated member still resolves.
	Deprecated bool
}

// Constant is a numeric literal the chip's assembler accepts wherever a number
// is accepted. Values come from the game and are not recomputed.
type Constant struct {
	Name  string
	Value float64
}

`

// prefabTypes are the shapes the prefab roster is written in.
const prefabTypes = `// Prefab is one thing the game ships, and what a chip can reach on it once it is
// built. The surfaces never describe a device mid-build.
type Prefab struct {
	// Name is the prefab's own name, which the game hashes. Hash is the number a
	// batch instruction operand carries.
	Name string
	Hash int32
	// Title is the English name the game shows, empty for the few prefabs with none.
	Title string
	// CircuitHolder reports whether the thing can hold a chip, which is what makes
	// it reachable as db rather than only through a pin. CircuitHolderUnknown says
	// that could not be recovered, which is not the same as holding none.
	CircuitHolder        bool
	CircuitHolderUnknown bool
	// Slots is indexed by the slot number an ls or ss operand carries.
	Slots []Slot
	// Modes names the settings the Mode property selects between, indexed by the
	// number a program writes. It is empty when ModesUnknown is set.
	Modes        []string
	ModesUnknown bool
	// Logic lists the properties l, s and the batch forms reach, in LogicType
	// order. A property absent from it is one the device answers nothing for.
	Logic []LogicAccess
}

// Slot is one slot a prefab declares.
type Slot struct {
	// Class is the game's Slot.Class member naming what the slot accepts.
	Class string
	// Types lists the slot properties reachable here, in LogicSlotType order.
	Types []SlotAccess
}

// LogicAccess is one device property together with the directions the game
// allows on it. LogicType is the value the matching LogicTypes member carries.
type LogicAccess struct {
	LogicType uint16
	Allows    Access
}

// SlotAccess is [LogicAccess] for one slot's own properties. SlotType is the
// value the matching LogicSlotTypes member carries.
type SlotAccess struct {
	SlotType uint8
	Allows   Access
}

`

// renderImports writes the import declaration for the named packages, which are
// given in the order gofmt keeps them.
func renderImports(b *strings.Builder, packages ...string) {
	if len(packages) == 1 {
		fmt.Fprintf(b, "import %q\n\n", packages[0])
		return
	}
	b.WriteString("import (\n")
	for _, name := range packages {
		fmt.Fprintf(b, "\t%q\n", name)
	}
	b.WriteString(")\n\n")
}

// renderTables produces the gofmt-formatted contents of the instruction tables.
func renderTables(isa *ISA) ([]byte, error) {
	if len(isa.Instructions) == 0 {
		return nil, fmt.Errorf("instruction table is empty")
	}
	for i, instruction := range isa.Instructions {
		if instruction.Opcode != i {
			return nil, fmt.Errorf("instruction %s has opcode %d at index %d: opcodes must be dense and ordered so Instructions can be indexed by Opcode",
				instruction.Mnemonic, instruction.Opcode, i)
		}
	}

	// The constants are resolved ahead of the file because whether the file
	// imports math is a property of their values.
	values := make([]float64, len(isa.Constants))
	for i, constant := range isa.Constants {
		value, err := constant.Float()
		if err != nil {
			return nil, err
		}
		values[i] = value
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\n")
	b.WriteString(packageDoc)
	b.WriteString("\n\n")
	if needsMath(values) {
		renderImports(&b, "math", "strconv")
	} else {
		renderImports(&b, "strconv")
	}

	fmt.Fprintf(&b, "// ManifestID is the Steam depot manifest these tables were extracted from. It\n// names the assembly's exact bytes, so a re-extraction from it lands here again.\nconst ManifestID = %q\n\n", isa.Manifest)
	fmt.Fprintf(&b, "// GameVersion is the assembly file version these tables were extracted from.\nconst GameVersion = %q\n\n", isa.Version)

	directions.render(&b)
	conversions.render(&b)
	operandKinds.render(&b)
	b.WriteString(instructionTypes)

	b.WriteString("// Opcodes in game enum order. They are untyped so a consumer naming one can\n// hold it in an opcode type of its own.\nconst (\n")
	for _, instruction := range isa.Instructions {
		fmt.Fprintf(&b, "\t%s = %d\n", opcodeConst(instruction.Mnemonic), instruction.Opcode)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Instructions holds every mnemonic the chip's assembler accepts, indexed by Opcode.\nvar Instructions = []Instruction{\n")
	for _, instruction := range isa.Instructions {
		operands, err := renderOperands(instruction)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\t{Mnemonic: %q, Opcode: %s, ", instruction.Mnemonic, opcodeConst(instruction.Mnemonic))
		if instruction.Deprecated {
			b.WriteString("Deprecated: true, ")
		}
		implicit, err := renderImplicit(instruction)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "Example: %q, Operands: %s", instruction.Example, operands)
		if implicit != "" {
			fmt.Fprintf(&b, ", Implicit: %s", implicit)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	renderEnum(&b, "LogicTypes",
		"// LogicTypes holds the device properties addressable by l, s and the batch forms.",
		isa.LogicTypes)
	renderEnum(&b, "LogicSlotTypes",
		"// LogicSlotTypes holds the slot properties addressable by ls, ss and the batch slot forms.",
		isa.SlotTypes)
	renderEnum(&b, "BatchModes",
		"// BatchModes holds the aggregation modes accepted by the batch load forms.",
		isa.BatchModes)
	renderEnum(&b, "ReagentModes",
		"// ReagentModes holds the reagent views accepted by lr.",
		isa.ReagentModes)

	b.WriteString("// Constants are in the game's own declaration order.\nvar Constants = []Constant{\n")
	for i, constant := range isa.Constants {
		fmt.Fprintf(&b, "\t{Name: %q, Value: %s},\n", constant.Name, goFloat(values[i]))
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}

// prefabsDoc heads the prefab table. It carries what the literal below cannot:
// why hashes with no surface are listed, and how the access entries are written.
const prefabsDoc = `// Prefabs holds every thing the game ships, in the game's own roster order.
// Things with no logic surface are listed too, since Hash is what a batch
// operand carries: a hash naming none of these names nothing in this build.
// [LogicAccess] and [SlotAccess] are positional: property, then directions.`

// renderDevices produces the gofmt-formatted contents of devices.gen.go. The
// reagent table the device JSON carries is not rendered: a chip names a
// reagent by hash alone, so there is no name for the compiler to resolve.
func renderDevices(devices *Devices, isa *ISA) ([]byte, error) {
	if len(devices.Prefabs) == 0 {
		return nil, errors.New("prefab table is empty")
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\npackage isa\n\n")
	renderImports(&b, "strconv")
	accesses.render(&b)
	b.WriteString(prefabTypes)
	b.WriteString(prefabsDoc)
	b.WriteString("\nvar Prefabs = []Prefab{\n")
	logicTypes := enumValues(isa.LogicTypes)
	slotTypes := enumValues(isa.SlotTypes)
	for _, prefab := range devices.Prefabs {
		if err := renderPrefab(&b, prefab, logicTypes, slotTypes); err != nil {
			return nil, err
		}
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}

func renderPrefab(b *strings.Builder, prefab Prefab, logicTypes, slotTypes map[string]int64) error {
	if prefab.Name == "" {
		return errors.New("prefab table holds an unnamed entry")
	}
	fmt.Fprintf(b, "\t{Name: %q, Hash: %d", prefab.Name, prefab.Hash)
	if prefab.Title != "" {
		fmt.Fprintf(b, ", Title: %q", prefab.Title)
	}
	if prefab.CircuitHolder {
		b.WriteString(", CircuitHolder: true")
	}
	if prefab.CircuitHolderUnknown {
		b.WriteString(", CircuitHolderUnknown: true")
	}
	if prefab.ModesUnknown {
		b.WriteString(", ModesUnknown: true")
	}
	if len(prefab.Modes) > 0 {
		b.WriteString(",\n\t\tModes: []string{")
		for i, mode := range prefab.Modes {
			if mode.Value != i {
				return fmt.Errorf("prefab %s: mode %d is listed at position %d, and the generated table indexes modes by position",
					prefab.Name, mode.Value, i)
			}
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", mode.Name)
		}
		b.WriteString("}")
	}
	if len(prefab.Logic) > 0 {
		b.WriteString(",\n\t\tLogic: []LogicAccess{")
		if err := renderAccessList(b, prefab.Name, prefab.Logic, logicTypes, logicTypeWidth); err != nil {
			return err
		}
		b.WriteString("}")
	}
	if len(prefab.Slots) > 0 {
		b.WriteString(",\n\t\tSlots: []Slot{")
		for i, slot := range prefab.Slots {
			if slot.Index != i {
				return fmt.Errorf("prefab %s: slot %d is listed at position %d, and the generated table indexes slots by position",
					prefab.Name, slot.Index, i)
			}
			fmt.Fprintf(b, "\n\t\t\t{Class: %q, Types: []SlotAccess{", slot.Class)
			if err := renderAccessList(b, prefab.Name, slot.Types, slotTypes, slotTypeWidth); err != nil {
				return err
			}
			b.WriteString("}},")
		}
		b.WriteString("\n\t\t}")
	}
	b.WriteString("},\n")
	return nil
}

// The widths the rendered access entries carry their property selector in.
// There are 13426 logic entries and as many slot entries, so the narrowest type
// that holds every declared member is what the roster costs at run time; a
// selector the width cannot hold is reported rather than truncated.
const (
	logicTypeWidth = 1<<16 - 1
	slotTypeWidth  = 1<<8 - 1
)

func renderAccessList(b *strings.Builder, prefab string, entries []LogicAccess, values map[string]int64, widest int64) error {
	for i, entry := range entries {
		value, ok := values[entry.Name]
		if !ok {
			return fmt.Errorf("prefab %s: %s is not a member of the ISA enumeration it is listed under", prefab, entry.Name)
		}
		if value < 0 || value > widest {
			return fmt.Errorf("prefab %s: %s has value %d, which the rendered table's selector field cannot hold", prefab, entry.Name, value)
		}
		name, ok := goAccessConstants[string(entry.Access)]
		if !ok {
			return fmt.Errorf("prefab %s: property %s has access %q", prefab, entry.Name, entry.Access)
		}
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "{%d, %s}", value, name)
	}
	return nil
}

// renderEnum writes one operand enum table. The value is always emitted, since
// it is the identity generated code refers to.
func renderEnum(b *strings.Builder, sliceName, doc string, members []EnumMember) {
	b.WriteString(doc)
	fmt.Fprintf(b, "\nvar %s = []EnumMember{\n", sliceName)
	for _, member := range members {
		fmt.Fprintf(b, "\t{Name: %q, Value: %d", member.Name, member.Value)
		if member.Deprecated {
			b.WriteString(", Deprecated: true")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
}

// renderOperands writes an instruction's operand list as a Go composite
// literal, or the nil literal for the operandless forms.
func renderOperands(instruction Instruction) (string, error) {
	if len(instruction.Operands) == 0 {
		return "nil", nil
	}
	var b strings.Builder
	b.WriteString("[]Operand{")
	for i, operand := range instruction.Operands {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteByte('{')
		if operand.Name != "" {
			fmt.Fprintf(&b, "Name: %q, ", operand.Name)
		}
		if len(operand.Kinds) == 0 {
			return "", fmt.Errorf("instruction %s operand %d has no kinds", instruction.Mnemonic, i)
		}
		b.WriteString("Kinds: []OperandKind{")
		for j, kind := range operand.Kinds {
			name, ok := goOperandKinds[kind]
			if !ok {
				return "", fmt.Errorf("instruction %s operand %d: unknown kind %q", instruction.Mnemonic, i, kind)
			}
			if j > 0 {
				b.WriteString(", ")
			}
			b.WriteString(name)
		}
		direction, ok := goDirections[string(operand.Direction)]
		if !ok {
			return "", fmt.Errorf("instruction %s operand %d: unknown direction %q", instruction.Mnemonic, i, operand.Direction)
		}
		conversion, ok := goConversions[string(operand.Conversion)]
		if !ok {
			return "", fmt.Errorf("instruction %s operand %d: unknown conversion %q", instruction.Mnemonic, i, operand.Conversion)
		}
		fmt.Fprintf(&b, "}, Direction: %s, Conversion: %s}", direction, conversion)
	}
	b.WriteByte('}')
	return b.String(), nil
}

// renderImplicit renders the registers an instruction reaches without an
// operand naming them, and is empty for an instruction that reaches none.
func renderImplicit(instruction Instruction) (string, error) {
	if len(instruction.Implicit) == 0 {
		return "", nil
	}
	var b strings.Builder
	b.WriteString("[]ImplicitUse{")
	for i, use := range instruction.Implicit {
		register, ok := goRegisters[use.Register]
		if !ok {
			return "", fmt.Errorf("instruction %s: unknown implicit register %q", instruction.Mnemonic, use.Register)
		}
		direction, ok := goDirections[string(use.Direction)]
		if !ok {
			return "", fmt.Errorf("instruction %s: implicit %s has unknown direction %q", instruction.Mnemonic, use.Register, use.Direction)
		}
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "{Register: %s, Direction: %s}", register, direction)
	}
	b.WriteByte('}')
	return b.String(), nil
}

// needsMath reports whether any constant must be written as a math package
// call because Go has no literal for it.
func needsMath(values []float64) bool {
	for _, v := range values {
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return true
		}
	}
	return false
}

// goFloat renders v as a Go expression that evaluates to exactly v.
//
// A NaN is written as its bit pattern rather than as math.NaN, whose payload is
// Go's and not the game's.
func goFloat(v float64) string {
	switch {
	case math.IsNaN(v):
		return fmt.Sprintf("math.Float64frombits(%#x)", math.Float64bits(v))
	case math.IsInf(v, 1):
		return "math.Inf(1)"
	case math.IsInf(v, -1):
		return "math.Inf(-1)"
	default:
		return strconv.FormatFloat(v, 'g', -1, 64)
	}
}

// opcodeConst is the exported Go name for a mnemonic's opcode constant.
func opcodeConst(mnemonic string) string {
	return "Op" + strings.ToUpper(mnemonic[:1]) + mnemonic[1:]
}
